import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:sehatak/core/constants/app_colors.dart';
import 'package:sehatak/presentation/screens/advertisements/ad_management_screen.dart';
import 'package:sehatak/core/models/ad_model.dart';

class AdminDashboard extends StatefulWidget { const AdminDashboard({super.key}); @override State<AdminDashboard> createState()=>_AdminDashboardState(); }
class _AdminDashboardState extends State<AdminDashboard> with SingleTickerProviderStateMixin {
  late TabController _tabController; int _totalUsers=0,_totalProviders=0,_totalBookings=0,_totalRevenue=0,_pendingAds=0;
  @override void initState(){super.initState();_tabController=TabController(length:4,vsync:this);_loadStats();}
  Future<void> _loadStats() async { try { final users=await FirebaseFirestore.instance.collection('users').get(); final providers=await Future.wait([FirebaseFirestore.instance.collection('doctors').get(),FirebaseFirestore.instance.collection('pharmacies').get(),FirebaseFirestore.instance.collection('labs').get(),FirebaseFirestore.instance.collection('hospitals').get()]); final bookings=await FirebaseFirestore.instance.collection('bookings').get(); final ads=await FirebaseFirestore.instance.collection('advertisements').where('status',isEqualTo:'pending').get(); if(!mounted)return; setState((){_totalUsers=users.size;_totalProviders=providers.fold<int>(0,(s,q)=>s+q.size);_totalBookings=bookings.size;_totalRevenue=bookings.docs.fold<int>(0,(s,d)=>s+((d.data()['amount'] as num?)?.toInt()??0));_pendingAds=ads.size;}); } catch(e){debugPrint('Error loading stats: $e');} }
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('لوحة تحكم المشرف'),actions:[IconButton(onPressed:_loadStats,icon:const Icon(Icons.refresh)),IconButton(onPressed:()=>FirebaseAuth.instance.signOut(),icon:const Icon(Icons.logout))]),body:Column(children:[Container(color:AppColors.primary,padding:const EdgeInsets.all(12),child:Row(children:[_stat('المستخدمين','$_totalUsers',Icons.people),_stat('المقدمين','$_totalProviders',Icons.business),_stat('الحجوزات','$_totalBookings',Icons.event),_stat('الإيرادات','$_totalRevenue',Icons.attach_money)])),if(_pendingAds>0)ListTile(leading:const Icon(Icons.campaign,color:Colors.orange),title:Text('$_pendingAds إعلان في انتظار المراجعة'),trailing:TextButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>AdManagementScreen(providerId:FirebaseAuth.instance.currentUser?.uid,providerType:AdType.general)),child:const Text('مراجعة'))),),Container(color:Colors.white,child:TabBar(controller:_tabController,tabs:const[Tab(text:'الرئيسية'),Tab(text:'المستخدمين'),Tab(text:'المقدمين'),Tab(text:'الإعلانات')])),Expanded(child:TabBarView(controller:_tabController,children:[_home(),_users(),_providers(),_ads()]))]));
  Widget _stat(String l,String v,IconData i)=>Expanded(child:Column(children:[Icon(i,color:Colors.white),Text(v,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.bold)),Text(l,style:const TextStyle(color:Colors.white70,fontSize:10))]));
  Widget _home()=>GridView.count(padding:const EdgeInsets.all(16),crossAxisCount:2,crossAxisSpacing:12,mainAxisSpacing:12,children:[_card('المستخدمين','$_totalUsers',Icons.people),_card('المقدمين','$_totalProviders',Icons.business),_card('الحجوزات','$_totalBookings',Icons.event),_card('الإيرادات','$_totalRevenue ريال',Icons.attach_money),_card('الإعلانات','$_pendingAds قيد المراجعة',Icons.campaign),_card('المنصة','نشطة',Icons.check_circle)]);
  Widget _card(String t,String v,IconData i)=>Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(i,color:AppColors.primary),const SizedBox(height:8),Text(v,style:const TextStyle(fontWeight:FontWeight.bold)),Text(t,style:const TextStyle(color:Colors.grey))])));
  Widget _users()=>StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:FirebaseFirestore.instance.collection('users').snapshots(),builder:(c,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());return ListView(children:s.data!.docs.map((d){final x=d.data();return ListTile(leading:const CircleAvatar(child:Icon(Icons.person)),title:Text(x['name']?.toString()??'مستخدم'),subtitle:Text(x['email']?.toString()??''));}).toList());});
  Widget _providers()=>DefaultTabController(length:4,child:Column(children:[const TabBar(tabs:[Tab(text:'أطباء'),Tab(text:'صيدليات'),Tab(text:'مختبرات'),Tab(text:'مستشفيات')]),Expanded(child:TabBarView(children:[_providerList('doctors'),_providerList('pharmacies'),_providerList('labs'),_providerList('hospitals')]))]));
  Widget _providerList(String col)=>StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:FirebaseFirestore.instance.collection(col).snapshots(),builder:(c,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());return ListView(children:s.data!.docs.map((d)=>ListTile(leading:const Icon(Icons.business),title:Text(d.data()['name']?.toString()??'غير معروف'),subtitle:Text(d.data()['address']?.toString()??''))).toList());});
  Widget _ads()=>Center(child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.campaign,size:64,color:Colors.grey),const SizedBox(height:12),const Text('إدارة الإعلانات'),ElevatedButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const AdManagementScreen())),child:const Text('فتح'))]));
  @override void dispose(){_tabController.dispose();super.dispose();}
}
