import 'package:sehatak/core/services/toast_service.dart';
import 'package:sehatak/presentation/widgets/common/custom_app_bar.dart';
import 'package:flutter/material.dart';
import 'package:sehatak/core/constants/app_colors.dart';

class ChangePasswordScreen extends StatefulWidget { const ChangePasswordScreen({super.key}); @override State<ChangePasswordScreen> createState()=>_ChangePasswordScreenState(); }
class _ChangePasswordScreenState extends State<ChangePasswordScreen> {
 final current=TextEditingController(),password=TextEditingController(),confirm=TextEditingController(); bool obscureCurrent=true,obscureNew=true,obscureConfirm=true; String strength=''; Color strengthColor=AppColors.grey;
 @override void dispose(){current.dispose();password.dispose();confirm.dispose();super.dispose();}
 void check(String value){final score=(value.length>=8?1:0)+(value.contains(RegExp(r'[A-Z]'))?1:0)+(value.contains(RegExp(r'[0-9]'))?1:0)+(value.contains(RegExp(r'[!@#$%^&*(),.?":{}|<>]'))?1:0);setState((){switch(score){case 0:case 1:strength='ضعيفة';strengthColor=AppColors.error;break;case 2:strength='متوسطة';strengthColor=AppColors.warning;break;case 3:strength='قوية';strengthColor=AppColors.info;break;default:strength='قوية جداً';strengthColor=AppColors.success;}});}
 bool get canSave=>current.text.isNotEmpty&&password.text.length>=6&&password.text==confirm.text;
 void save(){if(!canSave){ToastService.showError(context,'يرجى التأكد من صحة البيانات');return;}showDialog<void>(context:context,builder:(dialogContext)=>AlertDialog(title:const Text('تم بنجاح'),content:const Text('تم تغيير كلمة المرور بنجاح'),actions:[TextButton(onPressed:(){Navigator.pop(dialogContext);Navigator.pop(context);},child:const Text('حسناً'))]));}
 @override Widget build(BuildContext context){final progress=strength=='ضعيفة'?0.25:strength=='متوسطة'?0.5:strength=='قوية'?0.75:strength.isEmpty?0.0:1.0;return Scaffold(appBar:CustomAppBar(title:const Text('تغيير كلمة المرور',style:TextStyle(fontWeight:FontWeight.bold))),body:SingleChildScrollView(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Center(child:Container(width:80,height:80,decoration:BoxDecoration(color:AppColors.primary.withOpacity(.08),shape:BoxShape.circle),child:const Icon(Icons.lock_outline,color:AppColors.primary,size:40))),const SizedBox(height:24),_field(current,'كلمة المرور الحالية',obscureCurrent,()=>setState(()=>obscureCurrent=!obscureCurrent),Icons.lock_outline),const SizedBox(height:14),_field(password,'كلمة المرور الجديدة',obscureNew,()=>setState(()=>obscureNew=!obscureNew),Icons.lock,onChanged:check),if(password.text.isNotEmpty)Padding(padding:const EdgeInsets.only(top:8),child:Row(children:[Text('قوة كلمة المرور: $strength',style:TextStyle(color:strengthColor,fontSize:12)),const SizedBox(width:8),Expanded(child:LinearProgressIndicator(value:progress,color:strengthColor,minHeight:4))])),const SizedBox(height:14),_field(confirm,'تأكيد كلمة المرور',obscureConfirm,()=>setState(()=>obscureConfirm=!obscureConfirm),Icons.lock),if(confirm.text.isNotEmpty)Padding(padding:const EdgeInsets.only(top:6),child:Row(children:[Icon(password.text==confirm.text?Icons.check_circle:Icons.cancel,size:14,color:password.text==confirm.text?AppColors.success:AppColors.error),const SizedBox(width:6),Text(password.text==confirm.text?'كلمتا المرور متطابقتان':'كلمتا المرور غير متطابقتين',style:TextStyle(fontSize:11,color:password.text==confirm.text?AppColors.success:AppColors.error))])),const SizedBox(height:24),Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:AppColors.warning.withOpacity(.05),borderRadius:BorderRadius.circular(12)),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('نصائح لكلمة مرور آمنة',style:TextStyle(fontWeight:FontWeight.bold)),SizedBox(height:8),Text('• 8 أحرف على الأقل'),Text('• حرف كبير وصغير'),Text('• رقم واحد على الأقل'),Text('• رمز خاص (!@#\$%^&*)')])) ,const SizedBox(height:24),SizedBox(width:double.infinity,child:ElevatedButton(onPressed:canSave?save:null,style:ElevatedButton.styleFrom(backgroundColor:AppColors.primary,foregroundColor:Colors.white),child:const Text('حفظ كلمة المرور الجديدة')))])));
 }
 Widget _field(TextEditingController controller,String label,bool obscure,VoidCallback toggle,IconData icon,{ValueChanged<String>? onChanged})=>TextField(controller:controller,obscureText:obscure,onChanged:onChanged,textAlign:TextAlign.right,decoration:InputDecoration(labelText:label,prefixIcon:Icon(icon),suffixIcon:IconButton(icon:Icon(obscure?Icons.visibility_off:Icons.visibility),onPressed:toggle),border:OutlineInputBorder(borderRadius:BorderRadius.circular(12)),filled:true,fillColor:AppColors.surfaceContainerLow.withOpacity(.3)));
}
