// ============================================================
// Sehatak - 300 منتج فريد للصيدلية
// Collection: products
// ============================================================

const admin = require("firebase-admin");
const serviceAccount = require("./service-account.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
});

const db = admin.firestore();

const products = [
  // ============================================================
  // 1️⃣ مسكنات وخافضات حرارة (50 دواء)
  // ============================================================
  {
    id: "med_001",
    name: "باراسيتامول 500 مجم",
    genericName: "Paracetamol",
    activeIngredient: "Paracetamol 500 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "500 mg",
    packageSize: "20 قرص",
    price: 500,
    stock: 100,
    requiresPrescription: false,
  },
  {
    id: "med_002",
    name: "باراسيتامول 1 جرام",
    genericName: "Paracetamol",
    activeIngredient: "Paracetamol 1000 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "1000 mg",
    packageSize: "20 قرص",
    price: 800,
    stock: 100,
    requiresPrescription: false,
  },
  {
    id: "med_003",
    name: "باراسيتامول شراب للأطفال",
    genericName: "Paracetamol",
    activeIngredient: "Paracetamol 120 mg/5ml",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "شراب",
    strength: "120 mg/5 ml",
    packageSize: "100 ml",
    price: 700,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_004",
    name: "إيبوبروفين 200 مجم",
    genericName: "Ibuprofen",
    activeIngredient: "Ibuprofen 200 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "200 mg",
    packageSize: "20 قرص",
    price: 900,
    stock: 90,
    requiresPrescription: false,
  },
  {
    id: "med_005",
    name: "إيبوبروفين 400 مجم",
    genericName: "Ibuprofen",
    activeIngredient: "Ibuprofen 400 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "400 mg",
    packageSize: "20 قرص",
    price: 1200,
    stock: 90,
    requiresPrescription: false,
  },
  {
    id: "med_006",
    name: "إيبوبروفين 600 مجم",
    genericName: "Ibuprofen",
    activeIngredient: "Ibuprofen 600 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "600 mg",
    packageSize: "20 قرص",
    price: 1500,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_007",
    name: "نابروكسين 250 مجم",
    genericName: "Naproxen",
    activeIngredient: "Naproxen 250 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "250 mg",
    packageSize: "20 قرص",
    price: 1100,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_008",
    name: "نابروكسين 500 مجم",
    genericName: "Naproxen",
    activeIngredient: "Naproxen 500 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "500 mg",
    packageSize: "20 قرص",
    price: 1600,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_009",
    name: "ديكلوفيناك 50 مجم",
    genericName: "Diclofenac",
    activeIngredient: "Diclofenac 50 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "50 mg",
    packageSize: "20 قرص",
    price: 1000,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_010",
    name: "ديكلوفيناك 100 مجم",
    genericName: "Diclofenac",
    activeIngredient: "Diclofenac 100 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "100 mg",
    packageSize: "20 قرص",
    price: 1400,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_011",
    name: "أسبرين 100 مجم",
    genericName: "Aspirin",
    activeIngredient: "Acetylsalicylic Acid 100 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "100 mg",
    packageSize: "30 قرص",
    price: 600,
    stock: 100,
    requiresPrescription: false,
  },
  {
    id: "med_012",
    name: "أسبرين 300 مجم",
    genericName: "Aspirin",
    activeIngredient: "Acetylsalicylic Acid 300 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "300 mg",
    packageSize: "30 قرص",
    price: 800,
    stock: 100,
    requiresPrescription: false,
  },
  {
    id: "med_013",
    name: "أسبرين 500 مجم",
    genericName: "Aspirin",
    activeIngredient: "Acetylsalicylic Acid 500 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "500 mg",
    packageSize: "30 قرص",
    price: 1000,
    stock: 90,
    requiresPrescription: false,
  },
  {
    id: "med_014",
    name: "كيتورولاك 10 مجم",
    genericName: "Ketorolac",
    activeIngredient: "Ketorolac 10 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "10 mg",
    packageSize: "20 قرص",
    price: 1300,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_015",
    name: "كيتورولاك 30 مجم حقن",
    genericName: "Ketorolac",
    activeIngredient: "Ketorolac 30 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "حقن",
    strength: "30 mg",
    packageSize: "1 حقنة",
    price: 1800,
    stock: 40,
    requiresPrescription: true,
  },
  {
    id: "med_016",
    name: "ميفيناميك أسيد 500 مجم",
    genericName: "Mefenamic Acid",
    activeIngredient: "Mefenamic Acid 500 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "500 mg",
    packageSize: "20 قرص",
    price: 1200,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_017",
    name: "إندوميثاسين 25 مجم",
    genericName: "Indomethacin",
    activeIngredient: "Indomethacin 25 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "كبسولات",
    strength: "25 mg",
    packageSize: "20 كبسولة",
    price: 900,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_018",
    name: "إندوميثاسين 50 مجم",
    genericName: "Indomethacin",
    activeIngredient: "Indomethacin 50 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "كبسولات",
    strength: "50 mg",
    packageSize: "20 كبسولة",
    price: 1200,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_019",
    name: "بيوكسيكام 20 مجم",
    genericName: "Piroxicam",
    activeIngredient: "Piroxicam 20 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "20 mg",
    packageSize: "20 قرص",
    price: 1000,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_020",
    name: "ميلوكسيكام 7.5 مجم",
    genericName: "Meloxicam",
    activeIngredient: "Meloxicam 7.5 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "7.5 mg",
    packageSize: "20 قرص",
    price: 1100,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_021",
    name: "ميلوكسيكام 15 مجم",
    genericName: "Meloxicam",
    activeIngredient: "Meloxicam 15 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "15 mg",
    packageSize: "20 قرص",
    price: 1400,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_022",
    name: "سيليكوكسيب 100 مجم",
    genericName: "Celecoxib",
    activeIngredient: "Celecoxib 100 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "كبسولات",
    strength: "100 mg",
    packageSize: "20 كبسولة",
    price: 1500,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_023",
    name: "سيليكوكسيب 200 مجم",
    genericName: "Celecoxib",
    activeIngredient: "Celecoxib 200 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "كبسولات",
    strength: "200 mg",
    packageSize: "20 كبسولة",
    price: 1800,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_024",
    name: "ترامادول 50 مجم",
    genericName: "Tramadol",
    activeIngredient: "Tramadol 50 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "50 mg",
    packageSize: "20 قرص",
    price: 2000,
    stock: 50,
    requiresPrescription: true,
  },
  {
    id: "med_025",
    name: "ترامادول 100 مجم",
    genericName: "Tramadol",
    activeIngredient: "Tramadol 100 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "100 mg",
    packageSize: "20 قرص",
    price: 2500,
    stock: 50,
    requiresPrescription: true,
  },
  {
    id: "med_026",
    name: "كودايين 15 مجم",
    genericName: "Codeine",
    activeIngredient: "Codeine 15 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "15 mg",
    packageSize: "20 قرص",
    price: 1800,
    stock: 40,
    requiresPrescription: true,
  },
  {
    id: "med_027",
    name: "كودايين 30 مجم",
    genericName: "Codeine",
    activeIngredient: "Codeine 30 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "30 mg",
    packageSize: "20 قرص",
    price: 2200,
    stock: 40,
    requiresPrescription: true,
  },
  {
    id: "med_028",
    name: "مورفين 10 مجم",
    genericName: "Morphine",
    activeIngredient: "Morphine 10 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "10 mg",
    packageSize: "20 قرص",
    price: 3000,
    stock: 30,
    requiresPrescription: true,
  },
  {
    id: "med_029",
    name: "مورفين 30 مجم",
    genericName: "Morphine",
    activeIngredient: "Morphine 30 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "30 mg",
    packageSize: "20 قرص",
    price: 3500,
    stock: 30,
    requiresPrescription: true,
  },
  {
    id: "med_030",
    name: "فنتانيل 50 ميكروجرام",
    genericName: "Fentanyl",
    activeIngredient: "Fentanyl 50 mcg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "لاصقات",
    strength: "50 mcg",
    packageSize: "5 لاصقات",
    price: 4000,
    stock: 20,
    requiresPrescription: true,
  },
  {
    id: "med_031",
    name: "فنتانيل 100 ميكروجرام",
    genericName: "Fentanyl",
    activeIngredient: "Fentanyl 100 mcg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "لاصقات",
    strength: "100 mcg",
    packageSize: "5 لاصقات",
    price: 4500,
    stock: 20,
    requiresPrescription: true,
  },
  {
    id: "med_032",
    name: "أوكسيكودون 10 مجم",
    genericName: "Oxycodone",
    activeIngredient: "Oxycodone 10 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "10 mg",
    packageSize: "20 قرص",
    price: 2800,
    stock: 30,
    requiresPrescription: true,
  },
  {
    id: "med_033",
    name: "أوكسيكودون 20 مجم",
    genericName: "Oxycodone",
    activeIngredient: "Oxycodone 20 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "20 mg",
    packageSize: "20 قرص",
    price: 3200,
    stock: 30,
    requiresPrescription: true,
  },
  {
    id: "med_034",
    name: "هيدروكودون 10 مجم",
    genericName: "Hydrocodone",
    activeIngredient: "Hydrocodone 10 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "10 mg",
    packageSize: "20 قرص",
    price: 2600,
    stock: 30,
    requiresPrescription: true,
  },
  {
    id: "med_035",
    name: "بنتازوسين 25 مجم",
    genericName: "Pentazocine",
    activeIngredient: "Pentazocine 25 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "25 mg",
    packageSize: "20 قرص",
    price: 2000,
    stock: 30,
    requiresPrescription: true,
  },
  {
    id: "med_036",
    name: "بنتازوسين 50 مجم",
    genericName: "Pentazocine",
    activeIngredient: "Pentazocine 50 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "50 mg",
    packageSize: "20 قرص",
    price: 2400,
    stock: 30,
    requiresPrescription: true,
  },
  {
    id: "med_037",
    name: "ميبريستون 200 مجم",
    genericName: "Mebeverine",
    activeIngredient: "Mebeverine 200 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "200 mg",
    packageSize: "20 قرص",
    price: 1500,
    stock: 50,
    requiresPrescription: true,
  },
  {
    id: "med_038",
    name: "كلونيدين 0.1 مجم",
    genericName: "Clonidine",
    activeIngredient: "Clonidine 0.1 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "0.1 mg",
    packageSize: "20 قرص",
    price: 800,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_039",
    name: "كلونيدين 0.2 مجم",
    genericName: "Clonidine",
    activeIngredient: "Clonidine 0.2 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "0.2 mg",
    packageSize: "20 قرص",
    price: 1000,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_040",
    name: "ميثيلدوبا 250 مجم",
    genericName: "Methyldopa",
    activeIngredient: "Methyldopa 250 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "250 mg",
    packageSize: "20 قرص",
    price: 900,
    stock: 50,
    requiresPrescription: true,
  },
  {
    id: "med_041",
    name: "ميثيلدوبا 500 مجم",
    genericName: "Methyldopa",
    activeIngredient: "Methyldopa 500 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "500 mg",
    packageSize: "20 قرص",
    price: 1200,
    stock: 50,
    requiresPrescription: true,
  },
  {
    id: "med_042",
    name: "مينوكسيديل 2.5 مجم",
    genericName: "Minoxidil",
    activeIngredient: "Minoxidil 2.5 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "2.5 mg",
    packageSize: "20 قرص",
    price: 1100,
    stock: 50,
    requiresPrescription: true,
  },
  {
    id: "med_043",
    name: "مينوكسيديل 5 مجم",
    genericName: "Minoxidil",
    activeIngredient: "Minoxidil 5 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "5 mg",
    packageSize: "20 قرص",
    price: 1400,
    stock: 50,
    requiresPrescription: true,
  },
  {
    id: "med_044",
    name: "باراسيتامول 125 مجم للأطفال",
    genericName: "Paracetamol",
    activeIngredient: "Paracetamol 125 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "125 mg",
    packageSize: "20 قرص",
    price: 400,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_045",
    name: "باراسيتامول 250 مجم للأطفال",
    genericName: "Paracetamol",
    activeIngredient: "Paracetamol 250 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "250 mg",
    packageSize: "20 قرص",
    price: 450,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_046",
    name: "إيبوبروفين 100 مجم للأطفال",
    genericName: "Ibuprofen",
    activeIngredient: "Ibuprofen 100 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "100 mg",
    packageSize: "20 قرص",
    price: 600,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_047",
    name: "إيبوبروفين شراب للأطفال",
    genericName: "Ibuprofen",
    activeIngredient: "Ibuprofen 100 mg/5ml",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "شراب",
    strength: "100 mg/5 ml",
    packageSize: "100 ml",
    price: 800,
    stock: 70,
    requiresPrescription: false,
  },
  {
    id: "med_048",
    name: "نابروكسين 125 مجم للأطفال",
    genericName: "Naproxen",
    activeIngredient: "Naproxen 125 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "125 mg",
    packageSize: "20 قرص",
    price: 800,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_049",
    name: "ديكلوفيناك 25 مجم للأطفال",
    genericName: "Diclofenac",
    activeIngredient: "Diclofenac 25 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "25 mg",
    packageSize: "20 قرص",
    price: 700,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_050",
    name: "أسبرين 75 مجم للأطفال",
    genericName: "Aspirin",
    activeIngredient: "Acetylsalicylic Acid 75 mg",
    category: "مسكنات وخافضات حرارة",
    dosageForm: "أقراص",
    strength: "75 mg",
    packageSize: "30 قرص",
    price: 500,
    stock: 70,
    requiresPrescription: false,
  },

  // ============================================================
  // 2️⃣ مضادات حيوية (50 دواء)
  // ============================================================
  {
    id: "med_051",
    name: "أموكسيسيلين 250 مجم",
    genericName: "Amoxicillin",
    activeIngredient: "Amoxicillin 250 mg",
    category: "مضادات حيوية",
    dosageForm: "كبسولات",
    strength: "250 mg",
    packageSize: "16 كبسولة",
    price: 800,
    stock: 100,
    requiresPrescription: true,
  },
  {
    id: "med_052",
    name: "أموكسيسيلين 500 مجم",
    genericName: "Amoxicillin",
    activeIngredient: "Amoxicillin 500 mg",
    category: "مضادات حيوية",
    dosageForm: "كبسولات",
    strength: "500 mg",
    packageSize: "16 كبسولة",
    price: 1200,
    stock: 100,
    requiresPrescription: true,
  },
  {
    id: "med_053",
    name: "أموكسيسيلين 1 جم",
    genericName: "Amoxicillin",
    activeIngredient: "Amoxicillin 1000 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "1000 mg",
    packageSize: "16 قرص",
    price: 1600,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_054",
    name: "أموكسيسيلين شراب للأطفال",
    genericName: "Amoxicillin",
    activeIngredient: "Amoxicillin 125 mg/5ml",
    category: "مضادات حيوية",
    dosageForm: "شراب",
    strength: "125 mg/5 ml",
    packageSize: "100 ml",
    price: 900,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_055",
    name: "أموكسيسيلين + كلافولانيك أسيد 625 مجم",
    genericName: "Amoxicillin + Clavulanic Acid",
    activeIngredient: "Amoxicillin 500 mg + Clavulanic Acid 125 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "625 mg",
    packageSize: "14 قرص",
    price: 1800,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_056",
    name: "أموكسيسيلين + كلافولانيك أسيد 1 جم",
    genericName: "Amoxicillin + Clavulanic Acid",
    activeIngredient: "Amoxicillin 875 mg + Clavulanic Acid 125 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "1000 mg",
    packageSize: "14 قرص",
    price: 2200,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_057",
    name: "أزيثروميسين 250 مجم",
    genericName: "Azithromycin",
    activeIngredient: "Azithromycin 250 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "250 mg",
    packageSize: "6 قرص",
    price: 1500,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_058",
    name: "أزيثروميسين 500 مجم",
    genericName: "Azithromycin",
    activeIngredient: "Azithromycin 500 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "500 mg",
    packageSize: "3 قرص",
    price: 2000,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_059",
    name: "أزيثروميسين 200 مجم شراب",
    genericName: "Azithromycin",
    activeIngredient: "Azithromycin 200 mg/5ml",
    category: "مضادات حيوية",
    dosageForm: "شراب",
    strength: "200 mg/5 ml",
    packageSize: "30 ml",
    price: 1200,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_060",
    name: "سيبروفلوكساسين 250 مجم",
    genericName: "Ciprofloxacin",
    activeIngredient: "Ciprofloxacin 250 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "250 mg",
    packageSize: "20 قرص",
    price: 1000,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_061",
    name: "سيبروفلوكساسين 500 مجم",
    genericName: "Ciprofloxacin",
    activeIngredient: "Ciprofloxacin 500 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "500 mg",
    packageSize: "20 قرص",
    price: 1400,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_062",
    name: "سيبروفلوكساسين 750 مجم",
    genericName: "Ciprofloxacin",
    activeIngredient: "Ciprofloxacin 750 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "750 mg",
    packageSize: "20 قرص",
    price: 1800,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_063",
    name: "ليفوفلوكساسين 250 مجم",
    genericName: "Levofloxacin",
    activeIngredient: "Levofloxacin 250 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "250 mg",
    packageSize: "10 قرص",
    price: 1200,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_064",
    name: "ليفوفلوكساسين 500 مجم",
    genericName: "Levofloxacin",
    activeIngredient: "Levofloxacin 500 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "500 mg",
    packageSize: "10 قرص",
    price: 1600,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_065",
    name: "ليفوفلوكساسين 750 مجم",
    genericName: "Levofloxacin",
    activeIngredient: "Levofloxacin 750 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "750 mg",
    packageSize: "10 قرص",
    price: 2000,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_066",
    name: "دوكسيسايكلين 100 مجم",
    genericName: "Doxycycline",
    activeIngredient: "Doxycycline 100 mg",
    category: "مضادات حيوية",
    dosageForm: "كبسولات",
    strength: "100 mg",
    packageSize: "20 كبسولة",
    price: 900,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_067",
    name: "دوكسيسايكلين 50 مجم",
    genericName: "Doxycycline",
    activeIngredient: "Doxycycline 50 mg",
    category: "مضادات حيوية",
    dosageForm: "كبسولات",
    strength: "50 mg",
    packageSize: "20 كبسولة",
    price: 700,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_068",
    name: "تتراسايكلين 250 مجم",
    genericName: "Tetracycline",
    activeIngredient: "Tetracycline 250 mg",
    category: "مضادات حيوية",
    dosageForm: "كبسولات",
    strength: "250 mg",
    packageSize: "20 كبسولة",
    price: 800,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_069",
    name: "تتراسايكلين 500 مجم",
    genericName: "Tetracycline",
    activeIngredient: "Tetracycline 500 mg",
    category: "مضادات حيوية",
    dosageForm: "كبسولات",
    strength: "500 mg",
    packageSize: "20 كبسولة",
    price: 1100,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_070",
    name: "كلاريثروميسين 250 مجم",
    genericName: "Clarithromycin",
    activeIngredient: "Clarithromycin 250 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "250 mg",
    packageSize: "14 قرص",
    price: 1400,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_071",
    name: "كلاريثروميسين 500 مجم",
    genericName: "Clarithromycin",
    activeIngredient: "Clarithromycin 500 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "500 mg",
    packageSize: "14 قرص",
    price: 1800,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_072",
    name: "كلاريثروميسين 125 مجم شراب",
    genericName: "Clarithromycin",
    activeIngredient: "Clarithromycin 125 mg/5ml",
    category: "مضادات حيوية",
    dosageForm: "شراب",
    strength: "125 mg/5 ml",
    packageSize: "60 ml",
    price: 1200,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_073",
    name: "سيفاليكسين 250 مجم",
    genericName: "Cephalexin",
    activeIngredient: "Cephalexin 250 mg",
    category: "مضادات حيوية",
    dosageForm: "كبسولات",
    strength: "250 mg",
    packageSize: "20 كبسولة",
    price: 800,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_074",
    name: "سيفاليكسين 500 مجم",
    genericName: "Cephalexin",
    activeIngredient: "Cephalexin 500 mg",
    category: "مضادات حيوية",
    dosageForm: "كبسولات",
    strength: "500 mg",
    packageSize: "20 كبسولة",
    price: 1200,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_075",
    name: "سيفاليكسين 1 جم",
    genericName: "Cephalexin",
    activeIngredient: "Cephalexin 1000 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "1000 mg",
    packageSize: "20 قرص",
    price: 1600,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_076",
    name: "سيفترياكسون 1 جم حقن",
    genericName: "Ceftriaxone",
    activeIngredient: "Ceftriaxone 1000 mg",
    category: "مضادات حيوية",
    dosageForm: "حقن",
    strength: "1000 mg",
    packageSize: "1 حقنة",
    price: 2000,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_077",
    name: "سيفترياكسون 500 مجم حقن",
    genericName: "Ceftriaxone",
    activeIngredient: "Ceftriaxone 500 mg",
    category: "مضادات حيوية",
    dosageForm: "حقن",
    strength: "500 mg",
    packageSize: "1 حقنة",
    price: 1500,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_078",
    name: "مترونيدازول 250 مجم",
    genericName: "Metronidazole",
    activeIngredient: "Metronidazole 250 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "250 mg",
    packageSize: "20 قرص",
    price: 600,
    stock: 100,
    requiresPrescription: true,
  },
  {
    id: "med_079",
    name: "مترونيدازول 500 مجم",
    genericName: "Metronidazole",
    activeIngredient: "Metronidazole 500 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "500 mg",
    packageSize: "20 قرص",
    price: 800,
    stock: 100,
    requiresPrescription: true,
  },
  {
    id: "med_080",
    name: "مترونيدازول شراب للأطفال",
    genericName: "Metronidazole",
    activeIngredient: "Metronidazole 125 mg/5ml",
    category: "مضادات حيوية",
    dosageForm: "شراب",
    strength: "125 mg/5 ml",
    packageSize: "100 ml",
    price: 700,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_081",
    name: "تينيدازول 500 مجم",
    genericName: "Tinidazole",
    activeIngredient: "Tinidazole 500 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "500 mg",
    packageSize: "20 قرص",
    price: 700,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_082",
    name: "تينيدازول 1 جم",
    genericName: "Tinidazole",
    activeIngredient: "Tinidazole 1000 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "1000 mg",
    packageSize: "20 قرص",
    price: 1000,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_083",
    name: "نيتروفورانتوين 100 مجم",
    genericName: "Nitrofurantoin",
    activeIngredient: "Nitrofurantoin 100 mg",
    category: "مضادات حيوية",
    dosageForm: "كبسولات",
    strength: "100 mg",
    packageSize: "20 كبسولة",
    price: 800,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_084",
    name: "نيتروفورانتوين 50 مجم",
    genericName: "Nitrofurantoin",
    activeIngredient: "Nitrofurantoin 50 mg",
    category: "مضادات حيوية",
    dosageForm: "كبسولات",
    strength: "50 mg",
    packageSize: "20 كبسولة",
    price: 600,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_085",
    name: "كليندامايسين 150 مجم",
    genericName: "Clindamycin",
    activeIngredient: "Clindamycin 150 mg",
    category: "مضادات حيوية",
    dosageForm: "كبسولات",
    strength: "150 mg",
    packageSize: "16 كبسولة",
    price: 1400,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_086",
    name: "كليندامايسين 300 مجم",
    genericName: "Clindamycin",
    activeIngredient: "Clindamycin 300 mg",
    category: "مضادات حيوية",
    dosageForm: "كبسولات",
    strength: "300 mg",
    packageSize: "16 كبسولة",
    price: 1800,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_087",
    name: "فانكومايسين 500 مجم حقن",
    genericName: "Vancomycin",
    activeIngredient: "Vancomycin 500 mg",
    category: "مضادات حيوية",
    dosageForm: "حقن",
    strength: "500 mg",
    packageSize: "1 حقنة",
    price: 2500,
    stock: 40,
    requiresPrescription: true,
  },
  {
    id: "med_088",
    name: "فانكومايسين 1 جم حقن",
    genericName: "Vancomycin",
    activeIngredient: "Vancomycin 1000 mg",
    category: "مضادات حيوية",
    dosageForm: "حقن",
    strength: "1000 mg",
    packageSize: "1 حقنة",
    price: 3000,
    stock: 40,
    requiresPrescription: true,
  },
  {
    id: "med_089",
    name: "لينزوليد 600 مجم",
    genericName: "Linezolid",
    activeIngredient: "Linezolid 600 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "600 mg",
    packageSize: "10 قرص",
    price: 2800,
    stock: 50,
    requiresPrescription: true,
  },
  {
    id: "med_090",
    name: "لينزوليد شراب للأطفال",
    genericName: "Linezolid",
    activeIngredient: "Linezolid 100 mg/5ml",
    category: "مضادات حيوية",
    dosageForm: "شراب",
    strength: "100 mg/5 ml",
    packageSize: "100 ml",
    price: 2200,
    stock: 40,
    requiresPrescription: true,
  },
  {
    id: "med_091",
    name: "بنسلين 500 مجم",
    genericName: "Penicillin",
    activeIngredient: "Penicillin V 500 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "500 mg",
    packageSize: "20 قرص",
    price: 900,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_092",
    name: "أمبيسيلين 250 مجم",
    genericName: "Ampicillin",
    activeIngredient: "Ampicillin 250 mg",
    category: "مضادات حيوية",
    dosageForm: "كبسولات",
    strength: "250 mg",
    packageSize: "20 كبسولة",
    price: 700,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_093",
    name: "أمبيسيلين 500 مجم",
    genericName: "Ampicillin",
    activeIngredient: "Ampicillin 500 mg",
    category: "مضادات حيوية",
    dosageForm: "كبسولات",
    strength: "500 mg",
    packageSize: "20 كبسولة",
    price: 1000,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_094",
    name: "سيفيكزيم 100 مجم",
    genericName: "Cefixime",
    activeIngredient: "Cefixime 100 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "100 mg",
    packageSize: "10 قرص",
    price: 1200,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_095",
    name: "سيفيكزيم 200 مجم",
    genericName: "Cefixime",
    activeIngredient: "Cefixime 200 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "200 mg",
    packageSize: "10 قرص",
    price: 1600,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_096",
    name: "سيفوروكسيم 250 مجم",
    genericName: "Cefuroxime",
    activeIngredient: "Cefuroxime 250 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "250 mg",
    packageSize: "10 قرص",
    price: 1400,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_097",
    name: "سيفوروكسيم 500 مجم",
    genericName: "Cefuroxime",
    activeIngredient: "Cefuroxime 500 mg",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "500 mg",
    packageSize: "10 قرص",
    price: 1800,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_098",
    name: "سيفوكسيتين 1 جم حقن",
    genericName: "Cefoxitin",
    activeIngredient: "Cefoxitin 1000 mg",
    category: "مضادات حيوية",
    dosageForm: "حقن",
    strength: "1000 mg",
    packageSize: "1 حقنة",
    price: 2000,
    stock: 50,
    requiresPrescription: true,
  },
  {
    id: "med_099",
    name: "سيفوتاكسيم 1 جم حقن",
    genericName: "Cefotaxime",
    activeIngredient: "Cefotaxime 1000 mg",
    category: "مضادات حيوية",
    dosageForm: "حقن",
    strength: "1000 mg",
    packageSize: "1 حقنة",
    price: 1900,
    stock: 50,
    requiresPrescription: true,
  },
  {
    id: "med_100",
    name: "سيفتازيديم 1 جم حقن",
    genericName: "Ceftazidime",
    activeIngredient: "Ceftazidime 1000 mg",
    category: "مضادات حيوية",
    dosageForm: "حقن",
    strength: "1000 mg",
    packageSize: "1 حقنة",
    price: 2200,
    stock: 50,
    requiresPrescription: true,
  },

  // ============================================================
  // 3️⃣ أدوية ضغط الدم والقلب (50 دواء)
  // ============================================================
  {
    id: "med_101",
    name: "لوسارتان 50 مجم",
    genericName: "Losartan",
    activeIngredient: "Losartan 50 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "50 mg",
    packageSize: "28 قرص",
    price: 1200,
    stock: 100,
    requiresPrescription: true,
  },
  {
    id: "med_102",
    name: "لوسارتان 100 مجم",
    genericName: "Losartan",
    activeIngredient: "Losartan 100 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "100 mg",
    packageSize: "28 قرص",
    price: 1600,
    stock: 100,
    requiresPrescription: true,
  },
  {
    id: "med_103",
    name: "فالسارتان 80 مجم",
    genericName: "Valsartan",
    activeIngredient: "Valsartan 80 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "80 mg",
    packageSize: "28 قرص",
    price: 1400,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_104",
    name: "فالسارتان 160 مجم",
    genericName: "Valsartan",
    activeIngredient: "Valsartan 160 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "160 mg",
    packageSize: "28 قرص",
    price: 1800,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_105",
    name: "إربيسارتان 150 مجم",
    genericName: "Irbesartan",
    activeIngredient: "Irbesartan 150 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "150 mg",
    packageSize: "28 قرص",
    price: 1500,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_106",
    name: "إربيسارتان 300 مجم",
    genericName: "Irbesartan",
    activeIngredient: "Irbesartan 300 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "300 mg",
    packageSize: "28 قرص",
    price: 1900,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_107",
    name: "كانديسارتان 8 مجم",
    genericName: "Candesartan",
    activeIngredient: "Candesartan 8 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "8 mg",
    packageSize: "28 قرص",
    price: 1100,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_108",
    name: "كانديسارتان 16 مجم",
    genericName: "Candesartan",
    activeIngredient: "Candesartan 16 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "16 mg",
    packageSize: "28 قرص",
    price: 1400,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_109",
    name: "تلميسارتان 40 مجم",
    genericName: "Telmisartan",
    activeIngredient: "Telmisartan 40 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "40 mg",
    packageSize: "28 قرص",
    price: 1300,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_110",
    name: "تلميسارتان 80 مجم",
    genericName: "Telmisartan",
    activeIngredient: "Telmisartan 80 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "80 mg",
    packageSize: "28 قرص",
    price: 1700,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_111",
    name: "أملوديبين 5 مجم",
    genericName: "Amlodipine",
    activeIngredient: "Amlodipine 5 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "5 mg",
    packageSize: "30 قرص",
    price: 1000,
    stock: 100,
    requiresPrescription: true,
  },
  {
    id: "med_112",
    name: "أملوديبين 10 مجم",
    genericName: "Amlodipine",
    activeIngredient: "Amlodipine 10 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "10 mg",
    packageSize: "30 قرص",
    price: 1300,
    stock: 100,
    requiresPrescription: true,
  },
  {
    id: "med_113",
    name: "نيفيديبين 10 مجم",
    genericName: "Nifedipine",
    activeIngredient: "Nifedipine 10 mg",
    category: "أدوية الضغط",
    dosageForm: "كبسولات",
    strength: "10 mg",
    packageSize: "30 كبسولة",
    price: 900,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_114",
    name: "نيفيديبين 20 مجم",
    genericName: "Nifedipine",
    activeIngredient: "Nifedipine 20 mg",
    category: "أدوية الضغط",
    dosageForm: "كبسولات",
    strength: "20 mg",
    packageSize: "30 كبسولة",
    price: 1200,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_115",
    name: "فيلوديبين 5 مجم",
    genericName: "Felodipine",
    activeIngredient: "Felodipine 5 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "5 mg",
    packageSize: "30 قرص",
    price: 1100,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_116",
    name: "ليسينوبريل 5 مجم",
    genericName: "Lisinopril",
    activeIngredient: "Lisinopril 5 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "5 mg",
    packageSize: "28 قرص",
    price: 1000,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_117",
    name: "ليسينوبريل 10 مجم",
    genericName: "Lisinopril",
    activeIngredient: "Lisinopril 10 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "10 mg",
    packageSize: "28 قرص",
    price: 1300,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_118",
    name: "ليسينوبريل 20 مجم",
    genericName: "Lisinopril",
    activeIngredient: "Lisinopril 20 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "20 mg",
    packageSize: "28 قرص",
    price: 1600,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_119",
    name: "إنالابريل 5 مجم",
    genericName: "Enalapril",
    activeIngredient: "Enalapril 5 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "5 mg",
    packageSize: "28 قرص",
    price: 900,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_120",
    name: "إنالابريل 10 مجم",
    genericName: "Enalapril",
    activeIngredient: "Enalapril 10 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "10 mg",
    packageSize: "28 قرص",
    price: 1200,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_121",
    name: "راميبريل 2.5 مجم",
    genericName: "Ramipril",
    activeIngredient: "Ramipril 2.5 mg",
    category: "أدوية الضغط",
    dosageForm: "كبسولات",
    strength: "2.5 mg",
    packageSize: "28 كبسولة",
    price: 1100,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_122",
    name: "راميبريل 5 مجم",
    genericName: "Ramipril",
    activeIngredient: "Ramipril 5 mg",
    category: "أدوية الضغط",
    dosageForm: "كبسولات",
    strength: "5 mg",
    packageSize: "28 كبسولة",
    price: 1400,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_123",
    name: "بيريندوبريل 4 مجم",
    genericName: "Perindopril",
    activeIngredient: "Perindopril 4 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "4 mg",
    packageSize: "30 قرص",
    price: 1300,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_124",
    name: "بيريندوبريل 8 مجم",
    genericName: "Perindopril",
    activeIngredient: "Perindopril 8 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "8 mg",
    packageSize: "30 قرص",
    price: 1600,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_125",
    name: "أتينولول 25 مجم",
    genericName: "Atenolol",
    activeIngredient: "Atenolol 25 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "25 mg",
    packageSize: "30 قرص",
    price: 800,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_126",
    name: "أتينولول 50 مجم",
    genericName: "Atenolol",
    activeIngredient: "Atenolol 50 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "50 mg",
    packageSize: "30 قرص",
    price: 1000,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_127",
    name: "أتينولول 100 مجم",
    genericName: "Atenolol",
    activeIngredient: "Atenolol 100 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "100 mg",
    packageSize: "30 قرص",
    price: 1300,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_128",
    name: "ميتوبرولول 50 مجم",
    genericName: "Metoprolol",
    activeIngredient: "Metoprolol 50 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "50 mg",
    packageSize: "30 قرص",
    price: 900,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_129",
    name: "ميتوبرولول 100 مجم",
    genericName: "Metoprolol",
    activeIngredient: "Metoprolol 100 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "100 mg",
    packageSize: "30 قرص",
    price: 1200,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_130",
    name: "بيزوبرولول 2.5 مجم",
    genericName: "Bisoprolol",
    activeIngredient: "Bisoprolol 2.5 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "2.5 mg",
    packageSize: "30 قرص",
    price: 1000,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_131",
    name: "بيزوبرولول 5 مجم",
    genericName: "Bisoprolol",
    activeIngredient: "Bisoprolol 5 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "5 mg",
    packageSize: "30 قرص",
    price: 1300,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_132",
    name: "كارفيديلول 6.25 مجم",
    genericName: "Carvedilol",
    activeIngredient: "Carvedilol 6.25 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "6.25 mg",
    packageSize: "30 قرص",
    price: 1100,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_133",
    name: "كارفيديلول 12.5 مجم",
    genericName: "Carvedilol",
    activeIngredient: "Carvedilol 12.5 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "12.5 mg",
    packageSize: "30 قرص",
    price: 1400,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_134",
    name: "كارفيديلول 25 مجم",
    genericName: "Carvedilol",
    activeIngredient: "Carvedilol 25 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "25 mg",
    packageSize: "30 قرص",
    price: 1700,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_135",
    name: "هيدروكلوروثيازيد 12.5 مجم",
    genericName: "Hydrochlorothiazide",
    activeIngredient: "Hydrochlorothiazide 12.5 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "12.5 mg",
    packageSize: "30 قرص",
    price: 600,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_136",
    name: "هيدروكلوروثيازيد 25 مجم",
    genericName: "Hydrochlorothiazide",
    activeIngredient: "Hydrochlorothiazide 25 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "25 mg",
    packageSize: "30 قرص",
    price: 800,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_137",
    name: "فوروسيميد 20 مجم",
    genericName: "Furosemide",
    activeIngredient: "Furosemide 20 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "20 mg",
    packageSize: "30 قرص",
    price: 700,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_138",
    name: "فوروسيميد 40 مجم",
    genericName: "Furosemide",
    activeIngredient: "Furosemide 40 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "40 mg",
    packageSize: "30 قرص",
    price: 900,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_139",
    name: "سبيرونولاكتون 25 مجم",
    genericName: "Spironolactone",
    activeIngredient: "Spironolactone 25 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "25 mg",
    packageSize: "30 قرص",
    price: 1000,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_140",
    name: "سبيرونولاكتون 50 مجم",
    genericName: "Spironolactone",
    activeIngredient: "Spironolactone 50 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "50 mg",
    packageSize: "30 قرص",
    price: 1300,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_141",
    name: "سبيرونولاكتون 100 مجم",
    genericName: "Spironolactone",
    activeIngredient: "Spironolactone 100 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "100 mg",
    packageSize: "30 قرص",
    price: 1600,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_142",
    name: "كلورتاليدون 25 مجم",
    genericName: "Chlortalidone",
    activeIngredient: "Chlortalidone 25 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "25 mg",
    packageSize: "30 قرص",
    price: 700,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_143",
    name: "كلورتاليدون 50 مجم",
    genericName: "Chlortalidone",
    activeIngredient: "Chlortalidone 50 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "50 mg",
    packageSize: "30 قرص",
    price: 900,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_144",
    name: "دوكسازوسين 1 مجم",
    genericName: "Doxazosin",
    activeIngredient: "Doxazosin 1 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "1 mg",
    packageSize: "30 قرص",
    price: 1000,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_145",
    name: "دوكسازوسين 2 مجم",
    genericName: "Doxazosin",
    activeIngredient: "Doxazosin 2 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "2 mg",
    packageSize: "30 قرص",
    price: 1300,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_146",
    name: "دوكسازوسين 4 مجم",
    genericName: "Doxazosin",
    activeIngredient: "Doxazosin 4 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "4 mg",
    packageSize: "30 قرص",
    price: 1600,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_147",
    name: "برازوسين 1 مجم",
    genericName: "Prazosin",
    activeIngredient: "Prazosin 1 mg",
    category: "أدوية الضغط",
    dosageForm: "كبسولات",
    strength: "1 mg",
    packageSize: "30 كبسولة",
    price: 900,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_148",
    name: "برازوسين 2 مجم",
    genericName: "Prazosin",
    activeIngredient: "Prazosin 2 mg",
    category: "أدوية الضغط",
    dosageForm: "كبسولات",
    strength: "2 mg",
    packageSize: "30 كبسولة",
    price: 1200,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_149",
    name: "كلونيدين 0.1 مجم",
    genericName: "Clonidine",
    activeIngredient: "Clonidine 0.1 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "0.1 mg",
    packageSize: "30 قرص",
    price: 800,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_150",
    name: "كلونيدين 0.2 مجم",
    genericName: "Clonidine",
    activeIngredient: "Clonidine 0.2 mg",
    category: "أدوية الضغط",
    dosageForm: "أقراص",
    strength: "0.2 mg",
    packageSize: "30 قرص",
    price: 1000,
    stock: 70,
    requiresPrescription: true,
  },

  // ============================================================
  // 4️⃣ أدوية السكري (50 دواء)
  // ============================================================
  {
    id: "med_151",
    name: "ميتفورمين 500 مجم",
    genericName: "Metformin",
    activeIngredient: "Metformin 500 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "500 mg",
    packageSize: "30 قرص",
    price: 800,
    stock: 100,
    requiresPrescription: true,
  },
  {
    id: "med_152",
    name: "ميتفورمين 850 مجم",
    genericName: "Metformin",
    activeIngredient: "Metformin 850 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "850 mg",
    packageSize: "30 قرص",
    price: 1000,
    stock: 100,
    requiresPrescription: true,
  },
  {
    id: "med_153",
    name: "ميتفورمين 1000 مجم",
    genericName: "Metformin",
    activeIngredient: "Metformin 1000 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "1000 mg",
    packageSize: "30 قرص",
    price: 1200,
    stock: 100,
    requiresPrescription: true,
  },
  {
    id: "med_154",
    name: "ميتفورمين 500 مجم ممتد المفعول",
    genericName: "Metformin SR",
    activeIngredient: "Metformin 500 mg SR",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "500 mg",
    packageSize: "30 قرص",
    price: 900,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_155",
    name: "ميتفورمين 750 مجم ممتد المفعول",
    genericName: "Metformin SR",
    activeIngredient: "Metformin 750 mg SR",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "750 mg",
    packageSize: "30 قرص",
    price: 1100,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_156",
    name: "جليبنكلاميد 5 مجم",
    genericName: "Glibenclamide",
    activeIngredient: "Glibenclamide 5 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "5 mg",
    packageSize: "30 قرص",
    price: 600,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_157",
    name: "جليبنكلاميد 10 مجم",
    genericName: "Glibenclamide",
    activeIngredient: "Glibenclamide 10 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "10 mg",
    packageSize: "30 قرص",
    price: 800,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_158",
    name: "جليكلازيد 30 مجم",
    genericName: "Gliclazide",
    activeIngredient: "Gliclazide 30 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "30 mg",
    packageSize: "30 قرص",
    price: 700,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_159",
    name: "جليكلازيد 60 مجم",
    genericName: "Gliclazide",
    activeIngredient: "Gliclazide 60 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "60 mg",
    packageSize: "30 قرص",
    price: 900,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_160",
    name: "جليكلازيد 80 مجم",
    genericName: "Gliclazide",
    activeIngredient: "Gliclazide 80 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "80 mg",
    packageSize: "30 قرص",
    price: 1000,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_161",
    name: "جليبيزيد 5 مجم",
    genericName: "Glipizide",
    activeIngredient: "Glipizide 5 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "5 mg",
    packageSize: "30 قرص",
    price: 650,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_162",
    name: "جليبيزيد 10 مجم",
    genericName: "Glipizide",
    activeIngredient: "Glipizide 10 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "10 mg",
    packageSize: "30 قرص",
    price: 850,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_163",
    name: "بيوجليتازون 15 مجم",
    genericName: "Pioglitazone",
    activeIngredient: "Pioglitazone 15 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "15 mg",
    packageSize: "30 قرص",
    price: 1400,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_164",
    name: "بيوجليتازون 30 مجم",
    genericName: "Pioglitazone",
    activeIngredient: "Pioglitazone 30 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "30 mg",
    packageSize: "30 قرص",
    price: 1800,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_165",
    name: "بيوجليتازون 45 مجم",
    genericName: "Pioglitazone",
    activeIngredient: "Pioglitazone 45 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "45 mg",
    packageSize: "30 قرص",
    price: 2200,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_166",
    name: "روسجليتازون 2 مجم",
    genericName: "Rosiglitazone",
    activeIngredient: "Rosiglitazone 2 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "2 mg",
    packageSize: "30 قرص",
    price: 1300,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_167",
    name: "روسجليتازون 4 مجم",
    genericName: "Rosiglitazone",
    activeIngredient: "Rosiglitazone 4 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "4 mg",
    packageSize: "30 قرص",
    price: 1600,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_168",
    name: "أكاربوز 50 مجم",
    genericName: "Acarbose",
    activeIngredient: "Acarbose 50 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "50 mg",
    packageSize: "30 قرص",
    price: 1000,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_169",
    name: "أكاربوز 100 مجم",
    genericName: "Acarbose",
    activeIngredient: "Acarbose 100 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "100 mg",
    packageSize: "30 قرص",
    price: 1300,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_170",
    name: "سيتاغليبتين 50 مجم",
    genericName: "Sitagliptin",
    activeIngredient: "Sitagliptin 50 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "50 mg",
    packageSize: "28 قرص",
    price: 2200,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_171",
    name: "سيتاغليبتين 100 مجم",
    genericName: "Sitagliptin",
    activeIngredient: "Sitagliptin 100 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "100 mg",
    packageSize: "28 قرص",
    price: 2800,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_172",
    name: "ساكساغليبتين 2.5 مجم",
    genericName: "Saxagliptin",
    activeIngredient: "Saxagliptin 2.5 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "2.5 mg",
    packageSize: "28 قرص",
    price: 2000,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_173",
    name: "ساكساغليبتين 5 مجم",
    genericName: "Saxagliptin",
    activeIngredient: "Saxagliptin 5 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "5 mg",
    packageSize: "28 قرص",
    price: 2500,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_174",
    name: "ليناغليبتين 5 مجم",
    genericName: "Linagliptin",
    activeIngredient: "Linagliptin 5 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "5 mg",
    packageSize: "28 قرص",
    price: 2400,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_175",
    name: "إمباغليفلوزين 10 مجم",
    genericName: "Empagliflozin",
    activeIngredient: "Empagliflozin 10 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "10 mg",
    packageSize: "28 قرص",
    price: 2600,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_176",
    name: "إمباغليفلوزين 25 مجم",
    genericName: "Empagliflozin",
    activeIngredient: "Empagliflozin 25 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "25 mg",
    packageSize: "28 قرص",
    price: 3200,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_177",
    name: "كاناغليفلوزين 100 مجم",
    genericName: "Canagliflozin",
    activeIngredient: "Canagliflozin 100 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "100 mg",
    packageSize: "28 قرص",
    price: 2400,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_178",
    name: "كاناغليفلوزين 300 مجم",
    genericName: "Canagliflozin",
    activeIngredient: "Canagliflozin 300 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "300 mg",
    packageSize: "28 قرص",
    price: 3000,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_179",
    name: "داباغليفلوزين 5 مجم",
    genericName: "Dapagliflozin",
    activeIngredient: "Dapagliflozin 5 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "5 mg",
    packageSize: "28 قرص",
    price: 2300,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_180",
    name: "داباغليفلوزين 10 مجم",
    genericName: "Dapagliflozin",
    activeIngredient: "Dapagliflozin 10 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "10 mg",
    packageSize: "28 قرص",
    price: 2900,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_181",
    name: "إكسيناتيد 5 ميكروجرام",
    genericName: "Exenatide",
    activeIngredient: "Exenatide 5 mcg",
    category: "أدوية السكري",
    dosageForm: "حقن",
    strength: "5 mcg",
    packageSize: "1 حقنة",
    price: 3500,
    stock: 40,
    requiresPrescription: true,
  },
  {
    id: "med_182",
    name: "إكسيناتيد 10 ميكروجرام",
    genericName: "Exenatide",
    activeIngredient: "Exenatide 10 mcg",
    category: "أدوية السكري",
    dosageForm: "حقن",
    strength: "10 mcg",
    packageSize: "1 حقنة",
    price: 4000,
    stock: 40,
    requiresPrescription: true,
  },
  {
    id: "med_183",
    name: "ليراجلوتيد 6 مجم",
    genericName: "Liraglutide",
    activeIngredient: "Liraglutide 6 mg",
    category: "أدوية السكري",
    dosageForm: "حقن",
    strength: "6 mg",
    packageSize: "1 حقنة",
    price: 4500,
    stock: 40,
    requiresPrescription: true,
  },
  {
    id: "med_184",
    name: "سماجلوتيد 0.5 مجم",
    genericName: "Semaglutide",
    activeIngredient: "Semaglutide 0.5 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "0.5 mg",
    packageSize: "28 قرص",
    price: 4000,
    stock: 40,
    requiresPrescription: true,
  },
  {
    id: "med_185",
    name: "سماجلوتيد 1 مجم",
    genericName: "Semaglutide",
    activeIngredient: "Semaglutide 1 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "1 mg",
    packageSize: "28 قرص",
    price: 4800,
    stock: 40,
    requiresPrescription: true,
  },
  {
    id: "med_186",
    name: "إنولين 70/30",
    genericName: "Insulin 70/30",
    activeIngredient: "Insulin 70/30",
    category: "أدوية السكري",
    dosageForm: "حقن",
    strength: "100 IU/ml",
    packageSize: "1 قلم",
    price: 5000,
    stock: 50,
    requiresPrescription: true,
  },
  {
    id: "med_187",
    name: "إنولين سريع المفعول",
    genericName: "Insulin Rapid",
    activeIngredient: "Insulin Rapid",
    category: "أدوية السكري",
    dosageForm: "حقن",
    strength: "100 IU/ml",
    packageSize: "1 قلم",
    price: 4800,
    stock: 50,
    requiresPrescription: true,
  },
  {
    id: "med_188",
    name: "إنولين طويل المفعول",
    genericName: "Insulin Long Acting",
    activeIngredient: "Insulin Long Acting",
    category: "أدوية السكري",
    dosageForm: "حقن",
    strength: "100 IU/ml",
    packageSize: "1 قلم",
    price: 5500,
    stock: 50,
    requiresPrescription: true,
  },
  {
    id: "med_189",
    name: "إنولين أسبارت",
    genericName: "Insulin Aspart",
    activeIngredient: "Insulin Aspart",
    category: "أدوية السكري",
    dosageForm: "حقن",
    strength: "100 IU/ml",
    packageSize: "1 قلم",
    price: 5200,
    stock: 50,
    requiresPrescription: true,
  },
  {
    id: "med_190",
    name: "إنولين ديتيمير",
    genericName: "Insulin Detemir",
    activeIngredient: "Insulin Detemir",
    category: "أدوية السكري",
    dosageForm: "حقن",
    strength: "100 IU/ml",
    packageSize: "1 قلم",
    price: 5800,
    stock: 50,
    requiresPrescription: true,
  },
  {
    id: "med_191",
    name: "إنولين جلارجين",
    genericName: "Insulin Glargine",
    activeIngredient: "Insulin Glargine",
    category: "أدوية السكري",
    dosageForm: "حقن",
    strength: "100 IU/ml",
    packageSize: "1 قلم",
    price: 6000,
    stock: 50,
    requiresPrescription: true,
  },
  {
    id: "med_192",
    name: "إنولين لزمير",
    genericName: "Insulin Lispro",
    activeIngredient: "Insulin Lispro",
    category: "أدوية السكري",
    dosageForm: "حقن",
    strength: "100 IU/ml",
    packageSize: "1 قلم",
    price: 5400,
    stock: 50,
    requiresPrescription: true,
  },
  {
    id: "med_193",
    name: "إنولين منتظم",
    genericName: "Insulin Regular",
    activeIngredient: "Insulin Regular",
    category: "أدوية السكري",
    dosageForm: "حقن",
    strength: "100 IU/ml",
    packageSize: "1 قلم",
    price: 4500,
    stock: 50,
    requiresPrescription: true,
  },
  {
    id: "med_194",
    name: "ميتفورمين + جليبنكلاميد",
    genericName: "Metformin + Glibenclamide",
    activeIngredient: "Metformin 500 mg + Glibenclamide 5 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "500/5 mg",
    packageSize: "30 قرص",
    price: 1100,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_195",
    name: "ميتفورمين + جليكلازيد",
    genericName: "Metformin + Gliclazide",
    activeIngredient: "Metformin 500 mg + Gliclazide 30 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "500/30 mg",
    packageSize: "30 قرص",
    price: 1200,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_196",
    name: "ميتفورمين + سيتاغليبتين",
    genericName: "Metformin + Sitagliptin",
    activeIngredient: "Metformin 500 mg + Sitagliptin 50 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "500/50 mg",
    packageSize: "28 قرص",
    price: 2600,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_197",
    name: "ميتفورمين + إمباغليفلوزين",
    genericName: "Metformin + Empagliflozin",
    activeIngredient: "Metformin 500 mg + Empagliflozin 10 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "500/10 mg",
    packageSize: "28 قرص",
    price: 3000,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_198",
    name: "جليبنكلاميد + ميتفورمين",
    genericName: "Glibenclamide + Metformin",
    activeIngredient: "Glibenclamide 5 mg + Metformin 500 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "5/500 mg",
    packageSize: "30 قرص",
    price: 1000,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_199",
    name: "جليكلازيد + ميتفورمين",
    genericName: "Gliclazide + Metformin",
    activeIngredient: "Gliclazide 30 mg + Metformin 500 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "30/500 mg",
    packageSize: "30 قرص",
    price: 1100,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_200",
    name: "بيوجليتازون + ميتفورمين",
    genericName: "Pioglitazone + Metformin",
    activeIngredient: "Pioglitazone 15 mg + Metformin 500 mg",
    category: "أدوية السكري",
    dosageForm: "أقراص",
    strength: "15/500 mg",
    packageSize: "30 قرص",
    price: 1600,
    stock: 70,
    requiresPrescription: true,
  },

  // ============================================================
  // 5️⃣ أدوية الجهاز الهضمي (50 دواء)
  // ============================================================
  {
    id: "med_201",
    name: "أوميبرازول 20 مجم",
    genericName: "Omeprazole",
    activeIngredient: "Omeprazole 20 mg",
    category: "الجهاز الهضمي",
    dosageForm: "كبسولات",
    strength: "20 mg",
    packageSize: "14 كبسولة",
    price: 1200,
    stock: 100,
    requiresPrescription: false,
  },
  {
    id: "med_202",
    name: "أوميبرازول 40 مجم",
    genericName: "Omeprazole",
    activeIngredient: "Omeprazole 40 mg",
    category: "الجهاز الهضمي",
    dosageForm: "كبسولات",
    strength: "40 mg",
    packageSize: "14 كبسولة",
    price: 1600,
    stock: 100,
    requiresPrescription: false,
  },
  {
    id: "med_203",
    name: "بانتوبرازول 20 مجم",
    genericName: "Pantoprazole",
    activeIngredient: "Pantoprazole 20 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "20 mg",
    packageSize: "14 قرص",
    price: 1400,
    stock: 90,
    requiresPrescription: false,
  },
  {
    id: "med_204",
    name: "بانتوبرازول 40 مجم",
    genericName: "Pantoprazole",
    activeIngredient: "Pantoprazole 40 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "40 mg",
    packageSize: "14 قرص",
    price: 1800,
    stock: 90,
    requiresPrescription: false,
  },
  {
    id: "med_205",
    name: "إيزوميبرازول 20 مجم",
    genericName: "Esomeprazole",
    activeIngredient: "Esomeprazole 20 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "20 mg",
    packageSize: "14 قرص",
    price: 1600,
    stock: 90,
    requiresPrescription: false,
  },
  {
    id: "med_206",
    name: "إيزوميبرازول 40 مجم",
    genericName: "Esomeprazole",
    activeIngredient: "Esomeprazole 40 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "40 mg",
    packageSize: "14 قرص",
    price: 2000,
    stock: 90,
    requiresPrescription: false,
  },
  {
    id: "med_207",
    name: "فاموتيدين 20 مجم",
    genericName: "Famotidine",
    activeIngredient: "Famotidine 20 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "20 mg",
    packageSize: "30 قرص",
    price: 800,
    stock: 90,
    requiresPrescription: false,
  },
  {
    id: "med_208",
    name: "فاموتيدين 40 مجم",
    genericName: "Famotidine",
    activeIngredient: "Famotidine 40 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "40 mg",
    packageSize: "30 قرص",
    price: 1100,
    stock: 90,
    requiresPrescription: false,
  },
  {
    id: "med_209",
    name: "رانيتيدين 150 مجم",
    genericName: "Ranitidine",
    activeIngredient: "Ranitidine 150 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "150 mg",
    packageSize: "30 قرص",
    price: 900,
    stock: 90,
    requiresPrescription: false,
  },
  {
    id: "med_210",
    name: "رانيتيدين 300 مجم",
    genericName: "Ranitidine",
    activeIngredient: "Ranitidine 300 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "300 mg",
    packageSize: "30 قرص",
    price: 1200,
    stock: 90,
    requiresPrescription: false,
  },
  {
    id: "med_211",
    name: "سيميتيدين 200 مجم",
    genericName: "Cimetidine",
    activeIngredient: "Cimetidine 200 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "200 mg",
    packageSize: "30 قرص",
    price: 700,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_212",
    name: "سيميتيدين 400 مجم",
    genericName: "Cimetidine",
    activeIngredient: "Cimetidine 400 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "400 mg",
    packageSize: "30 قرص",
    price: 1000,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_213",
    name: "دومبيريدون 10 مجم",
    genericName: "Domperidone",
    activeIngredient: "Domperidone 10 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "10 mg",
    packageSize: "30 قرص",
    price: 900,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_214",
    name: "دومبيريدون 20 مجم",
    genericName: "Domperidone",
    activeIngredient: "Domperidone 20 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "20 mg",
    packageSize: "30 قرص",
    price: 1200,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_215",
    name: "ميتوكلوبراميد 10 مجم",
    genericName: "Metoclopramide",
    activeIngredient: "Metoclopramide 10 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "10 mg",
    packageSize: "30 قرص",
    price: 800,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_216",
    name: "ميتوكلوبراميد شراب",
    genericName: "Metoclopramide",
    activeIngredient: "Metoclopramide 1 mg/ml",
    category: "الجهاز الهضمي",
    dosageForm: "شراب",
    strength: "1 mg/ml",
    packageSize: "100 ml",
    price: 700,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_217",
    name: "أوندانسيترون 4 مجم",
    genericName: "Ondansetron",
    activeIngredient: "Ondansetron 4 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "4 mg",
    packageSize: "10 قرص",
    price: 1500,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_218",
    name: "أوندانسيترون 8 مجم",
    genericName: "Ondansetron",
    activeIngredient: "Ondansetron 8 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "8 mg",
    packageSize: "10 قرص",
    price: 2000,
    stock: 70,
    requiresPrescription: true,
  },
  {
    id: "med_219",
    name: "أوندانسيترون شراب",
    genericName: "Ondansetron",
    activeIngredient: "Ondansetron 2 mg/5ml",
    category: "الجهاز الهضمي",
    dosageForm: "شراب",
    strength: "2 mg/5 ml",
    packageSize: "50 ml",
    price: 1800,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_220",
    name: "لوبيراميد 2 مجم",
    genericName: "Loperamide",
    activeIngredient: "Loperamide 2 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "2 mg",
    packageSize: "12 قرص",
    price: 600,
    stock: 90,
    requiresPrescription: false,
  },
  {
    id: "med_221",
    name: "لوبيراميد شراب",
    genericName: "Loperamide",
    activeIngredient: "Loperamide 1 mg/5ml",
    category: "الجهاز الهضمي",
    dosageForm: "شراب",
    strength: "1 mg/5 ml",
    packageSize: "100 ml",
    price: 700,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_222",
    name: "بزموت سبساليسيلات",
    genericName: "Bismuth Subsalicylate",
    activeIngredient: "Bismuth Subsalicylate",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "262 mg",
    packageSize: "30 قرص",
    price: 1000,
    stock: 70,
    requiresPrescription: false,
  },
  {
    id: "med_223",
    name: "سيميثيكون 80 مجم",
    genericName: "Simethicone",
    activeIngredient: "Simethicone 80 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "80 mg",
    packageSize: "30 قرص",
    price: 700,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_224",
    name: "سيميثيكون 125 مجم",
    genericName: "Simethicone",
    activeIngredient: "Simethicone 125 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "125 mg",
    packageSize: "30 قرص",
    price: 900,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_225",
    name: "هيوسين بوتيل بروميد 10 مجم",
    genericName: "Hyoscine Butylbromide",
    activeIngredient: "Hyoscine Butylbromide 10 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "10 mg",
    packageSize: "20 قرص",
    price: 1000,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_226",
    name: "ميبيفيرين 135 مجم",
    genericName: "Mebeverine",
    activeIngredient: "Mebeverine 135 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "135 mg",
    packageSize: "30 قرص",
    price: 1200,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_227",
    name: "ميبيفيرين 200 مجم",
    genericName: "Mebeverine",
    activeIngredient: "Mebeverine 200 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "200 mg",
    packageSize: "30 قرص",
    price: 1600,
    stock: 80,
    requiresPrescription: true,
  },
  {
    id: "med_228",
    name: "بيثيدين 50 مجم",
    genericName: "Pethidine",
    activeIngredient: "Pethidine 50 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "50 mg",
    packageSize: "20 قرص",
    price: 1400,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_229",
    name: "بيثيدين 100 مجم",
    genericName: "Pethidine",
    activeIngredient: "Pethidine 100 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "100 mg",
    packageSize: "20 قرص",
    price: 1800,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_230",
    name: "ترامادول 50 مجم",
    genericName: "Tramadol",
    activeIngredient: "Tramadol 50 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "50 mg",
    packageSize: "20 قرص",
    price: 1600,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_231",
    name: "ترامادول 100 مجم",
    genericName: "Tramadol",
    activeIngredient: "Tramadol 100 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "100 mg",
    packageSize: "20 قرص",
    price: 2200,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_232",
    name: "كودايين 30 مجم",
    genericName: "Codeine",
    activeIngredient: "Codeine 30 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "30 mg",
    packageSize: "20 قرص",
    price: 1800,
    stock: 50,
    requiresPrescription: true,
  },
  {
    id: "med_233",
    name: "كودايين 60 مجم",
    genericName: "Codeine",
    activeIngredient: "Codeine 60 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "60 mg",
    packageSize: "20 قرص",
    price: 2400,
    stock: 50,
    requiresPrescription: true,
  },
  {
    id: "med_234",
    name: "مورفين 10 مجم",
    genericName: "Morphine",
    activeIngredient: "Morphine 10 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "10 mg",
    packageSize: "20 قرص",
    price: 2800,
    stock: 40,
    requiresPrescription: true,
  },
  {
    id: "med_235",
    name: "مورفين 30 مجم",
    genericName: "Morphine",
    activeIngredient: "Morphine 30 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "30 mg",
    packageSize: "20 قرص",
    price: 3400,
    stock: 40,
    requiresPrescription: true,
  },
  {
    id: "med_236",
    name: "فنتانيل 25 ميكروجرام",
    genericName: "Fentanyl",
    activeIngredient: "Fentanyl 25 mcg",
    category: "الجهاز الهضمي",
    dosageForm: "لاصقات",
    strength: "25 mcg",
    packageSize: "5 لاصقات",
    price: 3500,
    stock: 30,
    requiresPrescription: true,
  },
  {
    id: "med_237",
    name: "فنتانيل 50 ميكروجرام",
    genericName: "Fentanyl",
    activeIngredient: "Fentanyl 50 mcg",
    category: "الجهاز الهضمي",
    dosageForm: "لاصقات",
    strength: "50 mcg",
    packageSize: "5 لاصقات",
    price: 4200,
    stock: 30,
    requiresPrescription: true,
  },
  {
    id: "med_238",
    name: "فنتانيل 75 ميكروجرام",
    genericName: "Fentanyl",
    activeIngredient: "Fentanyl 75 mcg",
    category: "الجهاز الهضمي",
    dosageForm: "لاصقات",
    strength: "75 mcg",
    packageSize: "5 لاصقات",
    price: 4800,
    stock: 30,
    requiresPrescription: true,
  },
  {
    id: "med_239",
    name: "فنتانيل 100 ميكروجرام",
    genericName: "Fentanyl",
    activeIngredient: "Fentanyl 100 mcg",
    category: "الجهاز الهضمي",
    dosageForm: "لاصقات",
    strength: "100 mcg",
    packageSize: "5 لاصقات",
    price: 5500,
    stock: 30,
    requiresPrescription: true,
  },
  {
    id: "med_240",
    name: "أوكسيكودون 10 مجم",
    genericName: "Oxycodone",
    activeIngredient: "Oxycodone 10 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "10 mg",
    packageSize: "20 قرص",
    price: 2600,
    stock: 30,
    requiresPrescription: true,
  },
  {
    id: "med_241",
    name: "أوكسيكودون 20 مجم",
    genericName: "Oxycodone",
    activeIngredient: "Oxycodone 20 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "20 mg",
    packageSize: "20 قرص",
    price: 3200,
    stock: 30,
    requiresPrescription: true,
  },
  {
    id: "med_242",
    name: "هيدروكودون 10 مجم",
    genericName: "Hydrocodone",
    activeIngredient: "Hydrocodone 10 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "10 mg",
    packageSize: "20 قرص",
    price: 2400,
    stock: 30,
    requiresPrescription: true,
  },
  {
    id: "med_243",
    name: "هيدروكودون 20 مجم",
    genericName: "Hydrocodone",
    activeIngredient: "Hydrocodone 20 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "20 mg",
    packageSize: "20 قرص",
    price: 3000,
    stock: 30,
    requiresPrescription: true,
  },
  {
    id: "med_244",
    name: "بنتازوسين 25 مجم",
    genericName: "Pentazocine",
    activeIngredient: "Pentazocine 25 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "25 mg",
    packageSize: "20 قرص",
    price: 1800,
    stock: 30,
    requiresPrescription: true,
  },
  {
    id: "med_245",
    name: "بنتازوسين 50 مجم",
    genericName: "Pentazocine",
    activeIngredient: "Pentazocine 50 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "50 mg",
    packageSize: "20 قرص",
    price: 2200,
    stock: 30,
    requiresPrescription: true,
  },
  {
    id: "med_246",
    name: "ميبريستون 200 مجم",
    genericName: "Mebeverine",
    activeIngredient: "Mebeverine 200 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "200 mg",
    packageSize: "20 قرص",
    price: 1600,
    stock: 40,
    requiresPrescription: true,
  },
  {
    id: "med_247",
    name: "كلونيدين 0.1 مجم",
    genericName: "Clonidine",
    activeIngredient: "Clonidine 0.1 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "0.1 mg",
    packageSize: "20 قرص",
    price: 800,
    stock: 40,
    requiresPrescription: true,
  },
  {
    id: "med_248",
    name: "كلونيدين 0.2 مجم",
    genericName: "Clonidine",
    activeIngredient: "Clonidine 0.2 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "0.2 mg",
    packageSize: "20 قرص",
    price: 1000,
    stock: 40,
    requiresPrescription: true,
  },
  {
    id: "med_249",
    name: "ميثيلدوبا 250 مجم",
    genericName: "Methyldopa",
    activeIngredient: "Methyldopa 250 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "250 mg",
    packageSize: "20 قرص",
    price: 900,
    stock: 40,
    requiresPrescription: true,
  },
  {
    id: "med_250",
    name: "ميثيلدوبا 500 مجم",
    genericName: "Methyldopa",
    activeIngredient: "Methyldopa 500 mg",
    category: "الجهاز الهضمي",
    dosageForm: "أقراص",
    strength: "500 mg",
    packageSize: "20 قرص",
    price: 1200,
    stock: 40,
    requiresPrescription: true,
  },

  // ============================================================
  // 6️⃣ فيتامينات ومكملات (50 دواء)
  // ============================================================
  {
    id: "med_251",
    name: "فيتامين سي 500 مجم",
    genericName: "Vitamin C",
    activeIngredient: "Ascorbic Acid 500 mg",
    category: "فيتامينات",
    dosageForm: "أقراص",
    strength: "500 mg",
    packageSize: "30 قرص",
    price: 1000,
    stock: 100,
    requiresPrescription: false,
  },
  {
    id: "med_252",
    name: "فيتامين سي 1000 مجم",
    genericName: "Vitamin C",
    activeIngredient: "Ascorbic Acid 1000 mg",
    category: "فيتامينات",
    dosageForm: "أقراص فوارة",
    strength: "1000 mg",
    packageSize: "20 قرص",
    price: 1500,
    stock: 100,
    requiresPrescription: false,
  },
  {
    id: "med_253",
    name: "فيتامين سي شراب للأطفال",
    genericName: "Vitamin C",
    activeIngredient: "Ascorbic Acid 50 mg/5ml",
    category: "فيتامينات",
    dosageForm: "شراب",
    strength: "50 mg/5 ml",
    packageSize: "100 ml",
    price: 800,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_254",
    name: "فيتامين د 1000 IU",
    genericName: "Vitamin D",
    activeIngredient: "Cholecalciferol 1000 IU",
    category: "فيتامينات",
    dosageForm: "كبسولات",
    strength: "1000 IU",
    packageSize: "30 كبسولة",
    price: 1400,
    stock: 100,
    requiresPrescription: false,
  },
  {
    id: "med_255",
    name: "فيتامين د 2000 IU",
    genericName: "Vitamin D",
    activeIngredient: "Cholecalciferol 2000 IU",
    category: "فيتامينات",
    dosageForm: "كبسولات",
    strength: "2000 IU",
    packageSize: "30 كبسولة",
    price: 1800,
    stock: 100,
    requiresPrescription: false,
  },
  {
    id: "med_256",
    name: "فيتامين د 5000 IU",
    genericName: "Vitamin D",
    activeIngredient: "Cholecalciferol 5000 IU",
    category: "فيتامينات",
    dosageForm: "كبسولات",
    strength: "5000 IU",
    packageSize: "30 كبسولة",
    price: 2200,
    stock: 90,
    requiresPrescription: false,
  },
  {
    id: "med_257",
    name: "فيتامين د شراب للأطفال",
    genericName: "Vitamin D",
    activeIngredient: "Cholecalciferol 400 IU/ml",
    category: "فيتامينات",
    dosageForm: "قطرات",
    strength: "400 IU/ml",
    packageSize: "10 ml",
    price: 1200,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_258",
    name: "فيتامين هـ 400 IU",
    genericName: "Vitamin E",
    activeIngredient: "Tocopherol 400 IU",
    category: "فيتامينات",
    dosageForm: "كبسولات",
    strength: "400 IU",
    packageSize: "30 كبسولة",
    price: 1600,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_259",
    name: "فيتامين هـ 800 IU",
    genericName: "Vitamin E",
    activeIngredient: "Tocopherol 800 IU",
    category: "فيتامينات",
    dosageForm: "كبسولات",
    strength: "800 IU",
    packageSize: "30 كبسولة",
    price: 2000,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_260",
    name: "فيتامين ب 12 1000 ميكروجرام",
    genericName: "Vitamin B12",
    activeIngredient: "Cyanocobalamin 1000 mcg",
    category: "فيتامينات",
    dosageForm: "أقراص",
    strength: "1000 mcg",
    packageSize: "30 قرص",
    price: 1200,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_261",
    name: "فيتامين ب 12 حقن",
    genericName: "Vitamin B12",
    activeIngredient: "Cyanocobalamin 1000 mcg",
    category: "فيتامينات",
    dosageForm: "حقن",
    strength: "1000 mcg",
    packageSize: "1 حقنة",
    price: 800,
    stock: 60,
    requiresPrescription: true,
  },
  {
    id: "med_262",
    name: "فيتامين ب المركب",
    genericName: "Vitamin B Complex",
    activeIngredient: "B1, B2, B3, B5, B6, B7, B9, B12",
    category: "فيتامينات",
    dosageForm: "أقراص",
    strength: "متعدد",
    packageSize: "30 قرص",
    price: 1400,
    stock: 90,
    requiresPrescription: false,
  },
  {
    id: "med_263",
    name: "فيتامين ب المركب شراب",
    genericName: "Vitamin B Complex",
    activeIngredient: "B1, B2, B3, B5, B6, B7, B9, B12",
    category: "فيتامينات",
    dosageForm: "شراب",
    strength: "متعدد",
    packageSize: "100 ml",
    price: 1200,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_264",
    name: "فيتامين أ 10000 IU",
    genericName: "Vitamin A",
    activeIngredient: "Retinol 10000 IU",
    category: "فيتامينات",
    dosageForm: "كبسولات",
    strength: "10000 IU",
    packageSize: "30 كبسولة",
    price: 1000,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_265",
    name: "فيتامين أ شراب للأطفال",
    genericName: "Vitamin A",
    activeIngredient: "Retinol 5000 IU/ml",
    category: "فيتامينات",
    dosageForm: "قطرات",
    strength: "5000 IU/ml",
    packageSize: "10 ml",
    price: 900,
    stock: 70,
    requiresPrescription: false,
  },
  {
    id: "med_266",
    name: "فيتامين ك 10 مجم",
    genericName: "Vitamin K",
    activeIngredient: "Phytomenadione 10 mg",
    category: "فيتامينات",
    dosageForm: "أقراص",
    strength: "10 mg",
    packageSize: "30 قرص",
    price: 800,
    stock: 70,
    requiresPrescription: false,
  },
  {
    id: "med_267",
    name: "فيتامين ك حقن",
    genericName: "Vitamin K",
    activeIngredient: "Phytomenadione 10 mg",
    category: "فيتامينات",
    dosageForm: "حقن",
    strength: "10 mg",
    packageSize: "1 حقنة",
    price: 600,
    stock: 50,
    requiresPrescription: true,
  },
  {
    id: "med_268",
    name: "حمض الفوليك 1 مجم",
    genericName: "Folic Acid",
    activeIngredient: "Folic Acid 1 mg",
    category: "فيتامينات",
    dosageForm: "أقراص",
    strength: "1 mg",
    packageSize: "30 قرص",
    price: 600,
    stock: 90,
    requiresPrescription: false,
  },
  {
    id: "med_269",
    name: "حمض الفوليك 5 مجم",
    genericName: "Folic Acid",
    activeIngredient: "Folic Acid 5 mg",
    category: "فيتامينات",
    dosageForm: "أقراص",
    strength: "5 mg",
    packageSize: "30 قرص",
    price: 800,
    stock: 90,
    requiresPrescription: true,
  },
  {
    id: "med_270",
    name: "زنك 50 مجم",
    genericName: "Zinc",
    activeIngredient: "Zinc Sulfate 50 mg",
    category: "مكملات",
    dosageForm: "أقراص",
    strength: "50 mg",
    packageSize: "30 قرص",
    price: 700,
    stock: 90,
    requiresPrescription: false,
  },
  {
    id: "med_271",
    name: "زنك 25 مجم للأطفال",
    genericName: "Zinc",
    activeIngredient: "Zinc Sulfate 25 mg",
    category: "مكملات",
    dosageForm: "أقراص",
    strength: "25 mg",
    packageSize: "30 قرص",
    price: 500,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_272",
    name: "زنك شراب للأطفال",
    genericName: "Zinc",
    activeIngredient: "Zinc Sulfate 10 mg/5ml",
    category: "مكملات",
    dosageForm: "شراب",
    strength: "10 mg/5 ml",
    packageSize: "100 ml",
    price: 600,
    stock: 70,
    requiresPrescription: false,
  },
  {
    id: "med_273",
    name: "مغنيسيوم 400 مجم",
    genericName: "Magnesium",
    activeIngredient: "Magnesium Oxide 400 mg",
    category: "مكملات",
    dosageForm: "أقراص",
    strength: "400 mg",
    packageSize: "30 قرص",
    price: 800,
    stock: 90,
    requiresPrescription: false,
  },
  {
    id: "med_274",
    name: "مغنيسيوم 200 مجم",
    genericName: "Magnesium",
    activeIngredient: "Magnesium Oxide 200 mg",
    category: "مكملات",
    dosageForm: "أقراص",
    strength: "200 mg",
    packageSize: "30 قرص",
    price: 600,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_275",
    name: "مغنيسيوم شراب للأطفال",
    genericName: "Magnesium",
    activeIngredient: "Magnesium 50 mg/5ml",
    category: "مكملات",
    dosageForm: "شراب",
    strength: "50 mg/5 ml",
    packageSize: "100 ml",
    price: 700,
    stock: 70,
    requiresPrescription: false,
  },
  {
    id: "med_276",
    name: "كالسيوم 600 مجم",
    genericName: "Calcium",
    activeIngredient: "Calcium Carbonate 600 mg",
    category: "مكملات",
    dosageForm: "أقراص",
    strength: "600 mg",
    packageSize: "30 قرص",
    price: 900,
    stock: 90,
    requiresPrescription: false,
  },
  {
    id: "med_277",
    name: "كالسيوم 1200 مجم",
    genericName: "Calcium",
    activeIngredient: "Calcium Carbonate 1200 mg",
    category: "مكملات",
    dosageForm: "أقراص",
    strength: "1200 mg",
    packageSize: "30 قرص",
    price: 1200,
    stock: 90,
    requiresPrescription: false,
  },
  {
    id: "med_278",
    name: "كالسيوم + فيتامين د",
    genericName: "Calcium + Vitamin D",
    activeIngredient: "Calcium 500 mg + Vitamin D 200 IU",
    category: "مكملات",
    dosageForm: "أقراص",
    strength: "500/200 mg/IU",
    packageSize: "30 قرص",
    price: 1100,
    stock: 90,
    requiresPrescription: false,
  },
  {
    id: "med_279",
    name: "كالسيوم شراب للأطفال",
    genericName: "Calcium",
    activeIngredient: "Calcium 100 mg/5ml",
    category: "مكملات",
    dosageForm: "شراب",
    strength: "100 mg/5 ml",
    packageSize: "100 ml",
    price: 800,
    stock: 70,
    requiresPrescription: false,
  },
  {
    id: "med_280",
    name: "حديد 100 مجم",
    genericName: "Iron",
    activeIngredient: "Ferrous Sulfate 100 mg",
    category: "مكملات",
    dosageForm: "أقراص",
    strength: "100 mg",
    packageSize: "30 قرص",
    price: 700,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_281",
    name: "حديد 50 مجم للأطفال",
    genericName: "Iron",
    activeIngredient: "Ferrous Sulfate 50 mg",
    category: "مكملات",
    dosageForm: "أقراص",
    strength: "50 mg",
    packageSize: "30 قرص",
    price: 500,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_282",
    name: "حديد شراب للأطفال",
    genericName: "Iron",
    activeIngredient: "Ferrous Sulfate 15 mg/5ml",
    category: "مكملات",
    dosageForm: "شراب",
    strength: "15 mg/5 ml",
    packageSize: "100 ml",
    price: 600,
    stock: 70,
    requiresPrescription: false,
  },
  {
    id: "med_283",
    name: "حديد + حمض الفوليك",
    genericName: "Iron + Folic Acid",
    activeIngredient: "Iron 100 mg + Folic Acid 1 mg",
    category: "مكملات",
    dosageForm: "أقراص",
    strength: "100/1 mg",
    packageSize: "30 قرص",
    price: 800,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_284",
    name: "أوميغا 3 1000 مجم",
    genericName: "Omega-3",
    activeIngredient: "EPA 180 mg + DHA 120 mg",
    category: "مكملات",
    dosageForm: "كبسولات",
    strength: "1000 mg",
    packageSize: "30 كبسولة",
    price: 1400,
    stock: 90,
    requiresPrescription: false,
  },
  {
    id: "med_285",
    name: "أوميغا 3 2000 مجم",
    genericName: "Omega-3",
    activeIngredient: "EPA 360 mg + DHA 240 mg",
    category: "مكملات",
    dosageForm: "كبسولات",
    strength: "2000 mg",
    packageSize: "30 كبسولة",
    price: 1800,
    stock: 90,
    requiresPrescription: false,
  },
  {
    id: "med_286",
    name: "أوميغا 3 500 مجم للأطفال",
    genericName: "Omega-3",
    activeIngredient: "EPA 90 mg + DHA 60 mg",
    category: "مكملات",
    dosageForm: "كبسولات",
    strength: "500 mg",
    packageSize: "30 كبسولة",
    price: 1000,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_287",
    name: "أوميغا 3 شراب للأطفال",
    genericName: "Omega-3",
    activeIngredient: "EPA 50 mg + DHA 35 mg",
    category: "مكملات",
    dosageForm: "شراب",
    strength: "متعدد",
    packageSize: "100 ml",
    price: 1200,
    stock: 70,
    requiresPrescription: false,
  },
  {
    id: "med_288",
    name: "كولاجين 1000 مجم",
    genericName: "Collagen",
    activeIngredient: "Hydrolyzed Collagen 1000 mg",
    category: "مكملات",
    dosageForm: "أقراص",
    strength: "1000 mg",
    packageSize: "30 قرص",
    price: 1600,
    stock: 80,
    requiresPrescription: false,
  },
  {
    id: "med_289",
    name: "كولاجين 500 مجم للأطفال",
    genericName: "Collagen",
    activeIngredient: "Hydrolyzed Collagen 500 mg",
    category: "مكملات",
    dosageForm: "أقراص",
    strength: "500 mg",
    packageSize: "30 قرص",
    price: 1200,
    stock: 70,
    requiresPrescription: false,
  },
  {
    id: "med_290",
    name: "كولاجين شراب للأطفال",
    genericName: "Collagen",
    activeIngredient: "Hydrolyzed Collagen 250 mg/5ml",
    category: "مكملات",
    dosageForm: "شراب",
    strength: "250 mg/5 ml",
    packageSize: "100 ml",
    price: 1400,
    stock: 60,
    requiresPrescription: false,
  },
  {
    id: "med_291",
    name: "بروتين مصل اللبن 1 كجم",
    genericName: "Whey Protein",
    activeIngredient: "Whey Protein Isolate",
    category: "مكملات",
    dosageForm: "بودرة",
    strength: "1000 g",
    packageSize: "1 كجم",
    price: 3000,
    stock: 60,
    requiresPrescription: false,
  },
  {
    id: "med_292",
    name: "بروتين نباتي 1 كجم",
    genericName: "Plant Protein",
    activeIngredient: "Pea + Rice Protein",
    category: "مكملات",
    dosageForm: "بودرة",
    strength: "1000 g",
    packageSize: "1 كجم",
    price: 2800,
    stock: 50,
    requiresPrescription: false,
  },
  {
    id: "med_293",
    name: "كرياتين 100 جم",
    genericName: "Creatine",
    activeIngredient: "Creatine Monohydrate",
    category: "مكملات",
    dosageForm: "بودرة",
    strength: "100 g",
    packageSize: "100 جم",
    price: 1500,
    stock: 60,
    requiresPrescription: false,
  },
  {
    id: "med_294",
    name: "بيتا ألانين 100 جم",
    genericName: "Beta-Alanine",
    activeIngredient: "Beta-Alanine",
    category: "مكملات",
    dosageForm: "بودرة",
    strength: "100 g",
    packageSize: "100 جم",
    price: 1600,
    stock: 50,
    requiresPrescription: false,
  },
  {
    id: "med_295",
    name: "L-كارنيتين 100 جم",
    genericName: "L-Carnitine",
    activeIngredient: "L-Carnitine",
    category: "مكملات",
    dosageForm: "بودرة",
    strength: "100 g",
    packageSize: "100 جم",
    price: 1800,
    stock: 50,
    requiresPrescription: false,
  },
  {
    id: "med_296",
    name: "غلوتامين 100 جم",
    genericName: "Glutamine",
    activeIngredient: "L-Glutamine",
    category: "مكملات",
    dosageForm: "بودرة",
    strength: "100 g",
    packageSize: "100 جم",
    price: 1400,
    stock: 50,
    requiresPrescription: false,
  },
  {
    id: "med_297",
    name: "BCAA 100 جم",
    genericName: "BCAA",
    activeIngredient: "Leucine, Isoleucine, Valine",
    category: "مكملات",
    dosageForm: "بودرة",
    strength: "100 g",
    packageSize: "100 جم",
    price: 1600,
    stock: 50,
    requiresPrescription: false,
  },
  {
    id: "med_298",
    name: "أرجينين 100 جم",
    genericName: "Arginine",
    activeIngredient: "L-Arginine",
    category: "مكملات",
    dosageForm: "بودرة",
    strength: "100 g",
    packageSize: "100 جم",
    price: 1500,
    stock: 50,
    requiresPrescription: false,
  },
  {
    id: "med_299",
    name: "أحماض أمينية أساسية",
    genericName: "Essential Amino Acids",
    activeIngredient: "9 Essential Amino Acids",
    category: "مكملات",
    dosageForm: "أقراص",
    strength: "500 mg",
    packageSize: "30 قرص",
    price: 1200,
    stock: 60,
    requiresPrescription: false,
  },
  {
    id: "med_300",
    name: "سيليوم 500 مجم",
    genericName: "Psyllium",
    activeIngredient: "Psyllium Husk",
    category: "مكملات",
    dosageForm: "أقراص",
    strength: "500 mg",
    packageSize: "30 قرص",
    price: 800,
    stock: 70,
    requiresPrescription: false,
  },
];

// ============================================================
// إضافة الحقول الإضافية المطلوبة للشاشة
// ============================================================

const finalProducts = products.map(product => ({
  ...product,
  
  // معلومات المنصة
  productId: product.id,
  sourceType: "platform",
  sellerType: "platform",
  sellerName: "صحتك",
  pharmacyId: null,
  
  // حالة النشر
  approvalStatus: "approved",
  verificationStatus: "approved",
  isPublished: true,
  isActive: true,
  
  // العملة
  currency: "YER",
  
  // حالة العرض
  isDemo: true,
  
  // التقييم
  rating: 4.5,
  reviewsCount: 0,
  
  // التوصيل
  deliveryAvailable: true,
  
  // بيانات زمنية
  updatedAt: admin.firestore.FieldValue.serverTimestamp(),
  createdAt: admin.firestore.FieldValue.serverTimestamp(),
}));

// ============================================================
// تشغيل السكربت
// ============================================================

async function seedProducts() {
  console.log("======================================");
  console.log("Sehatak Pharmacy Marketplace");
  console.log("جاري استيراد 300 منتج...");
  console.log("المنتجات:", finalProducts.length);
  console.log("======================================");

  const batchSize = 400;

  for (let i = 0; i < finalProducts.length; i += batchSize) {
    const batch = db.batch();
    const chunk = finalProducts.slice(i, i + batchSize);

    for (const product of chunk) {
      const ref = db.collection("products").doc(product.id);
      batch.set(ref, product, { merge: true });
    }

    await batch.commit();
    console.log(
      `تم رفع ${Math.min(i + chunk.length, finalProducts.length)}/${finalProducts.length}`
    );
  }

  console.log("");
  console.log("======================================");
  console.log("✅ تم الاستيراد بنجاح!");
  console.log("======================================");
  console.log("المجموعة: products");
  console.log("إجمالي المنتجات:", finalProducts.length);
  console.log("الحالة: approved");
  console.log("منشور: true");
  console.log("نشط: true");
  console.log("المصدر: platform");
  console.log("العملة: YER");
  console.log("======================================");
}

seedProducts()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("❌ فشل الاستيراد");
    console.error(error);
    process.exit(1);
  });
