import 'package:flutter/material.dart';
import 'package:sehatak/core/models/cart/cart_item.dart';
enum OrderStatus { pending, confirmed, preparing, ready, delivering, delivered, cancelled }
enum DeliveryType { standard, express, scheduled }
class OrderModel {
 final String id,userId; final List<CartItem> items; final OrderStatus status; final DateTime orderDate,createdAt,updatedAt; final double subtotal,discount,deliveryFee,tax,total; final DeliveryType deliveryType; final String? deliveryAddress,deliveryInstructions,phoneNumber,paymentMethod,transactionId; final Map<String,dynamic>? metadata; final DateTime? estimatedDelivery,deliveredAt;
 OrderModel({required this.id,required this.userId,required this.items,required this.status,required this.orderDate,required this.subtotal,required this.discount,required this.deliveryFee,required this.tax,required this.total,required this.deliveryType,this.deliveryAddress,this.deliveryInstructions,this.phoneNumber,this.paymentMethod,this.transactionId,this.metadata,this.estimatedDelivery,this.deliveredAt,required this.createdAt,required this.updatedAt});
 String get statusText=>switch(status){OrderStatus.pending=>'قيد المعالجة',OrderStatus.confirmed=>'مؤكد',OrderStatus.preparing=>'جاري التحضير',OrderStatus.ready=>'جاهز',OrderStatus.delivering=>'جاري التوصيل',OrderStatus.delivered=>'تم التوصيل',OrderStatus.cancelled=>'ملغي'};
 IconData get statusIcon=>Icons.receipt_long; Color get statusColor=>Colors.teal; String get deliveryTypeText=>switch(deliveryType){DeliveryType.standard=>'عادي',DeliveryType.express=>'سريع',DeliveryType.scheduled=>'مجدول'}; String get typeText=>deliveryTypeText; IconData get typeIcon=>Icons.local_shipping_outlined;
 Map<String,dynamic> toJson()=>{'id':id,'userId':userId,'items':items.map((e)=>e.toJson()).toList(),'status':status.name,'orderDate':orderDate.toIso8601String(),'subtotal':subtotal,'discount':discount,'deliveryFee':deliveryFee,'tax':tax,'total':total,'deliveryType':deliveryType.name,'deliveryAddress':deliveryAddress,'deliveryInstructions':deliveryInstructions,'phoneNumber':phoneNumber,'paymentMethod':paymentMethod,'transactionId':transactionId,'metadata':metadata,'estimatedDelivery':estimatedDelivery?.toIso8601String(),'deliveredAt':deliveredAt?.toIso8601String(),'createdAt':createdAt.toIso8601String(),'updatedAt':updatedAt.toIso8601String()};
 factory OrderModel.fromJson(Map<String,dynamic> d)=>OrderModel(id:d['id']?.toString()??'',userId:d['userId']?.toString()??'',items:(d['items'] is List?d['items']:const []).whereType<Map>().map((e)=>CartItem.fromMap(Map<String,dynamic>.from(e))).toList(),status:OrderStatus.values.firstWhere((e)=>e.name==d['status'],orElse:()=>OrderStatus.pending),orderDate:_date(d['orderDate'])??DateTime.now(),subtotal:(d['subtotal'] as num?)?.toDouble()??0,discount:(d['discount'] as num?)?.toDouble()??0,deliveryFee:(d['deliveryFee'] as num?)?.toDouble()??0,tax:(d['tax'] as num?)?.toDouble()??0,total:(d['total'] as num?)?.toDouble()??0,deliveryType:DeliveryType.values.firstWhere((e)=>e.name==d['deliveryType'],orElse:()=>DeliveryType.standard),deliveryAddress:d['deliveryAddress']?.toString(),deliveryInstructions:d['deliveryInstructions']?.toString(),phoneNumber:d['phoneNumber']?.toString(),paymentMethod:d['paymentMethod']?.toString(),transactionId:d['transactionId']?.toString(),metadata:d['metadata'] is Map?Map<String,dynamic>.from(d['metadata']):null,estimatedDelivery:_date(d['estimatedDelivery']),deliveredAt:_date(d['deliveredAt']),createdAt:_date(d['createdAt'])??DateTime.now(),updatedAt:_date(d['updatedAt'])??DateTime.now());
 static DateTime? _date(dynamic v)=>v is DateTime?v:v is String?DateTime.tryParse(v):null;
}
