import 'package:cloud_firestore/cloud_firestore.dart';

DateTime? _date(dynamic value) => value is Timestamp ? value.toDate() : value is DateTime ? value : null;
Timestamp? _stamp(DateTime? value) => value == null ? null : Timestamp.fromDate(value);

class PregnancyDoctor {
  final String id,name,specialty,photoUrl,address,phone; final double rating; final int reviewCount,experienceYears; final bool isVerified,isAvailable; final DateTime? createdAt,updatedAt;
  const PregnancyDoctor({required this.id,required this.name,required this.specialty,this.photoUrl='',this.rating=0,this.reviewCount=0,this.experienceYears=0,this.address='',this.phone='',this.isVerified=false,this.isAvailable=true,this.createdAt,this.updatedAt});
  factory PregnancyDoctor.fromFirestore(String id,Map<String,dynamic> d)=>PregnancyDoctor(id:id,name:'${d['name']??''}',specialty:'${d['specialty']??'نساء وتوليد'}',photoUrl:'${d['photoUrl']??''}',rating:(d['rating'] as num?)?.toDouble()??0,reviewCount:(d['reviewCount'] as num?)?.toInt()??0,experienceYears:(d['experienceYears'] as num?)?.toInt()??0,address:'${d['address']??''}',phone:'${d['phone']??''}',isVerified:d['isVerified']==true,isAvailable:d['isAvailable']!=false,createdAt:_date(d['createdAt']),updatedAt:_date(d['updatedAt']));
  Map<String,dynamic> toFirestore()=>{'name':name,'specialty':specialty,'photoUrl':photoUrl,'rating':rating,'reviewCount':reviewCount,'experienceYears':experienceYears,'address':address,'phone':phone,'isVerified':isVerified,'isAvailable':isAvailable,'createdAt':_stamp(createdAt),'updatedAt':_stamp(updatedAt)};
}
class PregnancyClinic {final String id,name,type,address,phone; final double rating; final bool isOpen; final GeoPoint? location; const PregnancyClinic({required this.id,required this.name,this.type='متابعة حمل',this.address='',this.phone='',this.rating=0,this.isOpen=true,this.location}); factory PregnancyClinic.fromFirestore(String id,Map<String,dynamic>d)=>PregnancyClinic(id:id,name:'${d['name']??''}',type:'${d['type']??'متابعة حمل'}',address:'${d['address']??''}',phone:'${d['phone']??''}',rating:(d['rating'] as num?)?.toDouble()??0,isOpen:d['isOpen']!=false,location:d['location'] is GeoPoint?d['location'] as GeoPoint:null); Map<String,dynamic> toFirestore()=>{'name':name,'type':type,'address':address,'phone':phone,'rating':rating,'isOpen':isOpen,'location':location};}
class PregnancyTip {final String id,title,body,category; final int? week; final bool isPublished; final DateTime? createdAt; const PregnancyTip({required this.id,required this.title,required this.body,this.category='تغذية',this.week,this.isPublished=true,this.createdAt}); factory PregnancyTip.fromFirestore(String id,Map<String,dynamic>d)=>PregnancyTip(id:id,title:'${d['title']??''}',body:'${d['body']??''}',category:'${d['category']??'تغذية'}',week:(d['week'] as num?)?.toInt(),isPublished:d['isPublished']!=false,createdAt:_date(d['createdAt'])); Map<String,dynamic> toFirestore()=>{'title':title,'body':body,'category':category,'week':week,'isPublished':isPublished,'createdAt':_stamp(createdAt)};}
class PregnancyHospital {final String id,name,address,phone; final bool emergency,isOpen; final GeoPoint? location; const PregnancyHospital({required this.id,required this.name,this.address='',this.phone='',this.emergency=false,this.isOpen=true,this.location}); factory PregnancyHospital.fromFirestore(String id,Map<String,dynamic>d)=>PregnancyHospital(id:id,name:'${d['name']??''}',address:'${d['address']??''}',phone:'${d['phone']??''}',emergency:d['emergency']==true,isOpen:d['isOpen']!=false,location:d['location'] is GeoPoint?d['location'] as GeoPoint:null); Map<String,dynamic> toFirestore()=>{'name':name,'address':address,'phone':phone,'emergency':emergency,'isOpen':isOpen,'location':location};}
class PregnancyConsultation {final String id,userId,doctorId,question,status,answer; final DateTime? createdAt,answeredAt; const PregnancyConsultation({required this.id,required this.userId,this.doctorId='',required this.question,this.status='pending',this.answer='',this.createdAt,this.answeredAt}); factory PregnancyConsultation.fromFirestore(String id,Map<String,dynamic>d)=>PregnancyConsultation(id:id,userId:'${d['userId']??''}',doctorId:'${d['doctorId']??''}',question:'${d['question']??''}',status:'${d['status']??'pending'}',answer:'${d['answer']??''}',createdAt:_date(d['createdAt']),answeredAt:_date(d['answeredAt'])); Map<String,dynamic> toFirestore()=>{'userId':userId,'doctorId':doctorId,'question':question,'status':status,'answer':answer,'createdAt':_stamp(createdAt),'answeredAt':_stamp(answeredAt)};}
class PregnancyTracker {final String uid; final DateTime? dueDate; final int currentWeek; final double? weight; final String bp,notes; const PregnancyTracker({required this.uid,this.dueDate,this.currentWeek=0,this.weight,this.bp='',this.notes=''}); factory PregnancyTracker.fromFirestore(String uid,Map<String,dynamic>d)=>PregnancyTracker(uid:uid,dueDate:_date(d['dueDate']),currentWeek:(d['currentWeek'] as num?)?.toInt()??0,weight:(d['weight'] as num?)?.toDouble(),bp:'${d['bp']??''}',notes:'${d['notes']??''}'); Map<String,dynamic> toFirestore()=>{'uid':uid,'dueDate':_stamp(dueDate),'currentWeek':currentWeek,'weight':weight,'bp':bp,'notes':notes};}
