import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:sehatak/bloc/dental/dental_bloc.dart';
import 'package:sehatak/bloc/dental/dental_event.dart';
import 'package:sehatak/bloc/dental/dental_state.dart';
import 'package:sehatak/core/models/dental/dental_models.dart';
import 'package:sehatak/presentation/widgets/specialty/specialty_banner.dart';
import 'package:sehatak/presentation/widgets/specialty/quick_actions_grid.dart';
import 'package:sehatak/presentation/widgets/specialty/doctors_section.dart';
import 'package:sehatak/presentation/widgets/specialty/clinics_section.dart';
import 'package:sehatak/presentation/widgets/specialty/tips_section.dart';
import 'package:sehatak/presentation/widgets/specialty/hospitals_section.dart';
import 'package:sehatak/presentation/widgets/specialty/consultation_cta.dart';
import 'package:sehatak/app_router.dart';
const _dentalColor=Color(0xFF00BCD4); const _dentalIcon='assets/icons/services/dentistry.png';
class DentalHealthScreen extends StatelessWidget{const DentalHealthScreen({super.key});@override Widget build(BuildContext context)=>BlocProvider(create:(_)=>DentalBloc()..add(const DentalStarted()),child:const _DentalHealthView());}
class _DentalHealthView extends StatelessWidget{const _DentalHealthView();
 Widget _image(String? path,{double size=52}){if(path==null||path.isEmpty)return Container(width:size,height:size,color:_dentalColor.withOpacity(.08),child:const Icon(Icons.person,color:_dentalColor));final image=path.startsWith('http')?Image.network(path,width:size,height:size,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const Icon(Icons.person,color:_dentalColor)):Image.asset(path,width:size,height:size,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const Icon(Icons.person,color:_dentalColor));return ClipRRect(borderRadius:BorderRadius.circular(12),child:image);}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Row(children:[Image.asset(_dentalIcon,width:28,height:28,errorBuilder:(_,__,___)=>const Icon(Icons.medical_services)),const SizedBox(width:8),const Text('صحة الأسنان')])),body:BlocBuilder<DentalBloc,DentalState>(builder:(context,state){if(state.isLoading&&state.doctors.isEmpty)return const Center(child:CircularProgressIndicator());return RefreshIndicator(onRefresh:()async{context.read<DentalBloc>().add(const DentalRefreshed());await Future<void>.delayed(const Duration(milliseconds:300));},child:ListView(padding:const EdgeInsets.all(16),children:[SpecialtyBanner(title:'صحة الأسنان',subtitle:'أطباء، عيادات، نصائح ووقاية للأسرة',iconPath:_dentalIcon,accentColor:_dentalColor),const SizedBox(height:18),QuickActionsGrid(accentColor:_dentalColor,actions:[SpecialtyQuickAction(title:'حجز موعد',icon:Icons.calendar_month,onTap:()=>context.push(AppRouter.dentalDoctors)),SpecialtyQuickAction(title:'استشارة',icon:Icons.question_answer,onTap:()=>context.push(AppRouter.dentalConsultation)),SpecialtyQuickAction(title:'طوارئ',icon:Icons.local_hospital,onTap:()=>context.push(AppRouter.dentalHospitals))]),const SizedBox(height:22),DoctorsSection(accentColor:_dentalColor,doctors:state.doctors.take(6).map((d)=>_doctorCard(context,d)).toList(),onSeeAll:()=>context.push(AppRouter.dentalDoctors)),const SizedBox(height:20),ClinicsSection(accentColor:_dentalColor,clinics:state.clinics.take(4).map((d)=>_clinicCard(context,d)).toList(),onSeeAll:()=>context.push(AppRouter.dentalClinics)),const SizedBox(height:20),TipsSection(accentColor:_dentalColor,tips:state.tips.take(6).map(_tipCard).toList(),onSeeAll:()=>context.push(AppRouter.dentalTips)),const SizedBox(height:20),HospitalsSection(accentColor:_dentalColor,hospitals:state.hospitals.take(3).map(_hospitalCard).toList(),onSeeAll:()=>context.push(AppRouter.dentalHospitals)),const SizedBox(height:20),ConsultationCta(accentColor:_dentalColor,onPressed:()=>context.push(AppRouter.dentalConsultation)),if(state.errorMessage!=null)Padding(padding:const EdgeInsets.only(top:12),child:Text(state.errorMessage!,style:TextStyle(color:Colors.red[700]))) ]));});}
 Widget _doctorCard(BuildContext c,DentalDoctor d)=>Card(child:InkWell(onTap:()=>c.push(AppRouter.dentalDoctorDetail.replaceFirst(':id',d.id)),child:Padding(padding:const EdgeInsets.all(10),child:Column(children:[_image(d.photoUrl),const SizedBox(height:7),Text(d.name,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w800)),Text(d.specialty,style:const TextStyle(fontSize:11,color:_dentalColor)),Text('★ ${d.rating.toStringAsFixed(1)}',style:const TextStyle(color:Colors.amber))]))));
 Widget _clinicCard(BuildContext c,DentalClinic d)=>Card(child:ListTile(onTap:()=>c.push(AppRouter.dentalClinicDetail.replaceFirst(':id',d.id)),leading:Container(width:48,height:48,padding:const EdgeInsets.all(8),decoration:BoxDecoration(color:_dentalColor.withOpacity(.1),borderRadius:BorderRadius.circular(12)),child:Image.asset(_dentalIcon,errorBuilder:(_,__,___)=>const Icon(Icons.local_hospital,color:_dentalColor))),title:Text(d.name,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text(d.address,maxLines:1,overflow:TextOverflow.ellipsis),trailing:Text(d.isOpen?'مفتوح':'مغلق',style:TextStyle(color:d.isOpen?Colors.green:Colors.red,fontWeight:FontWeight.w700))));
 Widget _tipCard(DentalTip d)=>Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Icon(Icons.lightbulb_outline,color:_dentalColor),const SizedBox(height:7),Text(d.title,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:5),Text(d.body,maxLines:3,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:11))])));
 Widget _hospitalCard(DentalHospital d)=>Card(child:ListTile(leading:Icon(d.emergency?Icons.emergency:Icons.local_hospital,color:d.emergency?Colors.red:_dentalColor),title:Text(d.name,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text(d.address,maxLines:1,overflow:TextOverflow.ellipsis),trailing:d.emergency?const Text('طوارئ',style:TextStyle(color:Colors.red,fontWeight:FontWeight.w700)):null));
}
