import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:file_picker/file_picker.dart';
import 'package:sehatak/core/services/imagekit_service.dart';
import 'package:sehatak/core/constants/app_colors.dart';
import 'package:sehatak/core/services/toast_service.dart';
import 'package:sehatak/presentation/widgets/common/custom_app_bar.dart';

class VerificationScreen extends StatefulWidget {
  final dynamic userModel;
  const VerificationScreen({super.key, this.userModel});
  @override State<VerificationScreen> createState()=>_VerificationScreenState();
}
class _VerificationScreenState extends State<VerificationScreen>{
  final _name=TextEditingController(),_age=TextEditingController(),_license=TextEditingController(),_experience=TextEditingController(),_specialty=TextEditingController(),_academic=TextEditingController();
  final Map<String,List<Map<String,dynamic>>> _docs={};
  bool _loading=true,_submitting=false,_verified=false;
  String _status='notSubmitted',_role='user'; String? _error;
  final _functions=FirebaseFunctions.instanceFor(region:'us-central1');
  static const _labels=<String,String>{'doctor':'طبيب','nurse':'ممرض','midwife':'قابلة وتوليد','physiotherapist':'أخصائي علاج طبيعي','pharmacist':'صيدلي','lab':'مختبر','paramedic':'مسعف','hospital':'مستشفى','clinic':'عيادة','medical_center':'مركز طبي','dentist':'طبيب أسنان','dental':'عيادة أسنان','ophthalmology':'طبيب عيون','eye_clinic':'مركز عيون','optometrist':'أخصائي بصريات','veterinarian':'طبيب بيطري','delivery':'موصل طلبات','service':'خدمي'};
  String get _roleLabel=>_labels[_role]??'الحساب المهني';
  List<String> get _specialRequirements{switch(_role){case 'lab':return ['ترخيص المختبر','نطاق الفحوصات والخدمات','المسؤول الفني'];case 'hospital':return ['ترخيص المنشأة','الأقسام والخدمات','بيانات المسؤول'];case 'dental':case 'dentist':return ['ترخيص طب الأسنان','التخصص والخدمات السنية'];case 'ophthalmology':case 'eye_clinic':case 'optometrist':return ['ترخيص العيون/البصريات','الخدمات والأجهزة'];default:return ['رقم الترخيص أو المزاولة','التخصص والخدمات'];}}
  @override void initState(){super.initState();_load();}
  @override void dispose(){for(final c in [_name,_age,_license,_experience,_specialty,_academic])c.dispose();super.dispose();}
  Future<void> _load() async{try{final u=FirebaseAuth.instance.currentUser;if(u==null)throw Exception('يجب تسجيل الدخول أولاً');final s=await FirebaseFirestore.instance.collection('users').doc(u.uid).get();final d=s.data()??{};if(!mounted)return;setState((){_role=d['role']?.toString()??'user';_name.text=d['name']?.toString()??d['displayName']?.toString()??'';_license.text=d['licenseNumber']?.toString()??'';_experience.text=d['experience']?.toString()??'';_specialty.text=d['specialty']?.toString()??'';_status=d['verificationStatus']?.toString()??'notSubmitted';_verified=d['isVerified']==true;_loading=false;});}catch(e){if(mounted)setState((){_error=e.toString();_loading=false;});}}
  Future<void> _pick(String category) async{final result=await FilePicker.platform.pickFiles(allowMultiple:true,type:FileType.custom,allowedExtensions:['pdf','jpg','jpeg','png']);if(result==null)return;final u=FirebaseAuth.instance.currentUser;if(u==null)return;setState(()=>_submitting=true);try{final list=<Map<String,dynamic>>[];for(final x in result.files){if(x.path==null)continue;final file=File(x.path!);if(await file.length()>12*1024*1024)throw Exception('حجم الملف '+x.name+' أكبر من 12MB');final url=await ImageKitService().uploadImage(file:file,folder:'/verification/'+u.uid+'/'+category,fileName:x.name,customMetadata:{'userId':u.uid,'role':_role,'category':category});list.add({'name':x.name,'url':url,'uploadedAt':DateTime.now().toIso8601String()});}setState(()=>_docs[category]=[...(_docs[category]??[]),...list]);ToastService.showSuccess('تم رفع '+list.length.toString()+' ملف');}catch(e){ToastService.showError(e.toString().replaceFirst('Exception: ',''));}finally{if(mounted)setState(()=>_submitting=false);}}
  Future<void> _submit() async{if(_submitting||_verified)return;if(_name.text.trim().isEmpty||_age.text.trim().isEmpty||_license.text.trim().isEmpty||_experience.text.trim().isEmpty||_academic.text.trim().isEmpty){ToastService.showError('أكمل البيانات الأساسية أولاً');return;}if((_docs['academicRecord']??[]).isEmpty||(_docs['certificates']??[]).isEmpty||(_docs['professionalRecord']??[]).isEmpty){ToastService.showError('ارفع السجل الأكاديمي والشهادات والسجل المهني');return;}setState(()=>_submitting=true);try{final r=await _functions.httpsCallable('submitVerificationRequest').call({'profile':{'fullName':_name.text.trim(),'age':int.tryParse(_age.text.trim()),'licenseNumber':_license.text.trim(),'experience':_experience.text.trim(),'specialty':_specialty.text.trim(),'academicSummary':_academic.text.trim(),'roleRequirements':_specialRequirements},'documents':_docs});if(mounted){setState(()=>_status=(r.data is Map&&r.data['status']!=null)?r.data['status'].toString():'pending');ToastService.showSuccess('تم إرسال طلب توثيق '+_roleLabel+' إلى المشرف للمراجعة');}}on FirebaseFunctionsException catch(e){ToastService.showError(e.message??'تعذر إرسال الطلب');}catch(e){ToastService.showError(e.toString());}finally{if(mounted)setState(()=>_submitting=false);}}
  Widget _field(TextEditingController c,String label,{TextInputType? type})=>Padding(padding:const EdgeInsets.only(bottom:10),child:TextField(controller:c,keyboardType:type,decoration:InputDecoration(labelText:label,border:const OutlineInputBorder())));
  Widget _upload(String key,String title)=>Card(child:ListTile(leading:const Icon(Icons.upload_file,color:AppColors.primary),title:Text(title),subtitle:Text((_docs[key]??[]).length.toString()+' ملف مرفوع'),trailing:IconButton(onPressed:_submitting?null:()=>_pick(key),icon:const Icon(Icons.add_circle_outline))));
  @override Widget build(BuildContext context){if(_loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));if(_error!=null)return Scaffold(body:Center(child:Text(_error!)));final dark=Theme.of(context).brightness==Brightness.dark;return Scaffold(backgroundColor:dark?const Color(0xFF0B1121):const Color(0xFFF8FAFC),appBar:CustomAppBar(title:'توثيق حساب '+_roleLabel,backgroundColor:AppColors.primary,foregroundColor:Colors.white,elevation:0),body:SingleChildScrollView(padding:const EdgeInsets.all(16),child:Column(children:[Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(_verified?'الحساب موثق':_status=='pending'?'الطلب قيد المراجعة':'يجب توثيق حسابك',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:8),Text(_verified?'تم اعتماد حسابك ويمكنك استخدام ميزات دورك.':_status=='pending'?'تم إرسال ملفك إلى المشرف وستصلك النتيجة عبر الإشعارات.':'لاستخدام ميزات '+_roleLabel+' يجب استكمال التوثيق وإرفاق المؤهلات والمستندات المطلوبة.')]))),const SizedBox(height:12),_field(_name,'الاسم الكامل'),_field(_age,'العمر',type:TextInputType.number),_field(_specialty,'التخصص'),_field(_license,'رقم الترخيص/المزاولة'),_field(_experience,'سنوات الخبرة'),_field(_academic,'ملخص السجل الأكاديمي'),const SizedBox(height:6),..._specialRequirements.map((x)=>Align(alignment:AlignmentDirectional.centerStart,child:Padding(padding:const EdgeInsets.only(bottom:6),child:Text('• '+x)))),_upload('academicRecord','السجل الأكاديمي'),_upload('certificates','الشهادات والمؤهلات'),_upload('professionalRecord','السجل المهني/الخبرات'),_upload('healthRecord','السجل الصحي/اللياقة المهنية'),_upload('identity','الهوية والمستندات الرسمية'),if(!_verified&&_status!='pending')SizedBox(width:double.infinity,height:52,child:FilledButton(onPressed:_submitting?null:_submit,child:Text(_submitting?'جارٍ الرفع/الإرسال...':'إرسال ملف التوثيق للمشرف'))),const SizedBox(height:10),const Text('الملفات المدعومة: PDF و JPG و PNG — الحد الأقصى 12MB للملف.',style:TextStyle(color:Colors.grey,fontSize:12))])));}
}
