import 'package:flutter/material.dart';
import 'package:sehatak/core/constants/app_colors.dart';
import 'package:sehatak/core/models/child_model.dart';
import 'package:sehatak/core/services/child_service.dart';

class ChildSectionScreen extends StatelessWidget{
  final String childId,section; const ChildSectionScreen({super.key,required this.childId,required this.section});
  static const titles={'growth':'النمو والتطور','vaccines':'التطعيمات','nutrition':'التغذية','sleep':'النوم','dental':'صحة الفم والأسنان','checkups':'الفحوصات الدورية','vision':'النظر والسمع','activity':'النشاط واللعب','mental':'الصحة النفسية','firstaid':'الإسعافات الأولية'};
  @override Widget build(BuildContext c){return Scaffold(appBar:AppBar(title:Text(titles[section]??'صحة الطفل'),backgroundColor:AppColors.primary,foregroundColor:Colors.white),body:StreamBuilder<ChildModel?>(stream:ChildService.instance.streamChild(childId),builder:(c,s){if(s.hasError)return Center(child:Text('تعذر تحميل الملف: '+s.error.toString()));if(!s.hasData)return const Center(child:CircularProgressIndicator());final ch=s.data;if(ch==null)return const Center(child:Text('لم يُعثر على ملف الطفل'));return ListView(padding:const EdgeInsets.all(16),children:[Card(child:ListTile(leading:CircleAvatar(backgroundColor:AppColors.primary.withOpacity(.12),child:Text(ch.name.isEmpty?'ط':ch.name.substring(0,1))),title:Text(ch.name),subtitle:Text(ch.ageLabel))),const SizedBox(height:12),..._content(ch)]);})));}
  List<Widget> _content(ChildModel c){final a=c.ageInMonths;String text;switch(section){case'nutrition':text='قدّم غذاءً متنوعاً ومناسباً للعمر. تجنب العسل قبل عمر سنة وانتبه لمخاطر الاختناق.';break;case'sleep':text='النوم الموصى به يعتمد على العمر: '+(a<3?'14–17':a<12?'12–16':a<36?'11–14':'10–13')+' ساعة خلال 24 ساعة.';break;case'dental':text='ابدأ العناية بالفم مبكراً واستخدم معجون فلورايد بكمية مناسبة للعمر وفق إرشادات طبيب الأسنان.';break;case'vaccines':text='تابع بطاقة التطعيم وجدول وزارة الصحة؛ الجرعات والمواعيد تختلف حسب البرنامج الوطني وحالة الطفل.';break;case'growth':text='الوزن: '+(c.weight?.toStringAsFixed(1)??'-')+' كجم\nالطول: '+(c.height?.toStringAsFixed(1)??'-')+' سم\nمحيط الرأس: '+(c.headCircumference?.toStringAsFixed(1)??'-')+' سم';break;case'checkups':text='تابع النمو والتغذية والتطور والسمع والنظر وصحة الفم ضمن الزيارات الوقائية المناسبة للعمر.';break;case'vision':text='راجع الطبيب عند وجود مشكلة مستمرة في الرؤية أو السمع أو صعوبة تتبع الأشياء أو الاستجابة للأصوات.';break;case'activity':text='شجّع الحركة واللعب والتفاعل المناسب للعمر وتحت إشراف آمن.';break;case'mental':text='روتين واضح واستماع واحتواء ولعب وتواصل يومي يدعم الصحة النفسية.';break;case'firstaid':text='في صعوبة التنفس أو فقدان الوعي أو نزيف شديد اطلب الطوارئ فوراً. إسعافات الاختناق والحروق تختلف حسب العمر وشدة الحالة.';break;default:text='محتوى القسم غير متوفر.';}return[Card(child:Padding(padding:const EdgeInsets.all(16),child:Text(text,style:const TextStyle(height:1.7)))),const SizedBox(height:8),const Card(child:Padding(padding:EdgeInsets.all(16),child:Text('المعلومات للتثقيف والمتابعة ولا تغني عن تقييم طبيب الأطفال عند الحاجة.',style:TextStyle(color:Colors.grey))))];}
}
