import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:sehatak/core/constants/app_colors.dart';
import 'package:sehatak/presentation/screens/lab/lab_booking_screen.dart';

class LabDetailScreen extends StatefulWidget {
  final String labId;
  const LabDetailScreen({super.key, required this.labId});
  @override State<LabDetailScreen> createState()=>_LabDetailScreenState();
}
class _LabDetailScreenState extends State<LabDetailScreen> with SingleTickerProviderStateMixin {
  final _db=FirebaseFirestore.instance;
  late final TabController _tabs;
  Map<String,dynamic>? _lab;
  bool _loading=true;
  String? _error;
  @override void initState(){super.initState();_tabs=TabController(length:2,vsync:this);_load();}
  @override void dispose(){_tabs.dispose();super.dispose();}
  String _s(dynamic v)=>v?.toString().trim()??'';
  double _n(dynamic v)=>v is num?v.toDouble():double.tryParse(_s(v))??0;
  List<dynamic> _list(dynamic v)=>v is List?v:const[];
  Future<void> _load() async { try { final snap=await _db.collection('labs').doc(widget.labId).get(); if(!snap.exists) throw Exception(); if(mounted)setState(()=>{_lab={'id':snap.id,...snap.data()!},_loading=false}); } catch(_){if(mounted)setState(()=>{_loading=false,_error='تعذر تحميل بيانات المختبر.'});} }
  @override Widget build(BuildContext context){final dark=Theme.of(context).brightness==Brightness.dark;if(_loading)return Scaffold(backgroundColor:dark?const Color(0xFF0B1121):const Color(0xFFF8FAFC),body:const Center(child:CircularProgressIndicator(color:AppColors.primary)));if(_error!=null)return Scaffold(appBar:AppBar(title:const Text('تفاصيل المختبر')),body:Center(child:Text(_error!)));final l=_lab!;final tests=_list(l['tests']);return Scaffold(backgroundColor:dark?const Color(0xFF0B1121):const Color(0xFFF8FAFC),appBar:AppBar(title:Text(_s(l['name']).isEmpty?'المختبر':_s(l['name'])),backgroundColor:AppColors.primary,foregroundColor:Colors.white,bottom:TabBar(controller:_tabs,tabs:const[Tab(text:'نبذة'),Tab(text:'الفحوصات')],indicatorColor:Colors.white,labelColor:Colors.white,unselectedLabelColor:Colors.white70)),body:TabBarView(controller:_tabs,children:[_overview(l,dark),_tests(l,tests,dark)]));}
  Widget _overview(Map<String,dynamic> l,bool dark)=>SingleChildScrollView(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[_card(dark,Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(_s(l['name']),style:TextStyle(fontSize:20,fontWeight:FontWeight.bold,color:dark?Colors.white:Colors.black87)),const SizedBox(height:8),Text(_s(l['description']).isEmpty?'مختبر يقدم خدمات مخبرية متكاملة.':_s(l['description']),style:TextStyle(height:1.6,color:dark?Colors.grey[300]:Colors.grey[700])),const SizedBox(height:12),_row(Icons.location_on,'العنوان',_s(l['address']??l['location']??'غير محدد'),dark),_row(Icons.phone,'الهاتف',_s(l['phone']).isEmpty?'غير متوفر':_s(l['phone']),dark),_row(Icons.email,'البريد',_s(l['email']).isEmpty?'غير متوفر':_s(l['email']),dark),_row(Icons.star,'التقييم',_n(l['rating']).toStringAsFixed(1)+' ('+_n(l['reviews']??l['reviewsCount']).toInt().toString()+' تقييم)',dark)])),const SizedBox(height:16),_card(dark,Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('الخدمات والتخصصات',style:TextStyle(fontWeight:FontWeight.bold,color:dark?Colors.white:Colors.black87)),const SizedBox(height:10),Wrap(spacing:8,runSpacing:8,children:_list(l['specialties']).map((x)=>Chip(label:Text(_s(x)))).toList())])),const SizedBox(height:24)]));
  Widget _tests(Map<String,dynamic> l,List<dynamic> tests,bool dark)=>Column(children:[Expanded(child:tests.isEmpty?Center(child:Text('لا توجد فحوصات مسجلة حاليًا.',style:TextStyle(color:dark?Colors.grey[300]:Colors.grey[700]))):ListView.builder(padding:const EdgeInsets.all(16),itemCount:tests.length,itemBuilder:(c,i){final t=tests[i] is Map?Map<String,dynamic>.from(tests[i]):{'name':tests[i]};return Card(color:dark?const Color(0xFF1A2540):Colors.white,child:ListTile(leading:const CircleAvatar(backgroundColor:Color(0x1A0A8F83),child:Icon(Icons.science,color:AppColors.primary)),title:Text(_s(t['name']).isEmpty?'فحص':_s(t['name']),style:TextStyle(color:dark?Colors.white:Colors.black87,fontWeight:FontWeight.w600)),subtitle:Text(_s(t['description']),style:TextStyle(color:dark?Colors.grey[400]:Colors.grey[600])),trailing:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text('${_n(t['price']).toStringAsFixed(0)} ر.ي',style:const TextStyle(color:AppColors.primary,fontWeight:FontWeight.bold)),TextButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>LabBookingScreen(labId:_s(l['id']),testId:_s(t['id'])))),child:const Text('حجز'))])));}),),Container(padding:const EdgeInsets.all(16),color:dark?const Color(0xFF1A2540):Colors.white,child:SizedBox(width:double.infinity,child:ElevatedButton.icon(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>LabBookingScreen(labId:_s(l['id'])))),icon:const Icon(Icons.calendar_today),label:const Text('حجز فحص'),style:ElevatedButton.styleFrom(backgroundColor:AppColors.primary,foregroundColor:Colors.white))))]);
  Widget _card(bool dark,Widget child)=>Container(width:double.infinity,padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:dark?const Color(0xFF1A2540):Colors.white,borderRadius:BorderRadius.circular(16)),child:child);
  Widget _row(IconData i,String label,String value,bool dark)=>Padding(padding:const EdgeInsets.symmetric(vertical:5),child:Row(children:[Icon(i,size:18,color:AppColors.primary),const SizedBox(width:8),Text('$label: ',style:TextStyle(color:dark?Colors.grey[400]:Colors.grey[600])),Expanded(child:Text(value,style:TextStyle(color:dark?Colors.white:Colors.black87,fontWeight:FontWeight.w500)))]));
}
