import 'dart:async';
import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:livekit_client/livekit_client.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:sehatak/core/models/call_model.dart';
import 'package:sehatak/core/services/active_call_registry.dart';
import 'package:sehatak/core/services/call_service.dart';
import 'package:sehatak/core/services/livekit_service.dart';
import 'package:sehatak/core/services/toast_service.dart';

class CallScreen extends StatefulWidget {
  final String chatId; final String? callId; final String doctorName; final String doctorId; final bool isVideo; final String? doctorImage; final bool isOutgoing;
  const CallScreen({super.key,required this.chatId,this.callId,required this.doctorName,required this.doctorId,this.isVideo=true,this.doctorImage,this.isOutgoing=true});
  @override State<CallScreen> createState()=>_CallScreenState();
}
class _CallScreenState extends State<CallScreen>{
  static const teal=Color(0xFF0A8F83),cyan=Color(0xFF00BCD4),red=Color(0xFFE53935),card=Color(0xFF1A1A1A);
  final live=LiveKitService(),calls=CallService(); Room? room; StreamSubscription<CallModel?>? callSub; StreamSubscription<ConnectivityResult>? netSub; Timer? timeout,timer,sync,triple;
  String? callId,roomName,error; VideoTrack? localTrack,remoteTrack; DateTime? connectedAt; int seconds=0,taps=0; bool joined=false,ending=false,connecting=true,muted=false,camera=true,speaker=false,online=true,swapped=false;
  @override void initState(){super.initState();final id=widget.callId?.trim();if(id!=null&&id.isNotEmpty){if(ActiveCallRegistry.instance.hasActiveCall&&!ActiveCallRegistry.instance.isActive(id)){unawaited(calls.markBusy(id));WidgetsBinding.instance.addPostFrameCallback((_){if(mounted){Navigator.pop(context);ToastService.showError('مشغول في مكالمة أخرى');}});return;}ActiveCallRegistry.instance.register(id);}watchNet();connect();}
  Future<void> watchNet()async{try{final c=await Connectivity().checkConnectivity();if(mounted)setState(()=>online=c!=ConnectivityResult.none);netSub=Connectivity().onConnectivityChanged.listen((c){if(mounted)setState(()=>online=c!=ConnectivityResult.none);});}catch(e){debugPrint('CALL NET $e');}}
  Future<void> connect()async{try{final user=FirebaseAuth.instance.currentUser;if(user==null)throw StateError('يجب تسجيل الدخول');if((await Connectivity().checkConnectivity())==ConnectivityResult.none)throw StateError('لا يوجد اتصال بالإنترنت');CallModel? c;final supplied=widget.callId?.trim();if(supplied!=null&&supplied.isNotEmpty){c=await calls.streamCall(supplied).first;if(c==null)throw StateError('المكالمة غير موجودة');if(widget.isOutgoing&&c.callerId!=user.uid)throw StateError('المكالمة ليست صادرة من المستخدم');if(!widget.isOutgoing&&c.receiverId!=user.uid)throw StateError('المكالمة ليست موجهة لهذا المستخدم');}else if(widget.isOutgoing){c=await calls.initiateCall(receiverId:widget.doctorId,receiverName:widget.doctorName,receiverPhotoUrl:widget.doctorImage,type:widget.isVideo?CallType.video:CallType.audio,chatId:widget.chatId);}else{throw StateError('معرّف المكالمة مفقود');}callId=c.id;roomName=c.liveKitRoomName?.trim().isNotEmpty==true?c.liveKitRoomName!.trim():'call_${c.id}';ActiveCallRegistry.instance.register(c.id);callSub=calls.streamCall(c.id).listen((u){if(!mounted||u==null||ending)return;if(u.status==CallStatus.connected){final d=u.connectedAt?.toDate();if(d!=null)setConnectedAt(d);if(!joined)unawaited(join(u,user));}else if(_terminal(u.status))unawaited(finishRemote());});if(widget.isOutgoing&&c.status!=CallStatus.connected){timeout=Timer(const Duration(seconds:30),()async{if(ending||joined)return;try{await calls.missCall(c!.id);}catch(e){debugPrint('CALL TIMEOUT $e');}if(mounted)await finishRemote();});}if(c.status==CallStatus.connected)await join(c,user);else if(mounted)setState(()=>connecting=false);}catch(e){ActiveCallRegistry.instance.unregister(callId??widget.callId);debugPrint('CALL CONNECT $e');if(mounted){setState((){connecting=false;error=e.toString().replaceFirst('Exception: ','');});ToastService.showError('فشل تجهيز المكالمة');}}}
  bool _terminal(CallStatus s)=>s==CallStatus.cancelled||s==CallStatus.rejected||s==CallStatus.missed||s==CallStatus.ended||s==CallStatus.busy;
  void setConnectedAt(DateTime d){connectedAt=d;final e=DateTime.now().difference(d).inSeconds;seconds=e<0?0:e;if(mounted)setState((){});timer??=Timer.periodic(const Duration(seconds:1),(_){if(mounted&&!ending&&connectedAt!=null){final n=DateTime.now().difference(connectedAt!).inSeconds;setState(()=>seconds=n<0?0:n);}});}
  Future<void> join(CallModel c,User user)async{if(joined||ending||c.status!=CallStatus.connected)return;try{if(widget.isVideo&&!(await Permission.camera.request()).isGranted)throw StateError('يرجى منح إذن الكاميرا');if(!(await Permission.microphone.request()).isGranted)throw StateError('يرجى منح إذن الميكروفون');room=await live.startCall(roomName:roomName!,callerName:user.displayName?.trim().isNotEmpty==true?user.displayName!.trim():widget.doctorName,isVideo:widget.isVideo);joined=true;timeout?.cancel();setConnectedAt(c.connectedAt?.toDate()??DateTime.now());syncTracks();room!.events.on<ParticipantConnectedEvent>((_)=>syncTracks());room!.events.on<TrackSubscribedEvent>((e){syncTracks();bind(e.participant);});room!.events.on<TrackPublishedEvent>((e){syncTracks();bind(e.participant);});room!.events.on<ParticipantDisconnectedEvent>((_)=>syncTracks());sync?.cancel();sync=Timer.periodic(const Duration(milliseconds:500),(_){if(mounted&&!ending)syncTracks();});await live.setSpeakerphone(speaker);if(mounted)setState((){connecting=false;error=null;});}catch(e){ActiveCallRegistry.instance.unregister(c.id);debugPrint('CALL LIVEKIT $e');if(mounted)setState((){connecting=false;error=e.toString().replaceFirst('Exception: ','');});}}
  void syncTracks(){final r=room;if(r==null||!mounted)return;VideoTrack? l,rem;final lp=r.localParticipant;if(lp!=null){for(final p in lp.videoTracks){if(p.track is VideoTrack){l=p.track as VideoTrack;break;}}}for(final part in r.remoteParticipants.values){for(final p in part.videoTracks){if(p.track is VideoTrack){rem=p.track as VideoTrack;break;}}if(rem!=null)break;}if(l!=localTrack||rem!=remoteTrack)setState((){localTrack=l;remoteTrack=rem;});}
  void bind(Participant p){for(final pub in p.videoTracks){if(pub.track is VideoTrack){if(p is LocalParticipant){if(mounted)setState(()=>localTrack=pub.track as VideoTrack);}else if(mounted)setState(()=>remoteTrack=pub.track as VideoTrack);}}}
  void tapPreview(){taps++;triple?.cancel();if(taps>=3){taps=0;if(mounted)setState(()=>swapped=!swapped);return;}triple=Timer(const Duration(milliseconds:600),()=>taps=0);}
  Future<void> finishRemote()async{if(ending)return;ending=true;timeout?.cancel();timer?.cancel();sync?.cancel();await callSub?.cancel();ActiveCallRegistry.instance.unregister(callId??widget.callId);await live.endCall();if(mounted)Navigator.pop(context);}
  Future<void>end()async{if(ending)return;ending=true;timeout?.cancel();timer?.cancel();sync?.cancel();await callSub?.cancel();ActiveCallRegistry.instance.unregister(callId??widget.callId);try{if(callId!=null)await calls.endCall(callId!,durationSeconds:joined?seconds:0);}catch(e){debugPrint('CALL END $e');}await live.endCall();if(mounted)Navigator.pop(context);}
  Future<void>mute()async{final e=await live.toggleMicrophone();if(mounted)setState(()=>muted=!e);}
  Future<void>toggleCamera()async{final e=await live.toggleCamera();if(mounted)setState(()=>camera=e);syncTracks();}
  Future<void>switchCamera()async{await live.switchCamera();}
  Future<void>toggleSpeaker()async{final e=!speaker;await live.setSpeakerphone(e);if(mounted)setState(()=>speaker=e);}
  @override void dispose(){timeout?.cancel();timer?.cancel();sync?.cancel();triple?.cancel();callSub?.cancel();netSub?.cancel();ActiveCallRegistry.instance.unregister(callId??widget.callId);if(joined)unawaited(live.endCall());super.dispose();}
  @override Widget build(BuildContext context){final remote=swapped?localTrack:remoteTrack,local=swapped?remoteTrack:localTrack;final status=error??(!online?'لا يوجد اتصال بالإنترنت':connecting?(widget.isOutgoing?'جاري تجهيز المكالمة...':'جاري الاتصال...'):!joined?'في انتظار قبول المكالمة...':fmt(seconds));return Scaffold(backgroundColor:Colors.black,body:SafeArea(child:Stack(children:[if(widget.isVideo&&remote!=null)Positioned.fill(child:VideoTrackRenderer(remote,fit:BoxFit.cover))else Positioned.fill(child:waiting(status)),if(widget.isVideo&&local!=null)PositionedDirectional(top:68,end:18,child:GestureDetector(onTap:tapPreview,child:preview(local))),if(widget.isVideo&&joined&&remoteTrack==null)Positioned.fill(child:IgnorePointer(child:fallback())),Positioned(top:12,left:12,right:12,child:top(status)),if(error==null)Positioned(bottom:18,left:14,right:14,child:controls())])));}
  Widget preview(VideoTrack t)=>Container(width:118,height:176,clipBehavior:Clip.antiAlias,decoration:BoxDecoration(color:Colors.black,borderRadius:BorderRadius.circular(16),border:Border.all(color:Colors.white38,width:1.5),boxShadow:const[BoxShadow(color:Colors.black54,blurRadius:18,spreadRadius:2)]),child:Stack(fit:StackFit.expand,children:[VideoTrackRenderer(t,fit:BoxFit.cover),Positioned(bottom:7,left:7,right:7,child=Container())]));
  Widget fallback()=>Center(child:Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(color:Colors.black54,borderRadius:BorderRadius.circular(24),border:Border.all(color:teal.withOpacity(.3))),child:Column(mainAxisSize:MainAxisSize.min,children:[avatar(96),const SizedBox(height:12),Text(widget.doctorName,style:const TextStyle(color:Colors.white,fontSize:20,fontWeight:FontWeight.w700)),const SizedBox(height:6),const Text('الكاميرا غير مفعلة',style:TextStyle(color:Colors.white60))])));
  Widget waiting(String s)=>Center(child:Column(mainAxisSize:MainAxisSize.min,children:[avatar(140),const SizedBox(height:22),Text(widget.doctorName,style:const TextStyle(color:Colors.white,fontSize:26,fontWeight:FontWeight.w700)),const SizedBox(height:12),badge(s),const SizedBox(height:22),Text(fmt(seconds),style:const TextStyle(color:Colors.white,fontSize:34,fontWeight:FontWeight.w300))]));
  Widget avatar(double size)=>Container(width:size,height:size,decoration:BoxDecoration(shape:BoxShape.circle,gradient:const LinearGradient(colors:[teal,Color(0xFF00695C)]),image:widget.doctorImage?.trim().isNotEmpty==true?DecorationImage(image:NetworkImage(widget.doctorImage!.trim()),fit:BoxFit.cover):null),child:widget.doctorImage?.trim().isNotEmpty==true?null:const Icon(Icons.person_rounded,color:Colors.white,size:58));
  Widget top(String s)=>Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[glass(Icons.close_rounded,end),badge(joined?fmt(seconds):s),if(widget.isVideo&&remoteTrack!=null)glass(Icons.swap_vert_rounded,()=>setState(()=>swapped=!swapped))else const SizedBox(width:44)]);
  Widget badge(String s)=>Container(padding:const EdgeInsets.symmetric(horizontal:16,vertical:9),decoration:BoxDecoration(color:teal.withOpacity(.15),borderRadius:BorderRadius.circular(24),border:Border.all(color:teal.withOpacity(.3)),boxShadow:[BoxShadow(color:teal.withOpacity(.1),blurRadius:16)]),child:Row(mainAxisSize:MainAxisSize.min,children:[Icon(joined?Icons.circle:Icons.lock_outline,color:joined?Colors.greenAccent:cyan,size:14),const SizedBox(width:7),Text(s,style:const TextStyle(color:Colors.white,fontSize:13,fontWeight:FontWeight.w600))]));
  Widget glass(IconData i,VoidCallback f)=>Material(color:Colors.transparent,child:InkWell(onTap:f,borderRadius:BorderRadius.circular(24),child:Container(width:44,height:44,decoration:BoxDecoration(color:Colors.black54,shape:BoxShape.circle,border:Border.all(color:Colors.white.withOpacity(.16))),child:Icon(i,color:Colors.white,size:22))));
  Widget controls()=>ClipRRect(borderRadius:BorderRadius.circular(30),child=Container(padding:const EdgeInsets.symmetric(horizontal:8,vertical:11),decoration:BoxDecoration(color:card.withOpacity(.9),border:Border.all(color:Colors.white.withOpacity(.1)),borderRadius:BorderRadius.circular(30)),child:Row(mainAxisAlignment:MainAxisAlignment.spaceEvenly,children:[button(Icons.volume_up_rounded,'سماعة',card,toggleSpeaker,active:speaker),button(muted?Icons.mic_off_rounded:Icons.mic_rounded,'كتم',cyan,mute,active:muted),if(widget.isVideo)button(camera?Icons.videocam_rounded:Icons.videocam_off_rounded,'كاميرا',cyan,toggleCamera,active:!camera),if(widget.isVideo)button(Icons.cameraswitch_rounded,'تبديل',teal,switchCamera),button(Icons.call_end_rounded,'إنهاء',red,end,main:true)])));
  Widget button(IconData i,String label,Color c,VoidCallback f,{bool active=false,bool main=false})=>Column(mainAxisSize:MainAxisSize.min,children:[Material(color:Colors.transparent,child:InkWell(onTap:f,borderRadius:BorderRadius.circular(32),child:Container(width:main?68:58,height:main?68:58,decoration:BoxDecoration(shape:BoxShape.circle,color:main?c:(active?c.withOpacity(.22):c.withOpacity(.12)),border:Border.all(color:main?c:c.withOpacity(.7),width:main?0:1.4)),child:Icon(i,color:main?Colors.white:c,size:main?30:25)))),const SizedBox(height:5),Text(label,style:const TextStyle(color:Colors.white70,fontSize:10))]);
  String fmt(int s){final h=s~/3600,m=(s%3600)~/60,sec=s%60;return h>0?'${h.toString().padLeft(2,'0')}:${m.toString().padLeft(2,'0')}:${sec.toString().padLeft(2,'0')}':'${m.toString().padLeft(2,'0')}:${sec.toString().padLeft(2,'0')}';}
}
