import 'dart:async';
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:livekit_client/livekit_client.dart';
import 'package:sehatak/core/models/call_model.dart';
import 'package:sehatak/core/services/call_service.dart';
import 'package:sehatak/core/services/livekit_service.dart';
import 'package:sehatak/core/services/sound_manager.dart';
import 'package:sehatak/core/services/toast_service.dart';

class CallScreen extends StatefulWidget {
  final String chatId; final String? callId; final String doctorName, doctorId; final bool isVideo; final String? doctorImage; final bool isOutgoing;
  const CallScreen({super.key,required this.chatId,this.callId,required this.doctorName,required this.doctorId,this.isVideo=true,this.doctorImage,this.isOutgoing=true});
  @override State<CallScreen> createState()=>_CallScreenState();
}
class _CallScreenState extends State<CallScreen>{
 final _live=LiveKitService(),_calls=CallService(); Room? _room; StreamSubscription<CallModel?>? _sub; Timer? _timeout,_timer; String? _id,_roomName,_error; VideoTrack? _remote,_local; int _seconds=0; DateTime? _connectedAt; bool _joined=false,_ending=false,_connecting=true,_muted=false,_camera=true,_speaker=false;
 @override void initState(){super.initState();_connect();}
 Future<void> _connect()async{try{final user=FirebaseAuth.instance.currentUser;if(user==null)throw StateError('يجب تسجيل الدخول');CallModel? call;if(widget.isOutgoing){call=await _calls.initiateCall(receiverId:widget.doctorId,receiverName:widget.doctorName,receiverPhotoUrl:widget.doctorImage,type:widget.isVideo?CallType.video:CallType.audio,chatId:widget.chatId);}else{if(widget.callId==null)throw StateError('معرّف المكالمة مفقود');call=await _calls.streamCall(widget.callId!).first;if(call==null||call!.receiverId!=user.uid)throw StateError('هذه المكالمة ليست موجهة لهذا المستخدم');}if(call==null)throw StateError('تعذر العثور على المكالمة');_id=call.id;_roomName=(call.liveKitRoomName?.isNotEmpty==true?call.liveKitRoomName:'call_${call.id}');_sub=_calls.streamCall(call.id).listen((c){if(!mounted||c==null)return;if(c.status==CallStatus.connected&&!_joined)_join(c,user);else if([CallStatus.cancelled,CallStatus.rejected,CallStatus.missed,CallStatus.ended].contains(c.status)&&!_ending)_finishRemote();});if(widget.isOutgoing&&call.status!=CallStatus.connected)_timeout=Timer(const Duration(seconds:45),()async{if(_ending||_joined)return;try{await _calls.missCall(call!.id);}catch(e){debugPrint('call timeout: $e');}if(mounted)_finishRemote();});if(call.status==CallStatus.connected)await _join(call,user);if(mounted)setState(()=>_connecting=!_joined);}catch(e){debugPrint('Call connect: $e');if(mounted)setState((){_connecting=false;_error=e.toString();});ToastService.showError('فشل تجهيز المكالمة');}}
 Future<void> _join(CallModel call,User user)async{if(_joined||_ending)return;try{if(widget.isVideo&&!(await Permission.camera.request()).isGranted)throw StateError('يرجى منح إذن الكاميرا');if(!(await Permission.microphone.request()).isGranted)throw StateError('يرجى منح إذن الميكروفون');_room=await _live.startCall(roomName:_roomName!,callerName:user.displayName??widget.doctorName,isVideo:widget.isVideo);_joined=true;_connectedAt=call.connectedAt?.toDate()??DateTime.now();_timer=Timer.periodic(const Duration(seconds:1),(_){if(mounted)setState(()=>_seconds=DateTime.now().difference(_connectedAt!).inSeconds);});_room!.events.on<ParticipantConnectedEvent>((e)=>_bind(e.participant));_room!.events.on<TrackSubscribedEvent>((e)=>_bind(e.participant));_room!.events.on<TrackPublishedEvent>((e)=>_bind(e.participant));_room!.events.on<ParticipantDisconnectedEvent>((e){if(mounted)setState(()=>_remote=null);});_room!.localParticipant?.let(_bind);if(mounted)setState(()=>_connecting=false);}catch(e){if(mounted)setState((){_connecting=false;_error=e.toString();});}}
 void _bind(Participant p){for(final pub in p.videoTracks){final t=pub.track;if(t is VideoTrack&&mounted)setState(()=>p is LocalParticipant?_local=t:_remote=t);}}
 Future<void> _finishRemote()async{if(_ending)return;_ending=true;_timeout?.cancel();_timer?.cancel();_sub?.cancel();SoundManager().stopAll();await _live.endCall();if(mounted)Navigator.of(context).pop();}
 Future<void> _end()async{if(_ending)return;_ending=true;_timeout?.cancel();_timer?.cancel();_sub?.cancel();SoundManager().stopAll();try{if(_id!=null)await _calls.endCall(_id!,durationSeconds:_joined?_seconds:0);}catch(e){debugPrint('call end: $e');}await _live.endCall();if(mounted)Navigator.of(context).pop();}
 Future<void> _mute()async{final e=await _live.toggleMicrophone();if(mounted)setState(()=>_muted=!e);}Future<void> _cam()async{final e=await _live.toggleCamera();if(mounted)setState(()=>_camera=e);}
 @override void dispose(){_timeout?.cancel();_timer?.cancel();_sub?.cancel();SoundManager().stopAll();if(_joined)_live.endCall();super.dispose();}
 @override Widget build(BuildContext c)=>Scaffold(backgroundColor:Colors.black,body:SafeArea(child:Stack(children:[Positioned.fill(child:widget.isVideo&&_remote!=null?VideoTrackRenderer(_remote!):Center(child:Column(mainAxisSize:MainAxisSize.min,children:[CircleAvatar(radius:54,backgroundImage:widget.doctorImage!=null?NetworkImage(widget.doctorImage!):null,child:widget.doctorImage==null?const Icon(Icons.person,color:Colors.white,size:48):null),const SizedBox(height:18),Text(widget.doctorName,style:const TextStyle(color:Colors.white,fontSize:22,fontWeight:FontWeight.bold)),const SizedBox(height:8),Text(_error??(_connecting?(widget.isOutgoing?'في انتظار قبول المكالمة...':'جاري الاتصال...'):_fmt(_seconds)),style:const TextStyle(color:Colors.white70))]))),if(widget.isVideo&&_local!=null)PositionedDirectional(top:18,end:18,child:ClipRRect(borderRadius:BorderRadius.circular(14),child:SizedBox(width:110,height:160,child:VideoTrackRenderer(_local!)))),if(_error==null)Positioned(bottom:28,left:0,right:0,child:Row(mainAxisAlignment:MainAxisAlignment.center,children:[_btn(_muted?Icons.mic_off:Icons.mic,_mute),if(widget.isVideo)_btn(_camera?Icons.videocam:Icons.videocam_off,_cam),_btn(_speaker?Icons.volume_up:Icons.volume_down,(){setState(()=>_speaker=!_speaker);_live.setSpeakerphone(_speaker);}),_btn(Icons.call_end,_end,red:true)]))])));
 Widget _btn(IconData i,VoidCallback f,{bool red=false})=>Padding(padding:const EdgeInsets.symmetric(horizontal:7),child:FloatingActionButton(heroTag:'${i.codePoint}${red?'r':''}',mini:true,backgroundColor:red?Colors.red:Colors.white12,onPressed:f,child:Icon(i,color:Colors.white)));
 String _fmt(int s)=>'${(s~/60).toString().padLeft(2,'0')}:${(s%60).toString().padLeft(2,'0')}';
}
extension<T> on T{R let<R>(R Function(T) f)=>f(this);}
