import 'dart:typed_data';
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:sehatak/core/models/template_model.dart';
class TemplateService {
 static final _instance=TemplateService._internal(); factory TemplateService()=>_instance; TemplateService._internal();
 Future<ui.Image> generateImageFromTemplate({required TemplateModel template,required String primaryText,required String secondaryText,required Size size}) async{final recorder=ui.PictureRecorder();final canvas=Canvas(recorder);canvas.drawRect(Offset.zero&size,Paint()..color=template.primaryColor);final p=ui.ParagraphBuilder(ui.ParagraphStyle(textAlign:TextAlign.center,fontSize:size.width*.09,maxLines:2));p.pushStyle(ui.TextStyle(color:template.secondaryColor,fontWeight:FontWeight.bold));p.addText(primaryText);p.pop();final paragraph=p.build();paragraph.layout(ui.ParagraphConstraints(width:size.width*.9));canvas.drawParagraph(paragraph,Offset(size.width*.05,size.height*.38));final s=ui.ParagraphBuilder(ui.ParagraphStyle(textAlign:TextAlign.center,fontSize:size.width*.045,maxLines:2));s.pushStyle(ui.TextStyle(color:template.secondaryColor));s.addText(secondaryText);s.pop();final secondary=s.build();secondary.layout(ui.ParagraphConstraints(width:size.width*.9));canvas.drawParagraph(secondary,Offset(size.width*.05,size.height*.53));return recorder.endRecording().toImage(size.width.toInt(),size.height.toInt());}
 Future<Uint8List> imageToBytes(ui.Image image) async{final data=await image.toByteData(format:ui.ImageByteFormat.png);return data?.buffer.asUint8List()??Uint8List(0);}
 Widget buildTemplateWidget({required TemplateModel template,required String primaryText,required String secondaryText,double width=400,double height=400})=>FutureBuilder<ui.Image>(future:generateImageFromTemplate(template:template,primaryText:primaryText,secondaryText:secondaryText,size:Size(width,height)),builder:(context,snapshot)=>snapshot.hasData?RawImage(image:snapshot.data,width:width,height:height,fit:BoxFit.contain):SizedBox(width:width,height:height,child:const Center(child:CircularProgressIndicator())));
}
