import 'dart:convert';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:sehatak/core/models/payment/wallet_models.dart';
class WalletCacheService {
 static const _walletKey='cached_wallet',_transactionsKey='cached_transactions',_timestampKey='wallet_timestamp'; static const _cacheDuration=Duration(hours:1); SharedPreferences? _prefs; bool _isInitialized=false;
 Future<void> init() async{if(!_isInitialized){_prefs=await SharedPreferences.getInstance();_isInitialized=true;}}
 Future<void> saveWallet(WalletModel w) async{try{await init();final p=_prefs;if(p==null)return;await p.setString(_walletKey,jsonEncode({'userId':w.userId,'balance':w.balance,'pendingBalance':w.pendingBalance,'totalDeposited':w.totalDeposited,'totalWithdrawn':w.totalWithdrawn,'totalSpent':w.totalSpent,'currency':w.currency,'isActive':w.isActive,'createdAt':w.createdAt.toIso8601String(),'updatedAt':w.updatedAt.toIso8601String(),'lastTransactionAt':w.lastTransactionAt?.toIso8601String()}));await p.setInt(_timestampKey,DateTime.now().millisecondsSinceEpoch);}catch(e){print('❌ Failed to save wallet cache: $e');}}
 Future<WalletModel?> getWallet() async{try{await init();final s=_prefs?.getString(_walletKey);if(s==null)return null;final d=jsonDecode(s);return WalletModel(userId:d['userId'],balance:(d['balance'] as num).toDouble(),pendingBalance:(d['pendingBalance'] as num).toDouble(),totalDeposited:(d['totalDeposited'] as num).toDouble(),totalWithdrawn:(d['totalWithdrawn'] as num).toDouble(),totalSpent:(d['totalSpent'] as num).toDouble(),currency:d['currency']??'YER',isActive:d['isActive']??true,createdAt:DateTime.parse(d['createdAt']),updatedAt:DateTime.parse(d['updatedAt']),lastTransactionAt:d['lastTransactionAt']==null?null:DateTime.parse(d['lastTransactionAt']));}catch(e){print('❌ Failed to get wallet cache: $e');return null;}}
 Future<void> saveTransactions(List<TransactionModel> ts) async{try{await init();await _prefs?.setStringList(_transactionsKey,ts.map((t)=>jsonEncode({'id':t.id,'userId':t.userId,'amount':t.amount,'fee':t.fee,'netAmount':t.netAmount,'type':t.type.name,'status':t.status.name,'paymentMethod':t.paymentMethod?.name,'title':t.title,'description':t.description,'referenceNumber':t.referenceNumber,'walletName':t.walletName,'orderId':t.orderId,'serviceId':t.serviceId,'serviceType':t.serviceType,'metadata':t.metadata,'createdAt':t.createdAt.toIso8601String(),'completedAt':t.completedAt?.toIso8601String()})).toList());}catch(e){print('❌ Failed to save transactions cache: $e');}}
 Future<List<TransactionModel>> getTransactions() async{try{await init();final list=_prefs?.getStringList(_transactionsKey)??const <String>[];return list.map((s){try{final d=jsonDecode(s);return TransactionModel(id:d['id'],userId:d['userId'],amount:(d['amount'] as num).toDouble(),fee:(d['fee'] as num).toDouble(),netAmount:(d['netAmount'] as num).toDouble(),type:TransactionType.values.firstWhere((e)=>e.name==d['type'],orElse:()=>TransactionType.payment),status:TransactionStatus.values.firstWhere((e)=>e.name==d['status'],orElse:()=>TransactionStatus.pending),paymentMethod:d['paymentMethod']==null?null:PaymentMethodType.values.firstWhere((e)=>e.name==d['paymentMethod'],orElse:()=>PaymentMethodType.wallet),title:d['title'],description:d['description'],referenceNumber:d['referenceNumber'],walletName:d['walletName'],orderId:d['orderId'],serviceId:d['serviceId'],serviceType:d['serviceType'],metadata:d['metadata'],createdAt:DateTime.parse(d['createdAt']),completedAt:d['completedAt']==null?null:DateTime.parse(d['completedAt']));}catch(_){return null;}}).whereType<TransactionModel>().toList();}catch(e){print('❌ Failed to get transactions cache: $e');return [];}}
 Future<bool> isCacheValid() async{await init();final t=_prefs?.getInt(_timestampKey);return t!=null&&DateTime.now().difference(DateTime.fromMillisecondsSinceEpoch(t))<_cacheDuration;}
 Future<void> clearCache() async{await init();await _prefs?.remove(_walletKey);await _prefs?.remove(_transactionsKey);await _prefs?.remove(_timestampKey);}
 Future<bool> hasCachedData() async{await init();return _prefs?.containsKey(_walletKey)??false;}
}
