import 'package:flutter/material.dart';
import 'package:sehatak/presentation/widgets/common/app_image.dart';
class QuickServiceItem { final String icon,label; final Color color; final Widget screen; final String? badge; QuickServiceItem({required this.icon,required this.label,required this.color,required this.screen,this.badge}); }
class QuickServices extends StatelessWidget {
  final List<QuickServiceItem> services; final double height,itemWidth,iconSize; final EdgeInsets padding; final bool showLabels,isScrollable;
  const QuickServices({super.key,required this.services,this.height=90,this.itemWidth=70,this.iconSize=32,this.padding=const EdgeInsets.symmetric(horizontal:0),this.showLabels=true,this.isScrollable=true});
  @override Widget build(BuildContext context) { final dark=Theme.of(context).brightness==Brightness.dark; if(!isScrollable)return GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:4,childAspectRatio:1,crossAxisSpacing:8,mainAxisSpacing:8),itemCount:services.length,itemBuilder:(_,i)=>_item(context,services[i],dark)); return SizedBox(height:height,child:ListView.builder(scrollDirection:Axis.horizontal,itemCount:services.length,padding:padding,itemBuilder:(_,i)=>_item(context,services[i],dark))); }
  Widget _item(BuildContext context,QuickServiceItem s,bool dark)=>GestureDetector(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>s.screen)),child:SizedBox(width:itemWidth,child:Column(children:[Stack(children:[Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:s.color.withOpacity(.1),borderRadius:BorderRadius.circular(16)),child:AppImage(imageUrl:s.icon,width:iconSize,height:iconSize,fit:BoxFit.contain)),if(s.badge!=null)Positioned(top:0,right:0,child:Container(padding:const EdgeInsets.symmetric(horizontal:4,vertical:2),decoration:BoxDecoration(color:Colors.red,borderRadius:BorderRadius.circular(8)),child:Text(s.badge!,style:const TextStyle(color:Colors.white,fontSize:7))))]),if(showLabels) ...[const SizedBox(height:6),Text(s.label,maxLines:2,overflow:TextOverflow.ellipsis,textAlign:TextAlign.center,style:TextStyle(fontSize:10,color:dark?Colors.white:Colors.black87))]])));
}
class NetworkQuickServices extends StatelessWidget { final List<QuickServiceItem> services; const NetworkQuickServices({super.key,required this.services}); @override Widget build(BuildContext context)=>QuickServices(services:services); }
class GridQuickServices extends StatelessWidget { final List<QuickServiceItem> services; final int crossAxisCount; const GridQuickServices({super.key,required this.services,this.crossAxisCount=4}); @override Widget build(BuildContext context)=>QuickServices(services:services,isScrollable:false); }
class AnimatedQuickServices extends StatelessWidget { final List<QuickServiceItem> services; const AnimatedQuickServices({super.key,required this.services}); @override Widget build(BuildContext context)=>TweenAnimationBuilder<double>(tween:Tween(begin:0,end:1),duration:const Duration(milliseconds:600),builder:(context,value,child)=>Opacity(opacity:value,child:Transform.translate(offset:Offset(0,20*(1-value)),child:child)),child:QuickServices(services:services)); }
