import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:sehatak/bloc/eye/eye_bloc.dart';
import 'package:sehatak/bloc/eye/eye_event.dart';
import 'package:sehatak/bloc/eye/eye_state.dart';
import 'package:sehatak/core/models/eye/eye_models.dart';
import 'package:sehatak/presentation/widgets/specialty/specialty_banner.dart';
import 'package:sehatak/presentation/widgets/specialty/quick_actions_grid.dart';
import 'package:sehatak/presentation/widgets/specialty/doctors_section.dart';
import 'package:sehatak/presentation/widgets/specialty/clinics_section.dart';
import 'package:sehatak/presentation/widgets/specialty/tips_section.dart';
import 'package:sehatak/presentation/widgets/specialty/hospitals_section.dart';
import 'package:sehatak/presentation/widgets/specialty/consultation_cta.dart';
import 'package:sehatak/app_router.dart';
const _eyeColor=Color(0xFF9C27B0); const _eyeIcon='assets/icons/services/ophthalmology.png';
class EyeHealthScreen extends StatelessWidget{const EyeHealthScreen({super.key});@override Widget build(BuildContext context)=>BlocProvider(create:(_)=>EyeBloc()..add(const EyeStarted()),child:const _EyeHealthView());}
class _EyeHealthView extends StatelessWidget{const _EyeHealthView();
 Widget _image(String? path,{double size=52}){if(path==null||path.isEmpty)return Container(width:size,height:size,color:_eyeColor.withOpacity(.08),child:const Icon(Icons.person,color:_eyeColor));final image=path.startsWith('http')?Image.network(path,width:size,height:size,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const Icon(Icons.person,color:_eyeColor)):Image.asset(path,width:size,height:size,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const Icon(Icons.person,color:_eyeColor));return ClipRRect(borderRadius:BorderRadius.circular(12),child:image);}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Row(children:[Image.asset(_eyeIcon,width:28,height:28,errorBuilder:(_,__,___)=>const Icon(Icons.visibility)),const SizedBox(width:8),const Text('صحة العين')])),body:BlocBuilder<EyeBloc,EyeState>(builder:(context,state){if(state.isLoading&&state.doctors.isEmpty)return const Center(child:CircularProgressIndicator());return RefreshIndicator(onRefresh:()async{context.read<EyeBloc>().add(const EyeRefreshed());await Future<void>.delayed(const Duration(milliseconds:300));},child:ListView(padding:const EdgeInsets.all(16),children:[SpecialtyBanner(title:'صحة العين',subtitle:'أطباء، عيادات، نصائح ووقاية للأسرة',iconPath:_eyeIcon,accentColor:_eyeColor),const SizedBox(height:18),QuickActionsGrid(accentColor:_eyeColor,actions:[SpecialtyQuickAction(title:'حجز موعد',icon:Icons.calendar_month,onTap:()=>context.push(AppRouter.eyeDoctors)),SpecialtyQuickAction(title:'استشارة',icon:Icons.question_answer,onTap:()=>context.push(AppRouter.eyeConsultation)),SpecialtyQuickAction(title:'طوارئ',icon:Icons.local_hospital,onTap:()=>context.push(AppRouter.eyeHospitals))]),const SizedBox(height:22),DoctorsSection(accentColor:_eyeColor,doctors:state.doctors.take(6).map((d)=>_doctorCard(context,d)).toList(),onSeeAll:()=>context.push(AppRouter.eyeDoctors)),const SizedBox(height:20),ClinicsSection(accentColor:_eyeColor,clinics:state.clinics.take(4).map((d)=>_clinicCard(context,d)).toList(),onSeeAll:()=>context.push(AppRouter.eyeClinics)),const SizedBox(height:20),TipsSection(accentColor:_eyeColor,tips:state.tips.take(6).map(_tipCard).toList(),onSeeAll:()=>context.push(AppRouter.eyeTips)),const SizedBox(height:20),HospitalsSection(accentColor:_eyeColor,hospitals:state.hospitals.take(3).map(_hospitalCard).toList(),onSeeAll:()=>context.push(AppRouter.eyeHospitals)),const SizedBox(height:20),ConsultationCta(accentColor:_eyeColor,onPressed:()=>context.push(AppRouter.eyeConsultation)),if(state.errorMessage!=null)Padding(padding:const EdgeInsets.only(top:12),child:Text(state.errorMessage!,style:TextStyle(color:Colors.red[700]))) ]));});}
 Widget _doctorCard(BuildContext c,EyeDoctor d)=>Card(child:InkWell(onTap:()=>c.push(AppRouter.eyeDoctorDetail.replaceFirst(':id',d.id)),child:Padding(padding:const EdgeInsets.all(10),child:Column(children:[_image(d.photoUrl),const SizedBox(height:7),Text(d.name,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w800)),Text(d.specialty,style:const TextStyle(fontSize:11,color:_eyeColor)),Text('★ ${d.rating.toStringAsFixed(1)}',style:const TextStyle(color:Colors.amber))]))));
 Widget _clinicCard(BuildContext c,EyeClinic d)=>Card(child:ListTile(onTap:()=>c.push(AppRouter.eyeClinicDetail.replaceFirst(':id',d.id)),leading:Container(width:48,height:48,padding:const EdgeInsets.all(8),decoration:BoxDecoration(color:_eyeColor.withOpacity(.1),borderRadius:BorderRadius.circular(12)),child:Image.asset(_eyeIcon,errorBuilder:(_,__,___)=>const Icon(Icons.local_hospital,color:_eyeColor))),title:Text(d.name,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text(d.address,maxLines:1,overflow:TextOverflow.ellipsis),trailing:Text(d.isOpen?'مفتوح':'مغلق',style:TextStyle(color:d.isOpen?Colors.green:Colors.red,fontWeight:FontWeight.w700))));
 Widget _tipCard(EyeTip d)=>Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Icon(Icons.lightbulb_outline,color:_eyeColor),const SizedBox(height:7),Text(d.title,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:5),Text(d.body,maxLines:3,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:11))])));
 Widget _hospitalCard(EyeHospital d)=>Card(child:ListTile(leading:Icon(d.emergency?Icons.emergency:Icons.local_hospital,color:d.emergency?Colors.red:_eyeColor),title:Text(d.name,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text(d.address,maxLines:1,overflow:TextOverflow.ellipsis),trailing:d.emergency?const Text('طوارئ',style:TextStyle(color:Colors.red,fontWeight:FontWeight.w700)):null));
}
