import 'package:flutter/material.dart';
import 'package:sehatak/core/constants/app_colors.dart';
import 'package:sehatak/core/services/unified_cart_service.dart';
class DrugDetailsScreen extends StatelessWidget{
 final Map<String,dynamic> drug; const DrugDetailsScreen({super.key,required this.drug});
 String _text(String k){final v=drug[k];return v==null||v.toString().trim().isEmpty?'غير متوفر':v.toString();}
 @override Widget build(BuildContext context){final dark=Theme.of(context).brightness==Brightness.dark;final alternatives=drug['alternatives'] is List?(drug['alternatives'] as List).map((e)=>e.toString()).where((e)=>e.isNotEmpty).toList():<String>[];final rx=drug['prescription']==true||drug['requiresPrescription']==true;return Scaffold(backgroundColor:dark?const Color(0xFF0B1121):const Color(0xFFF8FAFC),appBar:AppBar(title:Text(_text('name')),backgroundColor:AppColors.primary,foregroundColor:Colors.white),body:SingleChildScrollView(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(height:150,width:double.infinity,decoration:BoxDecoration(color:dark?const Color(0xFF1A2540):Colors.grey[100],borderRadius:BorderRadius.circular(16)),child:const Center(child:Icon(Icons.medication,size:60,color:AppColors.primary))),const SizedBox(height:16),Row(children:[Expanded(child:Text(_text('name'),style:TextStyle(fontSize:22,fontWeight:FontWeight.bold,color:dark?Colors.white:Colors.black87))),if(drug['price']!=null)Text('${drug['price']} ر.ي',style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold,color:AppColors.primary))]),const SizedBox(height:8),Wrap(spacing:8,children:[if(_text('category')!='غير متوفر')_chip(_text('category'),AppColors.primary),if(rx)_chip('يحتاج وصفة',Colors.red)]),const SizedBox(height:16),const Divider(),_detail('الاستخدام',_text('usage'),dark),_detail('الآثار الجانبية',_text('sideEffects'),dark),_detail('التفاعلات',_text('interactions'),dark),_detail('الجرعة',_text('dosage'),dark),_detail('الشركة المصنعة',_text('manufacturer'),dark),_detail('تاريخ الانتهاء',_text('expiry'),dark),_detail('التخزين',_text('storage'),dark),if(alternatives.isNotEmpty)...[const SizedBox(height:18),const Text('بدائل الدواء',style:TextStyle(fontSize:16,fontWeight:FontWeight.bold)),const SizedBox(height:8),Wrap(spacing:8,children:alternatives.map((a)=>_chip(a,AppColors.primary)).toList())],const SizedBox(height:24),SizedBox(width:double.infinity,child:ElevatedButton.icon(onPressed:_canAdd()?(){UnifiedCartService.instance.add(productId:(drug['id']??drug['productId']??drug['name']).toString(),name:_text('name'),unitPrice:(drug['price'] as num?)?.toDouble()??0,requiresPrescription:rx);ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تمت إضافة الدواء إلى السلة')));}:null,icon:const Icon(Icons.add_shopping_cart),label:const Text('إضافة إلى السلة'),style:ElevatedButton.styleFrom(backgroundColor:AppColors.primary,foregroundColor:Colors.white)))])));}
 bool _canAdd()=>drug['name']!=null&&drug['price'] is num&&drug['inStock']!=false;
 Widget _chip(String t,Color c)=>Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:6),decoration:BoxDecoration(color:c.withOpacity(.1),borderRadius:BorderRadius.circular(20)),child:Text(t,style:TextStyle(fontSize:12,color:c,fontWeight:FontWeight.w600)));
 Widget _detail(String l,String v,bool dark)=>Padding(padding:const EdgeInsets.symmetric(vertical:6),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[SizedBox(width:105,child:Text(l,style:TextStyle(fontSize:13,fontWeight:FontWeight.w600,color:dark?Colors.grey[400]:Colors.grey[600]))),Expanded(child:Text(v,style:TextStyle(fontSize:13,color:dark?Colors.white:Colors.black87,height:1.5)))]));
}