import 'package:sehatak/presentation/widgets/common/custom_app_bar.dart';
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:sehatak/core/constants/app_colors.dart';
import 'package:sehatak/core/models/order_model.dart';
import 'package:sehatak/core/services/order_service.dart';
import 'package:sehatak/presentation/screens/orders/order_details_screen.dart';

class OrdersScreen extends StatefulWidget { final bool isProvider; const OrdersScreen({super.key, this.isProvider=false}); @override State<OrdersScreen> createState()=>_OrdersScreenState(); }
class _OrdersScreenState extends State<OrdersScreen>{String _selectedFilter='الكل';bool _isLoading=true;List<OrderModel> _orders=[];final _filters=['الكل','قيد المعالجة','مؤكد','جاري التحضير','جاهز','جاري التوصيل','تم التوصيل','ملغي'];
 @override void initState(){super.initState();_loadOrders();}
 Future<void> _loadOrders()async{final user=FirebaseAuth.instance.currentUser;if(user==null){if(mounted)setState(()=>_isLoading=false);return;}setState(()=>_isLoading=true);try{final orders=widget.isProvider?await OrderService.getProviderOrders(user.uid):await OrderService.getUserOrders(user.uid);if(!mounted)return;setState((){_orders=orders;_isLoading=false;});}catch(_){if(mounted)setState(()=>_isLoading=false);}}
 List<OrderModel> get _filteredOrders=>_selectedFilter=='الكل'?_orders:_orders.where((o)=>o.statusText==_selectedFilter).toList();
 @override Widget build(BuildContext context){final dark=Theme.of(context).brightness==Brightness.dark;return Scaffold(backgroundColor:dark?const Color(0xFF0B1121):const Color(0xFFF8FAFC),appBar:CustomAppBar(title:Text(widget.isProvider?'طلبات العملاء':'طلباتي'),backgroundColor:AppColors.primary,foregroundColor:Colors.white,elevation:0,actions:[IconButton(icon:const Icon(Icons.refresh),onPressed:_loadOrders)]),body:Column(children:[Container(padding:const EdgeInsets.all(16),child:SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:_filters.map((filter){final selected=_selectedFilter==filter;return GestureDetector(onTap:()=>setState(()=>_selectedFilter=filter),child:Container(padding:const EdgeInsets.symmetric(horizontal:16,vertical:6),margin:const EdgeInsets.only(right:8),decoration:BoxDecoration(color:selected?AppColors.primary:Colors.transparent,borderRadius:BorderRadius.circular(20),border:Border.all(color:selected?Colors.transparent:Colors.grey)),child:Text(filter,style:TextStyle(color:selected?Colors.white:Colors.grey,fontWeight:selected?FontWeight.bold:FontWeight.normal)));}).toList()))),Expanded(child:_isLoading?const Center(child:CircularProgressIndicator()):_filteredOrders.isEmpty?Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(Icons.shopping_bag_outlined,size:64,color:dark?Colors.grey[600]:Colors.grey[300]),const SizedBox(height:16),Text('لا توجد طلبات',style:TextStyle(fontSize:16,color:dark?Colors.grey[400]:Colors.grey[600])),const SizedBox(height:8),Text('ستظهر طلباتك هنا',style:TextStyle(fontSize:12,color:dark?Colors.grey[500]:Colors.grey[400]))])):ListView.builder(padding:const EdgeInsets.all(16),itemCount:_filteredOrders.length,itemBuilder:(context,index)=>_buildOrderCard(_filteredOrders[index]))) ]));}
 Widget _buildOrderCard(OrderModel order){final dark=Theme.of(context).brightness==Brightness.dark;const typeColor=AppColors.primary;return GestureDetector(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>OrderDetailsScreen(orderId:order.id)),),child:Container(margin:const EdgeInsets.only(bottom:12),padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:dark?const Color(0xFF1A2540):Colors.white,borderRadius:BorderRadius.circular(16),boxShadow:[BoxShadow(color:Colors.black.withOpacity(.04),blurRadius:4)],border:Border.all(color:order.statusColor.withOpacity(.3),width:order.status==OrderStatus.pending?2:1)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Container(padding:const EdgeInsets.all(8),decoration:BoxDecoration(color:typeColor.withOpacity(.1),shape:BoxShape.circle),child:Icon(order.typeIcon,color:typeColor,size:20)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(order.id.length>8?'طلب #${order.id.substring(0,8)}':'طلب #${order.id}',style:const TextStyle(fontWeight:FontWeight.bold,fontSize:14)),Text(order.typeText,style:TextStyle(fontSize:12,color:dark?Colors.grey[400]:Colors.grey[600]))])),Container(padding:const EdgeInsets.symmetric(horizontal:8,vertical:4),decoration:BoxDecoration(color:order.statusColor.withOpacity(.1),borderRadius:BorderRadius.circular(8)),child:Row(children:[Icon(order.statusIcon,size:12,color:order.statusColor),const SizedBox(width:4),Text(order.statusText,style:TextStyle(fontSize:10,color:order.statusColor))]))]),const SizedBox(height:8),Text('${order.items.length} منتج - ${order.total.toStringAsFixed(0)} ريال',style:TextStyle(fontSize:13,color:dark?Colors.grey[300]:Colors.grey[700])),if(order.deliveryAddress!=null)Padding(padding:const EdgeInsets.only(top:4),child:Row(children:[const Icon(Icons.location_on,size:14,color:Colors.grey),const SizedBox(width:4),Expanded(child:Text(order.deliveryAddress!,style:TextStyle(fontSize:12,color:dark?Colors.grey[400]:Colors.grey[600])))])),const SizedBox(height:8),Text(_formatDate(order.createdAt),style:TextStyle(fontSize:11,color:dark?Colors.grey[500]:Colors.grey[400]))])));}
 String _formatDate(DateTime d)=>'${d.day}/${d.month}/${d.year} ${d.hour}:${d.minute.toString().padLeft(2,'0')}';
}
