import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:sehatak/core/constants/app_colors.dart';
import 'package:sehatak/core/services/toast_service.dart';
import 'package:sehatak/presentation/widgets/common/custom_app_bar.dart';

class PlatformDashboard extends StatefulWidget{const PlatformDashboard({super.key});@override State<PlatformDashboard> createState()=>_PlatformDashboardState();}
class _PlatformDashboardState extends State<PlatformDashboard>{
 final _functions=FirebaseFunctions.instanceFor(region:'us-central1');bool _loading=true,_isAdmin=false;String? _error;List<QueryDocumentSnapshot<Map<String,dynamic>>> _pending=[];
 static const _roles=<String,String>{'doctor':'طبيب','nurse':'ممرض','midwife':'قابلة وتوليد','physiotherapist':'أخصائي علاج طبيعي','pharmacist':'صيدلي','lab':'مختبر','paramedic':'مسعف','hospital':'مستشفى','clinic':'عيادة','medical_center':'مركز طبي','dentist':'طبيب أسنان','dental':'عيادة أسنان','ophthalmology':'طبيب عيون','eye_clinic':'مركز عيون','optometrist':'أخصائي بصريات','delivery':'موصل طلبات','service':'خدمي'};
 @override void initState(){super.initState();_load();}
 Future<void> _load() async{try{final u=FirebaseAuth.instance.currentUser;if(u==null)throw Exception('يجب تسجيل الدخول أولاً');final me=await FirebaseFirestore.instance.collection('users').doc(u.uid).get();final role=me.data()?['role']?.toString();if(role!='admin'&&role!='superAdmin')throw Exception('هذه الشاشة مخصصة للمشرفين');final s=await FirebaseFirestore.instance.collection('verification_requests').where('status',isEqualTo:'pending').get();if(mounted)setState((){_isAdmin=true;_loading=false;_pending=s.docs;});}catch(e){if(mounted)setState((){_error=e.toString().replaceFirst('Exception: ','');_loading=false;});}}
 Future<void> _review(String id,String decision) async{try{await _functions.httpsCallable('reviewVerificationRequest').call({'requestId':id,'decision':decision});if(mounted)ToastService.showSuccess(decision=='approve'?'تم توثيق الحساب بنجاح':'تم رفض طلب التوثيق');await _load();}catch(e){if(mounted)ToastService.showError(e.toString());}}
 Future<void> _open(String url) async{final u=Uri.tryParse(url);if(u!=null)await launchUrl(u,mode:LaunchMode.externalApplication);}
 Widget _docs(Map<String,dynamic> data){final docs=Map<String,dynamic>.from((data['documents'] as Map?)??{});return ExpansionTile(title:const Text('المستندات المرفوعة'),children:docs.entries.expand((e){final list=e.value is List?e.value as List:const [];return [Padding(padding:const EdgeInsets.symmetric(horizontal:16,vertical:4),child:Text(e.key,style:const TextStyle(fontWeight:FontWeight.bold))),...list.whereType<Map>().map((x)=>ListTile(dense:true,title:Text(x['name']?.toString()??'ملف'),trailing:IconButton(icon:const Icon(Icons.open_in_new),onPressed:()=>_open(x['url']?.toString()??''))))];}).toList());}
 @override Widget build(BuildContext context){final dark=Theme.of(context).brightness==Brightness.dark;Widget body;
 if(_loading)body=const Center(child:CircularProgressIndicator());else if(_error!=null||!_isAdmin)body=Center(child:Text(_error??'غير مصرح لك بالدخول'));else body=RefreshIndicator(onRefresh:_load,child:_pending.isEmpty?ListView(children:const[SizedBox(height:180),Center(child:Text('لا توجد طلبات توثيق معلقة حالياً'))]):ListView.builder(padding:const EdgeInsets.all(16),itemCount:_pending.length,itemBuilder:(_,i){final d=_pending[i].data();final role=_roles[d['role']?.toString()]??'حساب مهني';final p=Map<String,dynamic>.from((d['profile'] as Map?)??{});return Card(margin:const EdgeInsets.only(bottom:12),child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text((d['name']??p['fullName']??'بدون اسم').toString(),style:const TextStyle(fontSize:17,fontWeight:FontWeight.bold)),Text(role),if((p['age']??'').toString().isNotEmpty)Text('العمر: '+p['age'].toString()),if((p['specialty']??d['specialty']??'').toString().isNotEmpty)Text('التخصص: '+(p['specialty']??d['specialty']).toString()),Text('الترخيص: '+(p['licenseNumber']??d['licenseNumber']??'').toString()),Text('الخبرة: '+(p['experience']??d['experience']??'').toString()),_docs(d),const SizedBox(height:8),Row(children:[Expanded(child:OutlinedButton(onPressed:()=>_review(d['requestId']?.toString()??_pending[i].id,'reject'),child:const Text('رفض'))),const SizedBox(width:10),Expanded(child:ElevatedButton(onPressed:()=>_review(d['requestId']?.toString()??_pending[i].id,'approve'),style:ElevatedButton.styleFrom(backgroundColor:AppColors.primary,foregroundColor:Colors.white),child:const Text('توثيق')))]),])));}));
 return Scaffold(backgroundColor:dark?const Color(0xFF0B1121):const Color(0xFFF8FAFC),appBar:CustomAppBar(title:'إدارة التوثيق',backgroundColor:AppColors.primary,foregroundColor:Colors.white,elevation:0),body:body);}
}
