import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:sehatak/core/constants/app_colors.dart';
import 'package:sehatak/core/services/toast_service.dart';
import 'package:sehatak/presentation/widgets/common/custom_app_bar.dart';

class PlatformDashboard extends StatefulWidget{const PlatformDashboard({super.key});@override State<PlatformDashboard> createState()=>_PlatformDashboardState();}
class _PlatformDashboardState extends State<PlatformDashboard>{
 final _functions=FirebaseFunctions.instanceFor(region:'us-central1');bool _loading=true,_isAdmin=false;String? _error;List<QueryDocumentSnapshot<Map<String,dynamic>>> _pending=[];
 static const _roles=<String,String>{'doctor':'طبيب','nurse':'ممرض','midwife':'قابلة وتوليد','physiotherapist':'أخصائي علاج طبيعي','pharmacist':'صيدلي','lab':'مختبر','paramedic':'مسعف','delivery':'موصل طلبات','service':'خدمي'};
 @override void initState(){super.initState();_load();}
 Future<void> _load() async{try{final u=FirebaseAuth.instance.currentUser;if(u==null)throw Exception('يجب تسجيل الدخول أولاً');final me=await FirebaseFirestore.instance.collection('users').doc(u.uid).get();if(me.data()?['role']!='admin')throw Exception('هذه الشاشة مخصصة للمشرف فقط');final s=await FirebaseFirestore.instance.collection('verification_requests').where('status',isEqualTo:'pending').get();if(mounted)setState((){_isAdmin=true;_loading=false;_pending=s.docs;});}catch(e){if(mounted)setState((){_error=e.toString().replaceFirst('Exception: ','');_loading=false;});}}
 Future<void> _review(String id,String decision) async{try{await _functions.httpsCallable('reviewVerificationRequest').call({'requestId':id,'decision':decision});if(mounted)ToastService.showSuccess(decision=='approve'?'تم اعتماد الحساب':'تم رفض طلب التوثيق');await _load();}catch(_){if(mounted)ToastService.showError('تعذر تنفيذ القرار');}}
 @override Widget build(BuildContext context){final dark=Theme.of(context).brightness==Brightness.dark;Widget body;
 if(_loading)body=const Center(child:CircularProgressIndicator());else if(_error!=null||!_isAdmin)body=Center(child:Text(_error??'غير مصرح لك بالدخول'));else body=RefreshIndicator(onRefresh:_load,child:_pending.isEmpty?ListView(children:const[SizedBox(height:180),Center(child:Text('لا توجد طلبات توثيق معلقة حالياً'))]):ListView.builder(padding:const EdgeInsets.all(16),itemCount:_pending.length,itemBuilder:(_,i){final d=_pending[i].data();final role=_roles[d['role']?.toString()]??'حساب مهني';final specialty=(d['specialty']??'').toString();final license=(d['licenseNumber']??'').toString();final experience=(d['experience']??'').toString();return Card(margin:const EdgeInsets.only(bottom:12),child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text((d['name']??'بدون اسم').toString(),style:const TextStyle(fontSize:17,fontWeight:FontWeight.bold)),const SizedBox(height:4),Text(role),if(specialty.isNotEmpty)Text('التخصص: '+specialty),if(license.isNotEmpty)Text('الترخيص: '+license),if(experience.isNotEmpty)Text('الخبرة: '+experience),const SizedBox(height:12),Row(children:[Expanded(child:OutlinedButton(onPressed:()=>_review((d['requestId']??_pending[i].id).toString(),'reject'),child:const Text('رفض'))),const SizedBox(width:10),Expanded(child:ElevatedButton(onPressed:()=>_review((d['requestId']??_pending[i].id).toString(),'approve'),style:ElevatedButton.styleFrom(backgroundColor:AppColors.primary,foregroundColor:Colors.white),child:const Text('اعتماد')))]),])));}) );
 return Scaffold(backgroundColor:dark?const Color(0xFF0B1121):const Color(0xFFF8FAFC),appBar:CustomAppBar(title:'إدارة التوثيق',backgroundColor:AppColors.primary,foregroundColor:Colors.white,elevation:0),body:body);
 }
}