import 'dart:async';
import 'dart:io';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:path_provider/path_provider.dart';
import 'package:record/record.dart';
import 'package:sehatak/core/constants/app_colors.dart';
import 'package:sehatak/core/services/chat_service.dart';
import 'package:sehatak/core/services/nextcloud_service.dart';
import 'package:sehatak/core/services/reliable_message_service.dart';
import 'package:sehatak/core/services/toast_service.dart';

class ChatInputBar extends StatefulWidget { final String chatId; final Function(String) onSendMessage; final Function(String)? onSendImage; final VoidCallback? onShareLocation; const ChatInputBar({super.key,required this.chatId,required this.onSendMessage,this.onSendImage,this.onShareLocation}); @override State<ChatInputBar> createState()=>_ChatInputBarState(); }
class _ChatInputBarState extends State<ChatInputBar>{
 final _controller=TextEditingController(),_focus=FocusNode(),_picker=ImagePicker(),_recorder=AudioRecorder(),_auth=FirebaseAuth.instance,_nextcloud=NextcloudService(),_chat=ChatService(); Timer? _timer; Duration _duration=Duration.zero; String? _recordPath; bool _recording=false,_paused=false,_sending=false,_attachments=false;
 bool get _hasText=>_controller.text.trim().isNotEmpty; bool get _hasRecording=>_recordPath!=null;
 @override void initState(){super.initState();_controller.addListener(_onTextChanged);} void _onTextChanged(){if(mounted)setState((){});} @override void dispose(){_timer?.cancel();_controller.dispose();_focus.dispose();_recorder.dispose();super.dispose();}
 Future<void> _sendText()async{final text=_controller.text.trim();if(text.isEmpty||_sending||_recording||_hasRecording)return;setState(()=>_sending=true);try{await ReliableMessageService.sendText(chatId:widget.chatId,text:text);widget.onSendMessage(text);_controller.clear();}catch(e){debugPrint('chat text send: $e');ToastService.showError('تعذر إرسال الرسالة. تحقق من الاتصال.');}finally{if(mounted)setState(()=>_sending=false);}}
 Future<String> _upload(File f,String folder)async{await _nextcloud.loadConfig();final r=await _nextcloud.uploadFile(file:f,path:'chats/${widget.chatId}/$folder');if(!r.success||r.url==null||r.url!.isEmpty)throw StateError(r.error??'Nextcloud upload failed');return r.url!;}
 Future<void> _sendMedia(File f,{required String type,required String folder,required String preview,String? name,String? size,String? mime})async{if(_sending||_auth.currentUser==null)return;setState((){_sending=true;_attachments=false;});try{final url=await _upload(f,folder);await _chat.sendMessage(chatId:widget.chatId,text:preview,imageUrl:type=='image'?url:null,videoUrl:type=='video'?url:null,fileUrl:type=='file'?url:null,fileName:name,fileSize:size,fileMimeType:mime);if(type=='image')widget.onSendImage?.call(url);}catch(e){debugPrint('chat media send: $e');ToastService.showError('تعذر إرسال الوسائط. تحقق من اتصال Nextcloud.');}finally{if(mounted)setState(()=>_sending=false);}}
 Future<void> _pickImage(ImageSource s)async{final x=await _picker.pickImage(source:s,imageQuality:90);if(x!=null)await _sendMedia(File(x.path),type:'image',folder:'images',preview:'📷 صورة');} Future<void> _pickVideo()async{final x=await _picker.pickVideo(source:ImageSource.gallery,maxDuration:const Duration(minutes:10));if(x!=null)await _sendMedia(File(x.path),type:'video',folder:'videos',preview:'🎬 فيديو');} Future<void> _pickFile()async{final r=await FilePicker.platform.pickFiles(withData:false);final f=r?.files.single;if(f?.path==null)return;await _sendMedia(File(f!.path!),type:'file',folder:'files',preview:'📎 ${f.name}',name:f.name,size:_formatBytes(f.size),mime:f.extension==null?null:'application/${f.extension}');}
 String _formatBytes(int b){if(b<1024)return '$b B';if(b<1048576)return '${(b/1024).toStringAsFixed(1)} KB';if(b<1073741824)return '${(b/1048576).toStringAsFixed(1)} MB';return '${(b/1073741824).toStringAsFixed(1)} GB';}
 Future<void> _startRecording()async{if(_sending||_recording||_hasRecording||_hasText)return;if(!await _recorder.hasPermission()){ToastService.showError('يلزم السماح بالوصول إلى الميكروفون.');return;}final dir=await getTemporaryDirectory();final p='${dir.path}/sehatak_chat_${DateTime.now().millisecondsSinceEpoch}.m4a';try{await _recorder.start(const RecordConfig(encoder:AudioEncoder.aacLc),path:p);_duration=Duration.zero;_timer?.cancel();_timer=Timer.periodic(const Duration(seconds:1),(_){if(mounted&&_recording&&!_paused)setState(()=>_duration+=const Duration(seconds:1));});setState((){_recording=true;_paused=false;_recordPath=p;});}catch(e){debugPrint('record start: $e');ToastService.showError('تعذر بدء التسجيل الصوتي.');}}
 Future<void> _stopRecording()async{if(!_recording)return;_timer?.cancel();try{await _recorder.stop();}catch(e){debugPrint('record stop: $e');}if(mounted)setState((){_recording=false;_paused=false;});}
 Future<void> _togglePause()async{if(!_recording)return;try{if(_paused)await _recorder.resume();else await _recorder.pause();if(mounted)setState(()=>_paused=!_paused);}catch(e){debugPrint('record pause/resume: $e');}}
 Future<void> _deleteRecording()async{_timer?.cancel();try{await _recorder.stop();}catch(_){}final p=_recordPath;_recordPath=null;if(p!=null){final f=File(p);if(await f.exists())await f.delete();}if(mounted)setState((){_recording=false;_paused=false;_duration=Duration.zero;});}
 Future<void> _sendRecording()async{if(_sending||_recordPath==null)return;if(_recording)await _stopRecording();final p=_recordPath;if(p==null)return;final f=File(p);if(!await f.exists()||await f.length()<1000){await _deleteRecording();ToastService.showError('التسجيل قصير جدًا.');return;}setState(()=>_sending=true);try{final url=await _upload(f,'audio');await _chat.sendMessage(chatId:widget.chatId,text:'🎤 رسالة صوتية',audioUrl:url,audioDuration:_duration.inSeconds.toString());_recordPath=null;_duration=Duration.zero;}catch(e){debugPrint('audio send: $e');ToastService.showError('تعذر إرسال التسجيل الصوتي.');}finally{if(_recordPath==null&&await f.exists())await f.delete();if(mounted)setState(()=>_sending=false);}}
 @override Widget build(BuildContext context){final dark=Theme.of(context).brightness==Brightness.dark;if(_recording||_hasRecording)return _voiceBar(dark);return Column(mainAxisSize:MainAxisSize.min,children:[if(_attachments)_mediaMenu(dark),Material(color:dark?const Color(0xFF121A29):Colors.white,child:SafeArea(top:false,child:Padding(padding:const EdgeInsets.fromLTRB(8,6,8,6),child:Row(crossAxisAlignment:CrossAxisAlignment.end,children:[IconButton(onPressed:_sending?null:()=>setState(()=>_attachments=!_attachments),icon:const Icon(Icons.add_circle_outline)),Expanded(child:Container(constraints:const BoxConstraints(minHeight:46,maxHeight:130),decoration:BoxDecoration(color:dark?const Color(0xFF26344D):const Color(0xFFF1F4F5),borderRadius:BorderRadius.circular(24)),child:TextField(controller:_controller,focusNode:_focus,minLines:1,maxLines:5,textDirection:TextDirection.rtl,keyboardType:TextInputType.multiline,decoration:const InputDecoration(hintText:'اكتب رسالة...',border:InputBorder.none,contentPadding:EdgeInsets.symmetric(horizontal:16,vertical:11))))),const SizedBox(width:5),GestureDetector(onTap:_hasText?_sendText:_startRecording,child:CircleAvatar(radius:23,backgroundColor:_sending?Colors.grey:AppColors.primary,child:Icon(_hasText?Icons.send_rounded:Icons.mic_rounded,color:Colors.white,size:21)))]))))]);}
 Widget _voiceBar(bool dark)=>Material(color:dark?const Color(0xFF121A29):Colors.white,child:SafeArea(top:false,child:Padding(padding:const EdgeInsets.all(6),child:Row(children:[IconButton(onPressed:_sending?null:_deleteRecording,icon:const Icon(Icons.delete_outline,color:Colors.red)),IconButton(onPressed:_sending||!_recording?null:_togglePause,icon:Icon(_paused?Icons.play_arrow:Icons.pause,color:AppColors.primary)),Expanded(child:Container(height:46,padding:const EdgeInsets.symmetric(horizontal:12),decoration:BoxDecoration(color:dark?const Color(0xFF26344D):const Color(0xFFF1F4F5),borderRadius:BorderRadius.circular(23)),child:Row(children:[Icon(_recording?Icons.mic:Icons.mic_none,color:_recording?Colors.red:AppColors.primary),const SizedBox(width:8),Text('${_duration.inMinutes.toString().padLeft(2,'0')}:${(_duration.inSeconds%60).toString().padLeft(2,'0')}'),const SizedBox(width:10),const Expanded(child:LinearProgressIndicator(minHeight:3))]))),IconButton(onPressed:_sending?null:(_recording?_stopRecording:_sendRecording),icon:Icon(_recording?Icons.stop_circle_outlined:Icons.send_rounded,color:AppColors.primary,size:29))]))));
 Widget _mediaMenu(bool dark)=>Container(padding:const EdgeInsets.all(10),color:dark?const Color(0xFF121A29):Colors.white,child:Row(mainAxisAlignment:MainAxisAlignment.spaceAround,children:[_mediaItem(Icons.camera_alt,'كاميرا',()=>_pickImage(ImageSource.camera)),_mediaItem(Icons.photo,'صورة',()=>_pickImage(ImageSource.gallery)),_mediaItem(Icons.video_library,'فيديو',_pickVideo),_mediaItem(Icons.attach_file,'ملف',_pickFile)])); Widget _mediaItem(IconData i,String l,VoidCallback a)=>InkWell(onTap:a,child:Padding(padding:const EdgeInsets.all(6),child:Column(children:[CircleAvatar(backgroundColor:AppColors.primary.withOpacity(.1),child:Icon(i,color:AppColors.primary)),const SizedBox(height:3),Text(l,style:const TextStyle(fontSize:10))])));
}
