import 'dart:async';
import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:path_provider/path_provider.dart';
import 'package:record/record.dart';
import 'package:sehatak/core/constants/app_colors.dart';
import 'package:sehatak/core/services/chat_service.dart';
import 'package:sehatak/core/services/nextcloud_service.dart';
import 'package:sehatak/core/services/reliable_message_service.dart';
import 'package:sehatak/core/services/toast_service.dart';

class ChatInputBar extends StatefulWidget { final String chatId; final Function(String) onSendMessage; final Function(String)? onSendImage; final VoidCallback? onShareLocation; const ChatInputBar({super.key,required this.chatId,required this.onSendMessage,this.onSendImage,this.onShareLocation}); @override State<ChatInputBar> createState()=>_ChatInputBarState(); }
class _ChatInputBarState extends State<ChatInputBar>{
 final _controller=TextEditingController(),_focus=FocusNode(),_recorder=AudioRecorder(); final _picker=ImagePicker(),_auth=FirebaseAuth.instance,_nextcloud=NextcloudService(),_chat=ChatService(); Timer? _timer; Duration _duration=Duration.zero; String? _path; bool _recording=false,_sending=false,_attachments=false;
 bool get _hasText=>_controller.text.trim().isNotEmpty;
 @override void initState(){super.initState();_controller.addListener(_changed);} void _changed(){if(mounted)setState((){});} @override void dispose(){_timer?.cancel();_controller.dispose();_focus.dispose();_recorder.dispose();super.dispose();}
 Future<void> _sendText()async{final text=_controller.text.trim();if(text.isEmpty||_sending)return;setState(()=>_sending=true);try{await ReliableMessageService.sendText(chatId:widget.chatId,text:text);widget.onSendMessage(text);_controller.clear();}catch(e){debugPrint('send text: $e');ToastService.showError('تعذر إرسال الرسالة.');}finally{if(mounted)setState(()=>_sending=false);}}
 Future<String?> _upload(File f,String folder)async{try{await _nextcloud.loadConfig();final r=await _nextcloud.uploadFile(file:f,path:'chats/${widget.chatId}/$folder');if(!r.success){debugPrint('Nextcloud: ${r.error}');return null;}return r.url;}catch(e){debugPrint('Nextcloud upload: $e');return null;}}
 Future<void> _image(ImageSource s)async{final p=await _picker.pickImage(source:s,imageQuality:88);if(p!=null)await _sendMedia(File(p.path),'image','images','📷 صورة');}
 Future<void> _video()async{final p=await _picker.pickVideo(source:ImageSource.gallery,maxDuration:const Duration(minutes:10));if(p!=null)await _sendMedia(File(p.path),'video','videos','🎬 فيديو');}
 Future<void> _file()async{final r=await FilePicker.platform.pickFiles(withData:false);final f=r?.files.single;if(f?.path!=null)await _sendMedia(File(f!.path!),'file','files','📎 ${f.name}',fileName:f.name,fileSize:_bytes(f.size),fileMimeType:f.extension==null?null:'application/${f.extension}');}
 String _bytes(int n){if(n<1024)return '$n B';if(n<1024*1024)return '${(n/1024).toStringAsFixed(1)} KB';return '${(n/(1024*1024)).toStringAsFixed(1)} MB';}
 Future<void> _sendMedia(File f,String type,String folder,String label,{String? fileName,String? fileSize,String? fileMimeType})async{final u=_auth.currentUser;if(_sending||u==null)return;setState((){_sending=true;_attachments=false;});try{final url=await _upload(f,folder);if(url==null||url.isEmpty)throw StateError('nextcloud_upload_failed');await _writeMedia(u,type,label,url,fileName:fileName,fileSize:fileSize,fileMimeType:fileMimeType);if(type=='image')widget.onSendImage?.call(url);}catch(e){debugPrint('media send: $e');ToastService.showError('تعذر إرسال الوسائط. تحقق من اتصال Nextcloud.');}finally{if(mounted)setState(()=>_sending=false);}}
 Future<void> _writeMedia(User u,String type,String label,String url,{String? fileName,String? fileSize,String? fileMimeType})async{final chat=FirebaseFirestore.instance.collection('chats').doc(widget.chatId);final snap=await chat.get();if(!snap.exists)throw StateError('chat_not_found');final ids=List<String>.from(snap.data()?['participants']??const []);if(!ids.contains(u.uid))throw StateError('not_participant');final ref=chat.collection('messages').doc();final b=FirebaseFirestore.instance.batch();b.set(ref,{'chatId':widget.chatId,'senderId':u.uid,'senderName':u.displayName??'مستخدم','senderPhotoUrl':u.photoURL,'text':label,'type':type,'imageUrl':type=='image'?url:null,'videoUrl':type=='video'?url:null,'fileUrl':type=='file'?url:null,'fileName':fileName,'fileSize':fileSize,'fileMimeType':fileMimeType,'timestamp':FieldValue.serverTimestamp(),'isRead':false,'isDelivered':true,'deliveredAt':FieldValue.serverTimestamp(),'isDeleted':false,'isEdited':false,'reactions':<String,dynamic>{}});final update=<String,dynamic>{'lastMessage':label,'lastMessageTime':FieldValue.serverTimestamp(),'lastMessageSenderId':u.uid,'updatedAt':FieldValue.serverTimestamp()};for(final id in ids){if(id!=u.uid)update['unreadCount.$id']=FieldValue.increment(1);}b.update(chat,update);await b.commit();}
 Future<void> _startRecording()async{if(_recording||_sending||_hasText)return;if(!await _recorder.hasPermission()){ToastService.showError('يلزم السماح بالوصول إلى الميكروفون.');return;}final dir=await getTemporaryDirectory();final p='${dir.path}/chat_${DateTime.now().millisecondsSinceEpoch}.m4a';await _recorder.start(const RecordConfig(encoder:AudioEncoder.aacLc),path:p);_duration=Duration.zero;_timer=Timer.periodic(const Duration(seconds:1),(_){if(mounted)setState(()=>_duration+=const Duration(seconds:1));});setState((){_recording=true;_path=p;});}
 Future<void> _finishRecording({bool cancel=false})async{if(!_recording)return;_timer?.cancel();final p=_path;_path=null;await _recorder.stop();if(mounted)setState(()=>_recording=false);if(p==null)return;final f=File(p);if(cancel){if(await f.exists())await f.delete();return;}if(!await f.exists()||await f.length()<1000){if(await f.exists())await f.delete();ToastService.showError('التسجيل قصير جدًا.');return;}setState(()=>_sending=true);try{final url=await _upload(f,'audio');if(url==null)throw StateError('audio_upload_failed');await _chat.sendMessage(chatId:widget.chatId,text:'🎵 رسالة صوتية',audioUrl:url);}catch(e){debugPrint('audio send: $e');ToastService.showError('تعذر إرسال التسجيل الصوتي.');}finally{if(await f.exists())await f.delete();if(mounted)setState(()=>_sending=false);}}
 @override Widget build(BuildContext context){final dark=Theme.of(context).brightness==Brightness.dark;if(_recording)return _recordingBar(dark);return Column(mainAxisSize:MainAxisSize.min,children:[if(_attachments)_menu(dark),Material(color:dark?const Color(0xFF121A29):Colors.white,child:SafeArea(top:false,child:Padding(padding:const EdgeInsets.fromLTRB(8,6,8,6),child:Row(crossAxisAlignment:CrossAxisAlignment.end,children:[IconButton(onPressed:()=>setState(()=>_attachments=!_attachments),icon:const Icon(Icons.add_circle_outline)),Expanded(child:Container(constraints:const BoxConstraints(minHeight:46,maxHeight:130),decoration:BoxDecoration(color:dark?const Color(0xFF26344D):const Color(0xFFF1F4F5),borderRadius:BorderRadius.circular(24)),child:TextField(controller:_controller,focusNode:_focus,minLines:1,maxLines:5,textDirection:TextDirection.rtl,keyboardType:TextInputType.multiline,decoration:const InputDecoration(hintText:'اكتب رسالة...',border:InputBorder.none,contentPadding:EdgeInsets.symmetric(horizontal:16,vertical:11)))),const SizedBox(width:5),GestureDetector(onTap:_hasText?_sendText:null,onLongPress:_hasText?null:_startRecording,onLongPressUp:_hasText?null:_finishRecording,child:AnimatedSwitcher(duration:const Duration(milliseconds:180),child:CircleAvatar(key:ValueKey(_hasText),radius:23,backgroundColor:AppColors.primary,child:Icon(_hasText?Icons.send_rounded:Icons.mic_rounded,color:Colors.white,size:21))))]))))]);}
 Widget _recordingBar(bool dark)=>Material(color:dark?const Color(0xFF121A29):Colors.white,child:SafeArea(top:false,child:Padding(padding:const EdgeInsets.fromLTRB(8,6,8,6),child:Row(children:[IconButton(onPressed:()=>_finishRecording(cancel:true),icon:const Icon(Icons.delete_outline,color:Colors.red)),Expanded(child:Container(height:46,padding:const EdgeInsets.symmetric(horizontal:14),decoration:BoxDecoration(color:dark?const Color(0xFF26344D):const Color(0xFFF1F4F5),borderRadius:BorderRadius.circular(23)),child:Row(children:[const Icon(Icons.mic,color:Colors.red),const SizedBox(width:8),Text('${_duration.inMinutes.toString().padLeft(2,'0')}:${(_duration.inSeconds%60).toString().padLeft(2,'0')}'),const SizedBox(width:10),const Expanded(child:LinearProgressIndicator(minHeight:3))]))),const SizedBox(width:6),IconButton(onPressed:_sending?null:_finishRecording,icon:const Icon(Icons.send_rounded,color:AppColors.primary,size:28))])));
 Widget _menu(bool dark)=>Container(padding:const EdgeInsets.all(10),color:dark?const Color(0xFF121A29):Colors.white,child:Row(mainAxisAlignment:MainAxisAlignment.spaceAround,children:[_item(Icons.camera_alt,'كاميرا',()=>_image(ImageSource.camera)),_item(Icons.photo,'صورة',()=>_image(ImageSource.gallery)),_item(Icons.video_library,'فيديو',_video),_item(Icons.attach_file,'ملف',_file)]));
 Widget _item(IconData i,String t,VoidCallback f)=>InkWell(onTap:f,child:Padding(padding:const EdgeInsets.all(6),child:Column(children:[CircleAvatar(backgroundColor:AppColors.primary.withOpacity(.1),child:Icon(i,color:AppColors.primary)),const SizedBox(height:3),Text(t,style:const TextStyle(fontSize:10))])));
}
