import 'dart:async';
import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:path_provider/path_provider.dart';
import 'package:record/record.dart';
import 'package:sehatak/core/constants/app_colors.dart';
import 'package:sehatak/core/services/chat_service.dart';
import 'package:sehatak/core/services/nextcloud_service.dart';
import 'package:sehatak/core/services/reliable_message_service.dart';
import 'package:sehatak/core/services/toast_service.dart';
class ChatInputBar extends StatefulWidget{final String chatId;final Function(String) onSendMessage;final Function(String)? onSendImage;final VoidCallback? onShareLocation;const ChatInputBar({super.key,required this.chatId,required this.onSendMessage,this.onSendImage,this.onShareLocation});@override State<ChatInputBar> createState()=>_ChatInputBarState();}
class _ChatInputBarState extends State<ChatInputBar>{final c=TextEditingController(),f=FocusNode();final p=ImagePicker(),r=AudioRecorder(),auth=FirebaseAuth.instance,n=NextcloudService(),chat=ChatService();Timer? timer;Duration d=Duration.zero;String? path;bool recording=false,sending=false,menu=false;bool get hasText=>c.text.trim().isNotEmpty;@override void initState(){super.initState();c.addListener(()=>mounted?setState((){}):null);}@override void dispose(){timer?.cancel();c.dispose();f.dispose();r.dispose();super.dispose();}
Future<void> textSend()async{final t=c.text.trim();if(t.isEmpty||sending)return;setState(()=>sending=true);try{await ReliableMessageService.sendText(chatId:widget.chatId,text:t);widget.onSendMessage(t);c.clear();}catch(e){ToastService.showError('تعذر إرسال الرسالة.');debugPrint('$e');}finally{if(mounted)setState(()=>sending=false);}}
Future<String?> upload(File file,String folder)async{try{await n.loadConfig();final x=await n.uploadFile(file:file,path:'chats/${widget.chatId}/$folder');if(!x.success)throw StateError(x.error??'upload failed');return x.url;}catch(e){debugPrint('Nextcloud upload: $e');return null;}}
Future<void> image(ImageSource s)async{final x=await p.pickImage(source:s,imageQuality:88);if(x!=null)await media(File(x.path),'image','images','📷 صورة');}
Future<void> video()async{final x=await p.pickVideo(source:ImageSource.gallery,maxDuration:const Duration(minutes:10));if(x!=null)await media(File(x.path),'video','videos','🎬 فيديو');}
Future<void> file()async{final x=await FilePicker.platform.pickFiles(withData:false);final q=x?.files.single;if(q?.path!=null)await media(File(q!.path!),'file','files','📎 ${q.name}',name:q.name,size:q.size.toString(),mime:q.extension==null?null:'application/${q.extension}');}
Future<void> media(File file,String type,String folder,String label,{String? name,String? size,String? mime})async{final u=auth.currentUser;if(u==null||sending)return;setState((){sending=true;menu=false;});try{final url=await upload(file,folder);if(url==null)throw StateError('upload failed');final chatRef=FirebaseFirestore.instance.collection('chats').doc(widget.chatId);final snap=await chatRef.get();final ids=List<String>.from(snap.data()?['participants']??const[]);final ref=chatRef.collection('messages').doc();final b=FirebaseFirestore.instance.batch();b.set(ref,{'chatId':widget.chatId,'senderId':u.uid,'senderName':u.displayName??'مستخدم','senderPhotoUrl':u.photoURL,'text':label,'type':type,'imageUrl':type=='image'?url:null,'videoUrl':type=='video'?url:null,'fileUrl':type=='file'?url:null,'fileName':name,'fileSize':size,'fileMimeType':mime,'timestamp':FieldValue.serverTimestamp(),'isRead':false,'isDelivered':true,'deliveredAt':FieldValue.serverTimestamp(),'isDeleted':false,'isEdited':false,'reactions':<String,dynamic>{}});final update=<String,dynamic>{'lastMessage':label,'lastMessageTime':FieldValue.serverTimestamp(),'lastMessageSenderId':u.uid,'updatedAt':FieldValue.serverTimestamp()};for(final id in ids){if(id!=u.uid)update['unreadCount.$id']=FieldValue.increment(1);}b.update(chatRef,update);await b.commit();if(type=='image')widget.onSendImage?.call(url);}catch(e){ToastService.showError('تعذر إرسال الوسائط. تحقق من Nextcloud.');debugPrint('$e');}finally{if(mounted)setState(()=>sending=false);}}
Future<void> start()async{if(recording||sending||hasText)return;if(!await r.hasPermission()){ToastService.showError('يلزم السماح بالوصول إلى الميكروفون.');return;}final dir=await getTemporaryDirectory();final x='${dir.path}/chat_${DateTime.now().millisecondsSinceEpoch}.m4a';await r.start(const RecordConfig(encoder:AudioEncoder.aacLc),path:x);d=Duration.zero;timer=Timer.periodic(const Duration(seconds:1),(_){if(mounted)setState(()=>d+=const Duration(seconds:1));});setState((){recording=true;path=x;});}
Future<void> sendAudio()async{if(!recording||sending)return;timer?.cancel();final x=path;path=null;await r.stop();if(mounted)setState(()=>recording=false);if(x==null)return;final file=File(x);try{if(!await file.exists()||await file.length()<1000)throw StateError('short');final url=await upload(file,'audio');if(url==null)throw StateError('upload');await chat.sendMessage(chatId:widget.chatId,text:'🎵 رسالة صوتية',audioUrl:url);}catch(e){ToastService.showError(e.toString().contains('short')?'التسجيل قصير جدًا.':'تعذر إرسال التسجيل الصوتي.');}finally{if(await file.exists())await file.delete();}}
Future<void> cancelAudio()async{timer?.cancel();final x=path;path=null;await r.stop();if(x!=null){final file=File(x);if(await file.exists())await file.delete();}if(mounted)setState(()=>recording=false);}
@override Widget build(BuildContext context){final dark=Theme.of(context).brightness==Brightness.dark;if(recording)return bar(dark);return Column(mainAxisSize:MainAxisSize.min,children:[if(menu)mediaMenu(dark),Material(color:dark?const Color(0xFF121A29):Colors.white,child:SafeArea(top:false,child:Padding(padding:const EdgeInsets.fromLTRB(8,6,8,6),child:Row(crossAxisAlignment:CrossAxisAlignment.end,children:[IconButton(onPressed:()=>setState(()=>menu=!menu),icon:const Icon(Icons.add_circle_outline)),Expanded(child:Container(constraints:const BoxConstraints(minHeight:46,maxHeight:130),decoration:BoxDecoration(color:dark?const Color(0xFF26344D):const Color(0xFFF1F4F5),borderRadius:BorderRadius.circular(24)),child:TextField(controller:c,focusNode:f,minLines:1,maxLines:5,textDirection:TextDirection.rtl,keyboardType:TextInputType.multiline,decoration:const InputDecoration(hintText:'اكتب رسالة...',border:InputBorder.none,contentPadding:EdgeInsets.symmetric(horizontal:16,vertical:11)))),const SizedBox(width:5),GestureDetector(onTap:hasText?textSend:start,child:CircleAvatar(radius:23,backgroundColor:AppColors.primary,child:Icon(hasText?Icons.send_rounded:Icons.mic_rounded,color:Colors.white,size:21)))]))))]);}
Widget bar(bool dark)=>Material(color:dark?const Color(0xFF121A29):Colors.white,child:SafeArea(top:false,child:Padding(padding:const EdgeInsets.fromLTRB(8,6,8,6),child:Row(children:[IconButton(onPressed:cancelAudio,tooltip:'حذف',icon:const Icon(Icons.delete_outline,color:Colors.red)),Expanded(child:Container(height:46,padding:const EdgeInsets.symmetric(horizontal:14),decoration:BoxDecoration(color:dark?const Color(0xFF26344D):const Color(0xFFF1F4F5),borderRadius:BorderRadius.circular(23)),child:Row(children:[const Icon(Icons.mic,color:Colors.red),const SizedBox(width:8),Text('${d.inMinutes.toString().padLeft(2,'0')}:${(d.inSeconds%60).toString().padLeft(2,'0')}'),const SizedBox(width:10),const Expanded(child:LinearProgressIndicator(minHeight:3))]))),IconButton(onPressed:sendAudio,tooltip:'إرسال التسجيل',icon:const Icon(Icons.send_rounded,color:AppColors.primary,size:28))])));
Widget mediaMenu(bool dark)=>Container(padding:const EdgeInsets.all(10),color:dark?const Color(0xFF121A29):Colors.white,child:Row(mainAxisAlignment:MainAxisAlignment.spaceAround,children:[item(Icons.camera_alt,'كاميرا',()=>image(ImageSource.camera)),item(Icons.photo,'صورة',()=>image(ImageSource.gallery)),item(Icons.video_library,'فيديو',video),item(Icons.attach_file,'ملف',file)]));Widget item(IconData i,String t,VoidCallback f)=>InkWell(onTap:f,child:Padding(padding:const EdgeInsets.all(6),child:Column(children:[CircleAvatar(backgroundColor:AppColors.primary.withOpacity(.1),child:Icon(i,color:AppColors.primary)),const SizedBox(height:3),Text(t,style:const TextStyle(fontSize:10))])));}
