import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

enum ReviewTarget { doctor, pharmacy, lab, hospital, delivery, service, product, order }
enum ReviewRating { one(1), two(2), three(3), four(4), five(5); final int value; const ReviewRating(this.value); static ReviewRating fromInt(int value) => ReviewRating.values.firstWhere((e) => e.value == value, orElse: () => ReviewRating.five); }

class ReviewModel {
  final String id, userId, userName, targetId, targetName;
  final String? userPhoto, comment, providerResponse, bookingId, orderId;
  final ReviewTarget target;
  final double rating;
  final List<String>? images, tags, likedBy, dislikedBy;
  final bool isVerified, isAnonymous;
  final int likes, dislikes;
  final Map<String, dynamic>? metadata;
  final DateTime createdAt;
  final DateTime? updatedAt, providerResponseAt;
  final List<Map<String, dynamic>>? replies;
  ReviewModel({required this.id, required this.userId, required this.userName, this.userPhoto, required this.target, required this.targetId, required this.targetName, required this.rating, this.comment, this.images, this.tags, this.isVerified = false, this.isAnonymous = false, this.likes = 0, this.dislikes = 0, this.likedBy, this.dislikedBy, this.metadata, required this.createdAt, this.updatedAt, this.bookingId, this.orderId, this.providerResponse, this.providerResponseAt, this.replies});
  String get targetText { switch (target) { case ReviewTarget.doctor: return 'طبيب'; case ReviewTarget.pharmacy: return 'صيدلية'; case ReviewTarget.lab: return 'مختبر'; case ReviewTarget.hospital: return 'مستشفى'; case ReviewTarget.delivery: return 'توصيل'; case ReviewTarget.service: return 'خدمة'; case ReviewTarget.product: return 'منتج'; case ReviewTarget.order: return 'طلب'; } }
  IconData get targetIcon { switch (target) { case ReviewTarget.doctor: return Icons.local_hospital; case ReviewTarget.pharmacy: return Icons.local_pharmacy; case ReviewTarget.lab: return Icons.science; case ReviewTarget.hospital: return Icons.medical_services; case ReviewTarget.delivery: return Icons.delivery_dining; case ReviewTarget.service: return Icons.stars; case ReviewTarget.product: return Icons.inventory; case ReviewTarget.order: return Icons.shopping_bag; } }
  Color get targetColor { switch (target) { case ReviewTarget.doctor: return Colors.blue; case ReviewTarget.pharmacy: return Colors.green; case ReviewTarget.lab: return Colors.purple; case ReviewTarget.hospital: return Colors.red; case ReviewTarget.delivery: return Colors.orange; case ReviewTarget.service: return Colors.teal; case ReviewTarget.product: return Colors.pink; case ReviewTarget.order: return Colors.amber; } }
  double get averageRating => rating;
  String get ratingText => const ['','سيء','ضعيف','جيد','جيد جداً','ممتاز'][rating.round().clamp(0, 5)];
  Map<String, dynamic> toFirestore() => {'userId': userId, 'userName': userName, 'userPhoto': userPhoto, 'target': target.name, 'targetId': targetId, 'targetName': targetName, 'rating': rating, 'comment': comment, 'images': images, 'tags': tags, 'isVerified': isVerified, 'isAnonymous': isAnonymous, 'likes': likes, 'dislikes': dislikes, 'likedBy': likedBy, 'dislikedBy': dislikedBy, 'metadata': metadata, 'createdAt': createdAt.toIso8601String(), 'updatedAt': updatedAt?.toIso8601String(), 'bookingId': bookingId, 'orderId': orderId, 'providerResponse': providerResponse, 'providerResponseAt': providerResponseAt?.toIso8601String(), 'replies': replies};
  factory ReviewModel.fromFirestore(Map<String, dynamic> data, String id) => ReviewModel(id: id, userId: data['userId']?.toString() ?? '', userName: data['userName']?.toString() ?? '', userPhoto: data['userPhoto']?.toString(), target: _parseTarget(data['target']?.toString() ?? 'service'), targetId: data['targetId']?.toString() ?? '', targetName: data['targetName']?.toString() ?? '', rating: (data['rating'] as num?)?.toDouble() ?? 0, comment: data['comment']?.toString(), images: List<String>.from(data['images'] ?? []), tags: List<String>.from(data['tags'] ?? []), isVerified: data['isVerified'] == true, isAnonymous: data['isAnonymous'] == true, likes: (data['likes'] as num?)?.toInt() ?? 0, dislikes: (data['dislikes'] as num?)?.toInt() ?? 0, likedBy: List<String>.from(data['likedBy'] ?? []), dislikedBy: List<String>.from(data['dislikedBy'] ?? []), metadata: data['metadata'] is Map ? Map<String, dynamic>.from(data['metadata']) : null, createdAt: DateTime.tryParse(data['createdAt']?.toString() ?? '') ?? DateTime.now(), updatedAt: data['updatedAt'] == null ? null : DateTime.tryParse(data['updatedAt'].toString()), bookingId: data['bookingId']?.toString(), orderId: data['orderId']?.toString(), providerResponse: data['providerResponse']?.toString(), providerResponseAt: data['providerResponseAt'] == null ? null : DateTime.tryParse(data['providerResponseAt'].toString()), replies: data['replies'] is List ? List<Map<String, dynamic>>.from((data['replies'] as List).map((e) => Map<String, dynamic>.from(e as Map))) : null);
  static ReviewTarget _parseTarget(String value) => ReviewTarget.values.firstWhere((e) => e.name == value, orElse: () => ReviewTarget.service);
  ReviewModel copyWith({String? comment, double? rating, int? likes, int? dislikes, List<String>? likedBy, List<String>? dislikedBy, bool? isVerified, bool? isAnonymous, DateTime? updatedAt, String? providerResponse, DateTime? providerResponseAt, List<Map<String, dynamic>>? replies}) => ReviewModel(id: id, userId: userId, userName: userName, userPhoto: userPhoto, target: target, targetId: targetId, targetName: targetName, rating: rating ?? this.rating, comment: comment ?? this.comment, images: images, tags: tags, isVerified: isVerified ?? this.isVerified, isAnonymous: isAnonymous ?? this.isAnonymous, likes: likes ?? this.likes, dislikes: dislikes ?? this.dislikes, likedBy: likedBy ?? this.likedBy, dislikedBy: dislikedBy ?? this.dislikedBy, metadata: metadata, createdAt: createdAt, updatedAt: updatedAt ?? this.updatedAt, bookingId: bookingId, orderId: orderId, providerResponse: providerResponse ?? this.providerResponse, providerResponseAt: providerResponseAt ?? this.providerResponseAt, replies: replies ?? this.replies);
}
