import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:equatable/equatable.dart';
class UserModel extends Equatable {
 final String id,name; final String? email,phone,photoUrl,bio,specialty,hospital,location,fcmToken; final bool isDoctor,isPatient,isOnline,isVerified; final double? rating; final int? reviewsCount; final Timestamp? lastSeen; final DateTime? createdAt; final List<String>? blockedUsers,savedDoctors;
 const UserModel({required this.id,this.email,this.phone,required this.name,this.photoUrl,this.bio,this.isDoctor=false,this.isPatient=true,this.specialty,this.hospital,this.location,this.rating,this.reviewsCount,this.isOnline=false,this.lastSeen,this.createdAt,this.fcmToken,this.isVerified=false,this.blockedUsers,this.savedDoctors});
 factory UserModel.fromFirestore(String id,Map<String,dynamic> data)=>UserModel(id:id,email:data['email']?.toString(),phone:data['phone']?.toString(),name:data['name']?.toString()??'مستخدم',photoUrl:data['photoUrl']?.toString(),bio:data['bio']?.toString(),isDoctor:data['isDoctor']==true,isPatient:data['isPatient']!=false,specialty:data['specialty']?.toString(),hospital:data['hospital']?.toString(),location:data['location']?.toString(),rating:(data['rating'] as num?)?.toDouble(),reviewsCount:(data['reviewsCount'] as num?)?.toInt(),isOnline:data['isOnline']==true,lastSeen:data['lastSeen'] is Timestamp?data['lastSeen'] as Timestamp:null,createdAt:data['createdAt'] is Timestamp?(data['createdAt'] as Timestamp).toDate():null,fcmToken:data['fcmToken']?.toString(),isVerified:data['isVerified']==true,blockedUsers:List<String>.from(data['blockedUsers']??const []),savedDoctors:List<String>.from(data['savedDoctors']??const []));
 String get role=>isDoctor?'doctor':'patient';
 Map<String,dynamic> toFirestore()=>{'email':email,'phone':phone,'name':name,'photoUrl':photoUrl,'bio':bio,'isDoctor':isDoctor,'isPatient':isPatient,'specialty':specialty,'hospital':hospital,'location':location,'rating':rating,'reviewsCount':reviewsCount,'isOnline':isOnline,'lastSeen':lastSeen??FieldValue.serverTimestamp(),'createdAt':FieldValue.serverTimestamp(),'fcmToken':fcmToken,'isVerified':isVerified,'blockedUsers':blockedUsers,'savedDoctors':savedDoctors};
 bool get isOnlineNow=>isOnline&&lastSeen!=null&&DateTime.now().difference(lastSeen!.toDate()).inMinutes<5;
 @override List<Object?> get props=>[id,email,phone,name,photoUrl,isDoctor,isOnline,lastSeen,fcmToken];
}
