const admin=require('firebase-admin');const fs=require('fs');const path=require('path');
const keyPath=process.env.GOOGLE_APPLICATION_CREDENTIALS||path.join(process.cwd(),'service-account.json');if(!admin.apps.length){if(fs.existsSync(keyPath))admin.initializeApp({credential:admin.credential.cert(require(keyPath))});else admin.initializeApp({credential:admin.credential.applicationDefault()});}const db=admin.firestore();
const now=admin.firestore.Timestamp.now();
const doctors=(specialties,prefix)=>specialties.map((specialty,i)=>({name:`د. ${prefix} ${['محمد','أحمد','سارة','علي','خالد','ريم'][i]}`,specialty,photoUrl:'',rating:4.5+(i%5)/10,reviewCount:18+i*7,experienceYears:5+i,address:'صنعاء، اليمن',phone:'',isVerified:true,isAvailable:true,createdAt:now,updatedAt:now}));
const clinics=(prefix)=>[1,2,3,4].map(i=>({name:`مركز ${prefix} ${i}`,type:prefix,address:`صنعاء - شارع ${i}`,phone:'',rating:4.3+i/10,isOpen:true}));
const hospitals=(prefix)=>[1,2,3].map(i=>({name:`مستشفى ${prefix} ${i}`,address:`صنعاء - ${i}`,phone:'',emergency:i===1,isOpen:true}));
const tips=(categories,count,prefix)=>Array.from({length:count},(_,i)=>({title:`نصيحة ${prefix} ${i+1}`,body:`معلومة إرشادية رقم ${i+1}: احرصي على المتابعة المنتظمة واستشارة الطبيب عند وجود أي أعراض مقلقة.`,category:categories[i%categories.length],...(prefix==='الحمل'?{week:(i%40)+1}:{}),isPublished:true,createdAt:now}));
async function write(col,rows){const b=db.batch();rows.forEach((r,i)=>b.set(db.collection(col).doc(`${col}_${i+1}`),r,{merge:true}));await b.commit();console.log(col,rows.length);}
async function main(){await write('pregnancy_doctors',doctors(['نساء وتوليد','خصوبة','متابعة حمل','نساء وتوليد','خصوبة','متابعة حمل'],'نسائية'));await write('pregnancy_clinics',clinics('متابعة الحمل'));await write('pregnancy_tips',tips(['تغذية','تمارين','تحاليل','ولادة'],15,'الحمل'));await write('pregnancy_hospitals',hospitals('توليد'));await write('women_doctors',doctors(['نساء','تجميل','غدد','أورام','نساء','غدد'],'صحة المرأة'));await write('women_clinics',clinics('صحة المرأة'));await write('women_tips',tips(['دورة','هرمونات','وقاية','نفسية'],10,'صحة المرأة'));await write('women_hospitals',hospitals('صحة المرأة'));await write('child_doctors',doctors(['أطفال','حديثي الولادة','مناعة','هضمي','أطفال','مناعة'],'أطفال'));await write('child_clinics',clinics('أطفال'));await write('child_tips',tips(['رضاعة','نوم','تغذية','تطعيمات'],12,'صحة الطفل'));await write('child_hospitals',hospitals('أطفال'));console.log('Seed completed.');}main().catch(e=>{console.error(e);process.exit(1);});
