import 'dart:async';
import 'dart:math' as math;
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:pedometer/pedometer.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:sensors_plus/sensors_plus.dart';
import 'package:sehatak/core/models/steps/steps_model.dart';
class StepsService {
 final _firestore=FirebaseFirestore.instance; final _auth=FirebaseAuth.instance; bool _isTracking=false; int _currentSteps=0,_todaySteps=0,_calories=0,_activeMinutes=0; double _distance=0; List<int> _hourlySteps=List.filled(24,0); Timer? _updateTimer; DateTime? _startTime; int _lastStepCount=0;
 StreamSubscription<StepCount>? _stepCountSubscription; StreamSubscription<PedestrianStatus>? _pedestrianStatusSubscription; StreamSubscription<AccelerometerEvent>? _accelerometerSubscription;
 Future<bool> requestPermissions() async=>(await Permission.activityRecognition.request()).isGranted;
 Future<void> startTracking() async{if(_isTracking)return;if(!await requestPermissions())throw Exception('يجب منح إذن الوصول إلى مستشعرات الحركة');_isTracking=true;_startTime=DateTime.now();_currentSteps=0;_todaySteps=await getTodaySteps();_hourlySteps=List.filled(24,0);_startSensorTracking();_updateTimer=Timer.periodic(const Duration(seconds:10),(_)=>_updateStepData());}
 Future<void> stopTracking() async{if(!_isTracking)return;_isTracking=false;_updateTimer?.cancel();_stopSensorTracking();if(_todaySteps>0)await _saveTodayRecord();}
 Future<int> getTodaySteps() async{try{final user=_auth.currentUser;if(user==null)return 0;final t=DateTime.now();final start=DateTime(t.year,t.month,t.day);final snap=await _firestore.collection('steps_records').where('userId',isEqualTo:user.uid).where('date',isEqualTo:start.toIso8601String()).limit(1).get();if(snap.docs.isEmpty)return 0;return StepRecord.fromFirestore(snap.docs.first.data(),snap.docs.first.id).steps;}catch(_){return 0;}}
 Future<List<StepRecord>> getWeeklySteps() async{try{final user=_auth.currentUser;if(user==null)return [];final since=DateTime.now().subtract(const Duration(days:7));final snap=await _firestore.collection('steps_records').where('userId',isEqualTo:user.uid).where('date',isGreaterThanOrEqualTo:since.toIso8601String()).orderBy('date',descending:true).get();return snap.docs.map((d)=>StepRecord.fromFirestore(d.data(),d.id)).toList();}catch(_){return [];}}
 Future<Map<String,dynamic>> getStepsStats() async{final records=await getWeeklySteps();if(records.isEmpty)return {'avgSteps':0,'totalSteps':0,'bestDay':'','totalDistance':0,'totalCalories':0};final totalSteps=records.fold<int>(0,(sum,r)=>sum+r.steps);final avgSteps=totalSteps~/records.length;final totalDistance=records.fold<double>(0,(sum,r)=>sum+r.distance);final totalCalories=records.fold<int>(0,(sum,r)=>sum+r.calories);final bestDay=records.reduce((a,b)=>a.steps>b.steps?a:b);return {'avgSteps':avgSteps,'totalSteps':totalSteps,'bestDay':'${bestDay.date.day}/${bestDay.date.month}','totalDistance':totalDistance/1000,'totalCalories':totalCalories};}
 void _startSensorTracking(){try{_stepCountSubscription=Pedometer.stepCountStream.listen((event){final delta=event.steps-_lastStepCount;if(delta>0){_currentSteps+=delta;_todaySteps+=delta;_lastStepCount=event.steps;_calories+=(delta*0.04).toInt();_distance+=delta*0.0008;_activeMinutes=(_todaySteps/100).toInt();final hour=DateTime.now().hour;if(hour<24)_hourlySteps[hour]+=delta;}},onError:(_)=>_startFallbackTracking());}catch(_){_startFallbackTracking();} _pedestrianStatusSubscription=Pedometer.pedestrianStatusStream.listen((_){});}
 void _startFallbackTracking(){_accelerometerSubscription?.cancel();_accelerometerSubscription=accelerometerEventStream().listen((event){final acceleration=math.sqrt(event.x*event.x+event.y*event.y+event.z*event.z);if(acceleration>12&&acceleration<20){_currentSteps++;_todaySteps++;_calories++;_distance+=0.0008;final hour=DateTime.now().hour;if(hour<24)_hourlySteps[hour]++;}});}
 void _stopSensorTracking(){_stepCountSubscription?.cancel();_pedestrianStatusSubscription?.cancel();_accelerometerSubscription?.cancel();}
 void _updateStepData(){}
 Future<void> _saveTodayRecord() async{try{final user=_auth.currentUser;if(user==null)return;final t=DateTime.now();final start=DateTime(t.year,t.month,t.day);final record=StepRecord(id:_firestore.collection('steps_records').doc().id,userId:user.uid,date:start,steps:_todaySteps,distance:_distance,calories:_calories,activeMinutes:_activeMinutes,hourlySteps:_hourlySteps,createdAt:DateTime.now());await _firestore.collection('steps_records').doc(record.id).set(record.toFirestore());}catch(_){}}
}
